In [1]:
# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Importing required packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Loading the data using Pandas
f1all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_1.xlsx')
f1all.columns = f1all.columns.str.lower()
f1all.columns = f1all.columns.str.strip()
f1all.columns = f1all.columns.str.replace(' |\n', '_')
f1all.columns = f1all.columns.str.replace('__', '_')
f1all['area_name'] = f1all['area_name'].str.replace('\d+', '')
f1all = f1all.applymap(lambda s:s.lower() if type(s) == str else s)
f1all.drop(['table_name'], inplace = True, axis = 1)
f1all['area_name'].astype(object)
f1all['area_name'] = f1all['area_name'].str.strip(' ')
f1all = f1all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f1all['total_ever_unmarried_women'] = f1all['total_women'] - f1all['total_ever_married_women']
f1all = f1all.set_axis(['state_code','distt._code', 'area_name', 'total/_rural/_urban', 'present_age','total_women', 'total_ever_married_women', 'parity_0', 'parity_1','parity_2', 'parity_3', 'parity_4', 'parity_5', 'parity_6', 'parity_7+','total_children_ever_born_p', 'total_children_ever_born_m','total_children_ever_born_f', 'all/sc/st','total_ever_unmarried_women'], axis=1, inplace=False)
f1all = f1all.drop_duplicates()
f1all = f1all.reset_index(drop=True)
f1all

,state_code,distt._code,area_name,total/_rural/_urban,present_age,total_women,total_ever_married_women,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,parity_7+,total_children_ever_born_p,total_children_ever_born_m,total_children_ever_born_f,all/sc/st,total_ever_unmarried_women
0,0,0,india,total,all_ages,587584719,339621277,49549956,50938514,81485683,60424480,40104260,23742379,14490504,18885501,915091154,484056967,431034187,all,247963442
1,0,0,india,total,less_than_15,178092741,1812200,1355195,136777,320228,0,0,0,0,0,777233,409134,368099,all,176280541
2,0,0,india,total,15-19,56544053,11229274,7880413,2243929,605514,215480,283938,0,0,0,5237149,2756470,2480679,all,45314779
3,0,0,india,total,20-24,53839529,37474855,12988953,12869090,8233549,2313647,621922,173729,81731,192234,41586014,21561931,20024083,all,16364674
4,0,0,india,total,25-29,50069757,45672215,7339229,10679349,15526465,7645252,2928732,904274,300426,348488,85628118,44420283,41207835,all,4397542
5,0,0,india,total,30-34,43934277,42494507,4023079,6023364,14151441,9320303,5015730,2244085,971625,744880,105395588,54734319,50661269,all,1439770
6,0,0,india,total,35-39,42221303,41450644,3016555,4570772,12304652,9516997,5807387,3118589,1673920,1441772,117975584,61659870,56315714,all,770659
7,0,0,india,total,40-44,34892726,34387860,2344859,3329727,8936013,7923419,5206741,2997388,1761298,1888415,106474619,56237822,50236797,all,504866
8,0,0,india,total,45-49,30180213,29817709,2008994,2760932,6816920,6769669,4760289,2847244,1729336,2124325,97576047,52039198,45536849,all,362504
9,0,0,india,total,50-54,23225988,22939799,1669427,2020968,4556777,4966315,3857000,2414091,1489107,1966114,78514964,42219701,36295263,all,286189
10,0,0,india,total,55-59,19690043,19470703,1462535,1647013,3288765,3847488,3368657,2295387,1480474,2080384,70654084,38082338,32571746,all,219340
11,0,0,india,total,60-64,18961958,18655119,1650929,1596864,2652290,3222529,3170839,2371256,1617653,2372759,70271304,37713605,32557699,all,306839
12,0,0,india,total,65-69,13510657,13238971,1269964,1096229,1631351,2016196,2167399,1772096,1289478,1996258,52047320,27892742,24154578,all,271686
13,0,0,india,total,70-74,9557343,9407217,1034232,818312,1062571,1253207,1414007,1246132,968009,1610747,37634373,20105036,17529337,all,150126
14,0,0,india,total,75-79,4741900,4665395,510889,400213,494527,570271,658133,614382,507206,909774,19355312,10348646,9006666,all,76505
15,0,0,india,total,80+,6005310,5734942,736640,562378,648501,662172,722979,672639,577502,1152131,23163719,12366185,10797534,all,270368
16,0,0,india,rural,all_ages,405967794,231577616,32236179,31209941,50881956,42277640,29885474,18442740,11504284,15139402,663799305,350248381,313550924,all,174390178
17,0,0,india,rural,less_than_15,131248972,1283307,967264,91051,224992,0,0,0,0,0,541035,284502,256533,all,129965665
18,0,0,india,rural,15-19,39331915,8604139,6007335,1760923,453369,160834,221678,0,0,0,4036875,2123490,1913385,all,30727776
19,0,0,india,rural,20-24,35696384,26974563,8810253,9299895,6228066,1813934,488243,135235,61596,137341,31242074,16180930,15061144,all,8721821
20,0,0,india,rural,25-29,32692281,30709055,4181564,6392891,10722730,5853060,2336081,736924,241169,244636,61908092,32061962,29846130,all,1983226
21,0,0,india,rural,30-34,28977587,28294613,2290910,3190428,8776569,6845642,3954381,1844850,809831,582002,75813566,39253435,36560131,all,682974
22,0,0,india,rural,35-39,27937146,27549682,1759324,2388394,7176519,6687820,4444618,2515794,1385123,1192090,84842156,44181585,40660571,all,387464
23,0,0,india,rural,40-44,23015773,22761435,1394285,1731105,4995523,5381395,3887038,2371413,1436341,1564335,76390722,40194412,36196310,all,254338
24,0,0,india,rural,45-49,19823958,19645985,1207940,1457855,3740940,4452060,3457349,2199891,1384432,1745518,69570342,36961595,32608747,all,177973
25,0,0,india,rural,50-54,15242241,15106685,1027124,1073974,2469009,3193971,2743035,1830531,1173317,1595724,55785094,29864621,25920473,all,135556
26,0,0,india,rural,55-59,13324985,13223051,924276,925462,1850357,2505805,2409160,1746042,1168132,1693817,51408554,27628896,23779658,all,101934
27,0,0,india,rural,60-64,13359653,13183737,1110359,982264,1624203,2173212,2295235,1807142,1271179,1920143,52347237,28045326,24301911,all,175916
28,0,0,india,rural,65-69,9707959,9548318,876094,700881,1048942,1391591,1577474,1345082,1005704,1602550,39199375,20997218,18202157,all,159641
29,0,0,india,rural,70-74,6829421,6744747,713376,523764,694098,864127,1017881,929206,738164,1264131,28052415,14990948,13061467,all,84674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92754,35,640,district_-_south_andaman,rural,15-19,91,14,7,3,3,1,0,0,0,0,12,5,7,st,77
92755,35,640,district_-_south_andaman,rural,20-24,101,44,13,13,11,5,1,1,0,0,59,26,33,st,57
92756,35,640,district_-_south_andaman,rural,25-29,107,86,19,28,21,10,5,1,1,1,139,69,70,st,21
92757,35,640,district_-_south_andaman,rural,30-34,100,94,14,22,40,9,5,2,2,0,171,91,80,st,6
92758,35,640,district_-_south_andaman,rural,35-39,87,81,8,13,28,18,6,3,1,4,200,101,99,st,6
92759,35,640,district_-_south_andaman,rural,40-44,78,73,11,14,23,15,7,0,2,1,152,87,65,st,5
92760,35,640,district_-_south_andaman,rural,45-49,67,62,14,12,14,12,7,2,0,1,122,61,61,st,5
92761,35,640,district_-_south_andaman,rural,50-54,36,36,4,7,12,6,4,2,0,1,83,55,28,st,0
92762,35,640,district_-_south_andaman,rural,55-59,27,27,8,9,6,1,3,0,0,0,36,18,18,st,0
92763,35,640,district_-_south_andaman,rural,60-64,23,23,10,3,2,4,2,0,1,1,40,25,15,st,0
92764,35,640,district_-_south_andaman,rural,65-69,11,11,5,2,2,0,1,0,1,0,16,7,9,st,0
92765,35,640,district_-_south_andaman,rural,70-74,11,11,5,2,1,1,1,0,0,1,18,7,11,st,0
92766,35,640,district_-_south_andaman,rural,75-79,8,8,3,1,4,0,0,0,0,0,9,6,3,st,0
92767,35,640,district_-_south_andaman,rural,80+,3,3,0,1,0,0,1,0,0,1,12,7,5,st,0
92768,35,640,district_-_south_andaman,urban,all_ages,916,387,61,71,133,69,34,13,2,4,792,382,410,st,529
92769,35,640,district_-_south_andaman,urban,less_than_15,246,2,1,0,1,0,0,0,0,0,2,2,0,st,244
92770,35,640,district_-_south_andaman,urban,15-19,94,6,6,0,0,0,0,0,0,0,0,0,0,st,88
92771,35,640,district_-_south_andaman,urban,20-24,147,24,10,10,3,1,0,0,0,0,19,9,10,st,123
92772,35,640,district_-_south_andaman,urban,25-29,112,64,22,16,20,3,1,2,0,0,79,30,49,st,48
92773,35,640,district_-_south_andaman,urban,30-34,90,76,8,16,37,13,2,0,0,0,137,72,65,st,14
92774,35,640,district_-_south_andaman,urban,35-39,72,69,5,9,33,15,6,0,0,1,153,70,83,st,3
92775,35,640,district_-_south_andaman,urban,40-44,60,57,5,6,17,18,10,1,0,0,139,65,74,st,3
92776,35,640,district_-_south_andaman,urban,45-49,39,36,2,4,12,6,8,2,1,1,101,50,51,st,3
92777,35,640,district_-_south_andaman,urban,50-54,34,33,1,6,8,8,4,5,1,0,93,49,44,st,1
92778,35,640,district_-_south_andaman,urban,55-59,14,12,0,2,1,4,1,3,0,1,42,21,21,st,2
92779,35,640,district_-_south_andaman,urban,60-64,3,3,1,0,0,1,1,0,0,0,7,1,6,st,0
92780,35,640,district_-_south_andaman,urban,65-69,1,1,0,1,0,0,0,0,0,0,1,1,0,st,0
92781,35,640,district_-_south_andaman,urban,70-74,4,4,0,1,1,0,1,0,0,1,19,12,7,st,0
92782,35,640,district_-_south_andaman,urban,75-79,0,0,0,0,0,0,0,0,0,0,0,0,0,st,0
92783,35,640,district_-_south_andaman,urban,80+,0,0,0,0,0,0,0,0,0,0,0,0,0,st,0

In [4]:
f1all['parity_0_%'] = (f1all['parity_0'] /f1all['total_ever_married_women'])*100

In [5]:
f1all['parity_1_%'] = (f1all['parity_1'] /f1all['total_ever_married_women'])*100

In [6]:
f1all['parity_2_%'] = (f1all['parity_2'] /f1all['total_ever_married_women'])*100

In [7]:
f1all['parity_3_%'] = (f1all['parity_3'] /f1all['total_ever_married_women'])*100

In [8]:
f1all['parity_4_%'] = (f1all['parity_4'] /f1all['total_ever_married_women'])*100

In [9]:
f1all['parity_5_%'] = (f1all['parity_5'] /f1all['total_ever_married_women'])*100

In [10]:
f1all['parity_6_%'] = (f1all['parity_6'] /f1all['total_ever_married_women'])*100

In [11]:
f1all['parity_7+_%'] = (f1all['parity_7+'] /f1all['total_ever_married_women'])*100

In [12]:
f1all['total_ever_married_women_%'] = (f1all['total_ever_married_women'] /f1all['total_women'])*100

In [13]:
f1all['total_ever_unmarried_women_%'] = (f1all['total_ever_unmarried_women'] /f1all['total_women'])*100

In [14]:
f1all['total_children_ever_born_m_%'] = (f1all['total_children_ever_born_m']/f1all['total_children_ever_born_p'] )*100

In [15]:
f1all['total_children_ever_born_f_%'] = (f1all['total_children_ever_born_f'].div(f1all['total_children_ever_born_p'].where(f1all['total_children_ever_born_p'] != 0, np.nan)))*100

In [16]:
f1all.dropna(axis = 0, inplace = True)

In [17]:
# Loading the data using Pandas
f2all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_2.xlsx')
f2all.columns = f2all.columns.str.lower()
f2all.columns = f2all.columns.str.strip()
f2all.columns = f2all.columns.str.replace(' |\n', '_')
f2all.columns = f2all.columns.str.replace('__', '_')
f2all = f2all.applymap(lambda s:s.lower() if type(s) == str else s)
f2all['area_name'] = f2all['area_name'].str.replace('\d+', '')
f2all.drop(['table_name'], inplace = True, axis = 1)
f2all['area_name'].astype(object)
f2all['area_name'] = f2all['area_name'].str.strip(' ')
f2all = f2all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f2all['total_ever_unmarried_women'] = f2all['total_women'] - f2all['total_ever_married_women']
f2all = f2all.set_axis(['state_code','distt._code', 'area_name', 'total/_rural/_urban', 'religious_community','present_age', 'total_women', 'total_ever_married_women', 'parity_0','parity_1', 'parity_2', 'parity_3', 'parity_4', 'parity_5', 'parity_6','parity_7+', 'total_children_ever_born_p', 'total_children_ever_born_m','total_children_ever_born_f', 'total_ever_unmarried_women'], axis=1, inplace=False)
f2all = f2all.drop_duplicates()
f2all = f2all.reset_index(drop=True)
f2all.head()

,state_code,distt._code,area_name,total/_rural/_urban,religious_community,present_age,total_women,total_ever_married_women,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,parity_7+,total_children_ever_born_p,total_children_ever_born_m,total_children_ever_born_f,total_ever_unmarried_women
0,0,0,india,total,all_religious_communities,all_ages,587584719,339621277,49549956,50938514,81485683,60424480,40104260,23742379,14490504,18885501,915091154,484056967,431034187,247963442
1,0,0,india,total,all_religious_communities,less_than_15,178092741,1812200,1355195,136777,320228,0,0,0,0,0,777233,409134,368099,176280541
2,0,0,india,total,all_religious_communities,15-19,56544053,11229274,7880413,2243929,605514,215480,283938,0,0,0,5237149,2756470,2480679,45314779
3,0,0,india,total,all_religious_communities,20-24,53839529,37474855,12988953,12869090,8233549,2313647,621922,173729,81731,192234,41586014,21561931,20024083,16364674
4,0,0,india,total,all_religious_communities,25-29,50069757,45672215,7339229,10679349,15526465,7645252,2928732,904274,300426,348488,85628118,44420283,41207835,4397542

In [18]:
f2all.dropna(axis = 0, inplace = True)

In [19]:
f2all['parity_0_%'] = (f2all['parity_0'] /f2all['total_ever_married_women'])*100

In [20]:
f2all['parity_1_%'] = (f2all['parity_1'] /f2all['total_ever_married_women'])*100

In [21]:
f2all['parity_2_%'] = (f2all['parity_2'] /f2all['total_ever_married_women'])*100

In [22]:
f2all['parity_3_%'] = (f2all['parity_3'] /f2all['total_ever_married_women'])*100

In [23]:
f2all['parity_4_%'] = (f2all['parity_4'] /f2all['total_ever_married_women'])*100

In [24]:
f2all['parity_5_%'] = (f2all['parity_5'] /f2all['total_ever_married_women'])*100

In [25]:
f2all['parity_6_%'] = (f2all['parity_6'] /f2all['total_ever_married_women'])*100

In [26]:
f2all['parity_7+_%'] = (f2all['parity_7+'] /f2all['total_ever_married_women'])*100

In [27]:
f2all['total_ever_married_women_%'] = (f2all['total_ever_married_women'] /f2all['total_women'])*100

In [28]:
f2all['total_ever_unmarried_women_%'] = (f2all['total_ever_unmarried_women'] /f2all['total_women'])*100

In [29]:
f2all['total_children_ever_born_m_%'] = (f2all['total_children_ever_born_m']/f2all['total_children_ever_born_p'] )*100

In [30]:
f2all['total_children_ever_born_f_%'] = (f2all['total_children_ever_born_f'].div(f2all['total_children_ever_born_p'].where(f2all['total_children_ever_born_p'] != 0, np.nan)))*100

In [31]:
f2all.dropna(axis = 0, inplace = True)

In [32]:
# Loading the data using Pandas
f3all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_3.xlsx')
f3all.columns = f3all.columns.str.lower()
f3all.columns = f3all.columns.str.strip()
f3all.columns = f3all.columns.str.replace(' |\n', '_')
f3all.columns = f3all.columns.str.replace('__', '_')
f3all = f3all.applymap(lambda s:s.lower() if type(s) == str else s)
f3all['area_name'] = f3all['area_name'].str.replace('\d+', '')
f3all.drop(['table_name'], inplace = True, axis = 1)
f3all['area_name'].astype(object)
f3all['area_name'] = f3all['area_name'].str.strip(' ')
f3all = f3all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f3all['total_ever_unmarried_women'] = f3all['total_women'] - f3all['total_ever_married_women']
f3all = f3all.set_axis(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban', 'educational_level','present_age', 'total_women', 'total_ever_married_women', 'parity_0','parity_1', 'parity_2', 'parity_3', 'parity_4', 'parity_5', 'parity_6','parity_7+', 'total_children_ever_born_p', 'total_children_ever_born_m','total_children_ever_born_f', 'total_ever_unmarried_women'], axis=1, inplace=False)
f3all = f3all.drop_duplicates()
f3all = f3all.reset_index(drop=True)
f3all.head()

,state_code,distt._code,area_name,total/_rural/_urban,educational_level,present_age,total_women,total_ever_married_women,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,parity_7+,total_children_ever_born_p,total_children_ever_born_m,total_children_ever_born_f,total_ever_unmarried_women
0,0,0,india,total,total,all_ages,587584719,339621277,49549956,50938514,81485683,60424480,40104260,23742379,14490504,18885501,915091154,484056967,431034187,247963442
1,0,0,india,total,total,less_than_15,178092741,1812200,1355195,136777,320228,0,0,0,0,0,777233,409134,368099,176280541
2,0,0,india,total,total,15-19,56544053,11229274,7880413,2243929,605514,215480,283938,0,0,0,5237149,2756470,2480679,45314779
3,0,0,india,total,total,20-24,53839529,37474855,12988953,12869090,8233549,2313647,621922,173729,81731,192234,41586014,21561931,20024083,16364674
4,0,0,india,total,total,25-29,50069757,45672215,7339229,10679349,15526465,7645252,2928732,904274,300426,348488,85628118,44420283,41207835,4397542

In [33]:
f3all.columns

Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'educational_level', 'present_age', 'total_women',
       'total_ever_married_women', 'parity_0', 'parity_1', 'parity_2',
       'parity_3', 'parity_4', 'parity_5', 'parity_6', 'parity_7+',
       'total_children_ever_born_p', 'total_children_ever_born_m',
       'total_children_ever_born_f', 'total_ever_unmarried_women'],
      dtype='object')

In [34]:
f3all['parity_0_%'] = (f3all['parity_0'] /f3all['total_ever_married_women'])*100

In [35]:
f3all['parity_1_%'] = (f3all['parity_1'] /f3all['total_ever_married_women'])*100

In [36]:
f3all['parity_2_%'] = (f3all['parity_2'] /f3all['total_ever_married_women'])*100

In [37]:
f3all['parity_3_%'] = (f3all['parity_3'] /f3all['total_ever_married_women'])*100

In [38]:
f3all['parity_4_%'] = (f3all['parity_4'] /f3all['total_ever_married_women'])*100

In [39]:
f3all['parity_5_%'] = (f3all['parity_5'] /f3all['total_ever_married_women'])*100

In [40]:
f3all['parity_6_%'] = (f3all['parity_6'] /f3all['total_ever_married_women'])*100

In [41]:
f3all['parity_7+_%'] = (f3all['parity_7+'] /f3all['total_ever_married_women'])*100

In [42]:
f3all['total_ever_married_women_%'] = (f3all['total_ever_married_women'] /f3all['total_women'])*100

In [43]:
f3all['total_ever_unmarried_women_%'] = (f3all['total_ever_unmarried_women'] /f3all['total_women'])*100

In [44]:
f3all['total_children_ever_born_m_%'] = (f3all['total_children_ever_born_m']/f3all['total_children_ever_born_p'] )*100

In [45]:
f3all['total_children_ever_born_f_%'] = (f3all['total_children_ever_born_f'].div(f3all['total_children_ever_born_p'].where(f3all['total_children_ever_born_p'] != 0, np.nan)))*100

In [46]:
# Loading the data using Pandas
f4all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_4.xlsx')
f4all.columns = f4all.columns.str.lower()
f4all.columns = f4all.columns.str.strip()
f4all.columns = f4all.columns.str.replace(' |\n', '_')
f4all.columns = f4all.columns.str.replace('__', '_')
f4all = f4all.applymap(lambda s:s.lower() if type(s) == str else s)
f4all.drop(['table_name', 'unnamed:_20'], inplace = True, axis = 1)
f4all['area_name'].astype(object)
f4all['area_name'] = f4all['area_name'].str.strip(' ')
f4all['total_ever_unmarried_women'] = f4all['total_women'] - f4all['total_ever_married_women']
f4all = f4all.drop_duplicates()
f4all = f4all.reset_index(drop=True)
f4all.head()

,state_code,district_code,area_name,total/rural/urban,economic_activity,present_age,total_women,total_ever_married_women,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,parity_7+,total_children_ever_born_p,total_children_ever_born_m,total_children_ever_born_f,total_ever_unmarried_women
0,0,0,india,total,total main workers,all ages,89355595,79738242,11700343,11311195,20447070,15232303,9456578,5195307,2938369,3457077,207332289,107829676,99502613,9617353
1,0,0,india,total,total main workers,less than 15,1689200,154674,68910,21309,64455,0,0,0,0,0,150219,79802,70417,1534526
2,0,0,india,total,total main workers,15-19,4981419,1869335,1219764,410605,133430,48821,56715,0,0,0,1050788,551713,499075,3112084
3,0,0,india,total,total main workers,20-24,9686759,7307549,2442851,2270228,1825652,538923,139479,37653,16607,36156,8659394,4490442,4168952,2379210
4,0,0,india,total,total main workers,25-29,11764723,10503248,1917666,2077487,3624829,1851625,682953,207586,67228,73874,19671057,10200574,9470483,1261475

In [47]:
f4all['economic_activity'] = f4all['economic_activity'].str.strip()
f4all['economic_activity'] = f4all['economic_activity'].replace({'(a) cultivators':'cultivators','(b) agricultural labourers':'agricultural labourers','(c) other main workers':'other main workers','(d) other workers':'other workers','(c) household industry workers':'household industry workers','(ii) non-manual':'non-manual'})
f4all['economic_activity'].unique()

array(['total main workers', 'cultivators', 'agricultural labourers',
       'household industry workers', 'other workers', 'marginal workers',
       'non-workers'], dtype=object)

In [48]:
f4all = f4all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)

In [49]:
f4all['parity_0_%'] = (f4all['parity_0'] /f4all['total_ever_married_women'])*100

In [50]:
f4all['parity_1_%'] = (f4all['parity_1'] /f4all['total_ever_married_women'])*100

In [51]:
f4all['parity_2_%'] = (f4all['parity_2'] /f4all['total_ever_married_women'])*100

In [52]:
f4all['parity_3_%'] = (f4all['parity_3'] /f4all['total_ever_married_women'])*100

In [53]:
f4all['parity_4_%'] = (f4all['parity_4'] /f4all['total_ever_married_women'])*100

In [54]:
f4all['parity_5_%'] = (f4all['parity_5'] /f4all['total_ever_married_women'])*100

In [55]:
f4all['parity_6_%'] = (f4all['parity_6'] /f4all['total_ever_married_women'])*100

In [56]:
f4all['parity_7+_%'] = (f4all['parity_7+'] /f4all['total_ever_married_women'])*100

In [57]:
f4all['total_ever_married_women_%'] = (f4all['total_ever_married_women'] /f4all['total_women'])*100

In [58]:
f4all['total_ever_unmarried_women_%'] = (f4all['total_ever_unmarried_women'] /f4all['total_women'])*100

In [59]:
f4all['total_children_ever_born_m_%'] = (f4all['total_children_ever_born_m']/f4all['total_children_ever_born_p'] )*100

In [60]:
f4all['total_children_ever_born_f_%'] = (f4all['total_children_ever_born_f'].div(f4all['total_children_ever_born_p'].where(f4all['total_children_ever_born_p'] != 0, np.nan)))*100

In [61]:
# Loading the data using Pandas
f5all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_5.xlsx')
f5all.dropna(axis = 0, inplace = True)
f5all.columns = f5all.columns.str.lower()
f5all.columns = f5all.columns.str.strip()
f5all.columns = f5all.columns.str.replace(' |\n', '_')
f5all.columns = f5all.columns.str.replace('__', '_')
f5all['area_name'] = f5all['area_name'].str.replace('\d+', '')
f5all = f5all.applymap(lambda s:s.lower() if type(s) == str else s)
f5all.drop(['table_name'], inplace = True, axis = 1)
f5all['area_name'].astype(object)
f5all['total_ever_unmarried_women'] = f5all['total_women'] - f5all['total_ever_married_women']
f5all = f5all.set_axis(['state_code','distt._code','area_name','total/_rural/_urban', 'present_age', 'total_women','total_ever_married_women', 'no._of_surv._child._0','no._of_surv._child._1', 'no._of_surv._child._2','no._of_surv._child._3', 'no._of_surv._child._4','no._of_surv._child._5+', 'ttl_surv._child._p','ttl_surv._child._m', 'ttl_surv._child._f', 'all/sc/st','total_ever_unmarried_women'], axis=1, inplace=False)
f5all['area_name'] = f5all['area_name'].str.strip(' ')
f5all['total_ever_unmarried_women'] = f5all['total_women'] - f5all['total_ever_married_women']
f5all = f5all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f5all = f5all.drop_duplicates()
f5all = f5all.reset_index(drop=True)
f5all.head()

,state_code,distt._code,area_name,total/_rural/_urban,present_age,total_women,total_ever_married_women,no._of_surv._child._0,no._of_surv._child._1,no._of_surv._child._2,no._of_surv._child._3,no._of_surv._child._4,no._of_surv._child._5+,ttl_surv._child._p,ttl_surv._child._m,ttl_surv._child._f,all/sc/st,total_ever_unmarried_women
0,0,0,india,total,all_ages,587584719,339621277,54482587,55823796,86065258,62275797,38761066,42212773,819694674,435169066,384525608,all,247963442
1,0,0,india,total,less_than_15,178092741,1812200,1386595,130556,295049,0,0,0,720654,379921,340733,all,176280541
2,0,0,india,total,15-19,56544053,11229274,8067901,2196387,559002,189650,216334,0,4748677,2486066,2262611,all,45314779
3,0,0,india,total,20-24,53839529,37474855,13831266,13034246,7932850,1986820,434394,255279,38187539,19730524,18457015,all,16364674
4,0,0,india,total,25-29,50069757,45672215,8131553,11292647,15698345,7257321,2382168,910181,79284181,41079386,38204795,all,4397542

In [62]:
f5all.columns

Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'present_age', 'total_women', 'total_ever_married_women',
       'no._of_surv._child._0', 'no._of_surv._child._1',
       'no._of_surv._child._2', 'no._of_surv._child._3',
       'no._of_surv._child._4', 'no._of_surv._child._5+', 'ttl_surv._child._p',
       'ttl_surv._child._m', 'ttl_surv._child._f', 'all/sc/st',
       'total_ever_unmarried_women'],
      dtype='object')

In [63]:
f5all['total_ever_unmarried_women_%'] = (f5all['total_ever_unmarried_women'] /f5all['total_women'])*100

In [64]:
f5all['total_ever_married_women_%'] = (f5all['total_ever_married_women'] /f5all['total_women'])*100

In [65]:
f5all['ttl_surv._child._m_%'] = (f5all['ttl_surv._child._m'] /f5all['ttl_surv._child._p'])*100

In [66]:
f5all['ttl_surv._child._f_%'] = (f5all['ttl_surv._child._f'] /f5all['ttl_surv._child._p'])*100

In [67]:
f5all['no._of_surv._child._0_%'] = (f5all['no._of_surv._child._0'] /f5all['total_ever_married_women'])*100

In [68]:
f5all['no._of_surv._child._1_%'] = (f5all['no._of_surv._child._1'] /f5all['total_ever_married_women'])*100

In [69]:
f5all['no._of_surv._child._2_%'] = (f5all['no._of_surv._child._2'] /f5all['total_ever_married_women'])*100

In [70]:
f5all['no._of_surv._child._3_%'] = (f5all['no._of_surv._child._3'] /f5all['total_ever_married_women'])*100

In [71]:
f5all['no._of_surv._child._4_%'] = (f5all['no._of_surv._child._4'] /f5all['total_ever_married_women'])*100

In [72]:
f5all['no._of_surv._child._5+_%'] = (f5all['no._of_surv._child._5+'] /f5all['total_ever_married_women'])*100

In [73]:
f5all.dropna(axis = 0, inplace = True)

In [74]:
# Loading the data using Pandas
f6all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_6.xlsx')
f6all.dropna(axis = 0, inplace = True)
f6all.columns = f6all.columns.str.lower()
f6all.columns = f6all.columns.str.strip()
f6all.columns = f6all.columns.str.replace(' |\n', '_')
f6all.columns = f6all.columns.str.replace('__', '_')
f6all = f6all.applymap(lambda s:s.lower() if type(s) == str else s)
f6all['area_name'] = f6all['area_name'].str.replace('\d+', '')
f6all.drop(['table_name'], inplace = True, axis = 1)
f6all['area_name'].astype(object)
f6all['area_name'] = f6all['area_name'].str.strip(' ')
f6all['total_ever_unmarried_women'] = f6all['total_women'] - f6all['total_ever_married_women']
f6all = f6all.set_axis(['state_code','distt._code','area_name','total/_rural/_urban', 'religious_community','present_age', 'total_women','total_ever_married_women', 'no._of_surv._child._0','no._of_surv._child._1', 'no._of_surv._child._2','no._of_surv._child._3', 'no._of_surv._child._4','no._of_surv._child._5+', 'ttl_surv._child._p','ttl_surv._child._m', 'ttl_surv._child._f','total_ever_unmarried_women'], axis=1, inplace=False)
f6all = f6all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f6all = f6all.drop_duplicates()
f6all = f6all.reset_index(drop=True)
f6all.head()

,state_code,distt._code,area_name,total/_rural/_urban,religious_community,present_age,total_women,total_ever_married_women,no._of_surv._child._0,no._of_surv._child._1,no._of_surv._child._2,no._of_surv._child._3,no._of_surv._child._4,no._of_surv._child._5+,ttl_surv._child._p,ttl_surv._child._m,ttl_surv._child._f,total_ever_unmarried_women
0,0,0,india,total,all_religious_communities,all_ages,587584719,339621277,54482587,55823796,86065258,62275797,38761066,42212773,819694674,435169066,384525608,247963442
1,0,0,india,total,all_religious_communities,less_than_15,178092741,1812200,1386595,130556,295049,0,0,0,720654,379921,340733,176280541
2,0,0,india,total,all_religious_communities,15-19,56544053,11229274,8067901,2196387,559002,189650,216334,0,4748677,2486066,2262611,45314779
3,0,0,india,total,all_religious_communities,20-24,53839529,37474855,13831266,13034246,7932850,1986820,434394,255279,38187539,19730524,18457015,16364674
4,0,0,india,total,all_religious_communities,25-29,50069757,45672215,8131553,11292647,15698345,7257321,2382168,910181,79284181,41079386,38204795,4397542

In [75]:
f6all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273024 entries, 0 to 273023
Data columns (total 18 columns):
state_code                    273024 non-null int64
distt._code                   273024 non-null int64
area_name                     273024 non-null object
total/_rural/_urban           273024 non-null object
religious_community           273024 non-null object
present_age                   273024 non-null object
total_women                   273024 non-null int64
total_ever_married_women      273024 non-null int64
no._of_surv._child._0         273024 non-null int64
no._of_surv._child._1         273024 non-null int64
no._of_surv._child._2         273024 non-null int64
no._of_surv._child._3         273024 non-null int64
no._of_surv._child._4         273024 non-null int64
no._of_surv._child._5+        273024 non-null int64
ttl_surv._child._p            273024 non-null int64
ttl_surv._child._m            273024 non-null int64
ttl_surv._child._f            273024 non-null int64
total_ever_unmarried_women    273024 non-null int64
dtypes: int64(14), object(4)
memory usage: 37.5+ MB

In [76]:
f6all['total_ever_unmarried_women_%'] = (f6all['total_ever_unmarried_women'] /f6all['total_women'])*100

In [77]:
f6all['total_ever_married_women_%'] = (f6all['total_ever_married_women'] /f6all['total_women'])*100

In [78]:
f6all['ttl_surv._child._m_%'] = (f6all['ttl_surv._child._m'] /f6all['ttl_surv._child._p'])*100

In [79]:
f6all['ttl_surv._child._f_%'] = (f6all['ttl_surv._child._f'] /f6all['ttl_surv._child._p'])*100

In [80]:
f6all['no._of_surv._child._0_%'] = (f6all['no._of_surv._child._0'] /f6all['total_ever_married_women'])*100

In [81]:
f6all['no._of_surv._child._1_%'] = (f6all['no._of_surv._child._1'] /f6all['total_ever_married_women'])*100

In [82]:
f6all['no._of_surv._child._2_%'] = (f6all['no._of_surv._child._2'] /f6all['total_ever_married_women'])*100

In [83]:
f6all['no._of_surv._child._3_%'] = (f6all['no._of_surv._child._3'] /f6all['total_ever_married_women'])*100

In [84]:
f6all['no._of_surv._child._4_%'] = (f6all['no._of_surv._child._4'] /f6all['total_ever_married_women'])*100

In [85]:
f6all['no._of_surv._child._5+_%'] = (f6all['no._of_surv._child._5+'] /f6all['total_ever_married_women'])*100

In [86]:
f6all.dropna(axis = 0, inplace = True)

In [87]:
# Loading the data using Pandas
f7all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_7.xlsx')
f7all.dropna(axis = 0, inplace = True)
f7all.columns = f7all.columns.str.lower()
f7all.columns = f7all.columns.str.strip()
f7all.columns = f7all.columns.str.replace(' |\n', '_')
f7all.columns = f7all.columns.str.replace('__', '_')
f7all['area_name'] = f7all['area_name'].str.replace('\d+', '')
f7all = f7all.applymap(lambda s:s.lower() if type(s) == str else s)
f7all.drop(['table_name'], inplace = True, axis = 1)
f7all['area_name'].astype(object)
f7all['area_name'] = f7all['area_name'].str.strip(' ')
f7all['total_ever_unmarried_women'] = f7all['total_women'] - f7all['total_ever_married_women']
f7all = f7all.set_axis(['state_code','distt._code','area_name','total/_rural/_urban', 'educational_level','present_age', 'total_women','total_ever_married_women', 'no._of_surv._child._0','no._of_surv._child._1', 'no._of_surv._child._2','no._of_surv._child._3', 'no._of_surv._child._4','no._of_surv._child._5+', 'ttl_surv._child._p','ttl_surv._child._m', 'ttl_surv._child._f','total_ever_unmarried_women'], axis=1, inplace=False)
f7all = f7all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f7all = f7all.drop_duplicates()
f7all = f7all.reset_index(drop=True)
f7all.head()

,state_code,distt._code,area_name,total/_rural/_urban,educational_level,present_age,total_women,total_ever_married_women,no._of_surv._child._0,no._of_surv._child._1,no._of_surv._child._2,no._of_surv._child._3,no._of_surv._child._4,no._of_surv._child._5+,ttl_surv._child._p,ttl_surv._child._m,ttl_surv._child._f,total_ever_unmarried_women
0,0,0,india,total,total,all_ages,587584719,339621277,54482587,55823796,86065258,62275797,38761066,42212773,819694674,435169066,384525608,247963442
1,0,0,india,total,total,less_than_15,178092741,1812200,1386595,130556,295049,0,0,0,720654,379921,340733,176280541
2,0,0,india,total,total,15-19,56544053,11229274,8067901,2196387,559002,189650,216334,0,4748677,2486066,2262611,45314779
3,0,0,india,total,total,20-24,53839529,37474855,13831266,13034246,7932850,1986820,434394,255279,38187539,19730524,18457015,16364674
4,0,0,india,total,total,25-29,50069757,45672215,8131553,11292647,15698345,7257321,2382168,910181,79284181,41079386,38204795,4397542

In [88]:
f7all['total_ever_unmarried_women_%'] = (f7all['total_ever_unmarried_women'] /f7all['total_women'])*100
f7all['total_ever_unmarried_women_%'] = (f7all['total_ever_unmarried_women'] /f7all['total_women'])*100
f7all['total_ever_married_women_%'] = (f7all['total_ever_married_women'] /f7all['total_women'])*100
f7all['ttl_surv._child._m_%'] = (f7all['ttl_surv._child._m'] /f7all['ttl_surv._child._p'])*100
f7all['ttl_surv._child._f_%'] = (f7all['ttl_surv._child._f'] /f7all['ttl_surv._child._p'])*100
f7all['no._of_surv._child._0_%'] = (f7all['no._of_surv._child._0'] /f7all['total_ever_married_women'])*100
f7all['no._of_surv._child._1_%'] = (f7all['no._of_surv._child._1'] /f7all['total_ever_married_women'])*100
f7all['no._of_surv._child._2_%'] = (f7all['no._of_surv._child._2'] /f7all['total_ever_married_women'])*100
f7all['no._of_surv._child._3_%'] = (f7all['no._of_surv._child._3'] /f7all['total_ever_married_women'])*100
f7all['no._of_surv._child._4_%'] = (f7all['no._of_surv._child._4'] /f7all['total_ever_married_women'])*100
f7all['no._of_surv._child._5+_%'] = (f7all['no._of_surv._child._5+'] /f7all['total_ever_married_women'])*100

In [89]:
# Loading the data using Pandas
f8all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_8.xlsx')
f8all.dropna(axis = 0, inplace = True)
f8all.columns = f8all.columns.str.lower()
f8all.columns = f8all.columns.str.strip()
f8all.columns = f8all.columns.str.replace(' |\n', '_')
f8all.columns = f8all.columns.str.replace('__', '_')
f8all['area_name'] = f8all['area_name'].str.replace('\d+', '')
f8all = f8all.applymap(lambda s:s.lower() if type(s) == str else s)
f8all.drop(['table_name'], inplace = True, axis = 1)
f8all['area_name'].astype(object)
f8all['area_name'] = f8all['area_name'].str.strip(' ')
f8all = f8all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f8all['area_name'] = f8all['area_name'].str.rstrip('_')
f8all['total_ever_unmarried_women'] = f8all['total_women'] - f8all['total_ever_married_women']
f8all = f8all.set_axis(['state_code','distt._code','area_name','total/rural/urban', 'economic_activity','present_age', 'total_women','total_ever_married_women', 'no._of_surv._child._0','no._of_surv._child._1', 'no._of_surv._child._2','no._of_surv._child._3', 'no._of_surv._child._4','no._of_surv._child._5+', 'ttl_surv._child._p','ttl_surv._child._m', 'ttl_surv._child._f','total_ever_unmarried_women'], axis=1, inplace=False)
f8all = f8all.drop_duplicates()
f8all = f8all.reset_index(drop=True)
f8all.head()

,state_code,distt._code,area_name,total/rural/urban,economic_activity,present_age,total_women,total_ever_married_women,no._of_surv._child._0,no._of_surv._child._1,no._of_surv._child._2,no._of_surv._child._3,no._of_surv._child._4,no._of_surv._child._5+,ttl_surv._child._p,ttl_surv._child._m,ttl_surv._child._f,total_ever_unmarried_women
0,0,0,india,total,total_main_workers,all_ages,89355595,79738242,12882767,12595396,21661462,15517897,8852228,8228492,185883867,96787081,89096786,9617353
1,0,0,india,total,total_main_workers,less_than_15,1689200,154674,72053,21942,60679,0,0,0,143300,76145,67155,1534526
2,0,0,india,total,total_main_workers,15-19,4981419,1869335,1255706,403208,124343,43124,42954,0,953082,497472,455610,3112084
3,0,0,india,total,total_main_workers,20-24,9686759,7307549,2609853,2320113,1768730,462736,95744,50373,7939300,4101929,3837371,2379210
4,0,0,india,total,total_main_workers,25-29,11764723,10503248,2093610,2234681,3685836,1746883,543933,198305,18168254,9403080,8765174,1261475

In [90]:
f8all['economic_activity'] = f8all['economic_activity'].str.strip()
f8all['economic_activity'] = f8all['economic_activity'].replace({'__(a)_cultivators':'cultivators','__(b)_agricultural_labourers':'agricultural labourers','______(i)_manual':'manual','______(ii)_non-manual':'non-manual','__(c)_other_main_workers':'other workers'})
f8all['economic_activity'].unique()

array(['total_main_workers', 'cultivators', 'agricultural labourers',
       '__(c)_household_industry_workers', '__(d)_other_workers',
       'marginal_workers', 'non-workers'], dtype=object)

In [91]:
f8all = f8all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)

In [92]:
f8all['total_ever_unmarried_women_%'] = (f8all['total_ever_unmarried_women'] /f8all['total_women'])*100
f8all['total_ever_unmarried_women_%'] = (f8all['total_ever_unmarried_women'] /f8all['total_women'])*100
f8all['total_ever_married_women_%'] = (f8all['total_ever_married_women'] /f8all['total_women'])*100
f8all['ttl_surv._child._m_%'] = (f8all['ttl_surv._child._m'] /f8all['ttl_surv._child._p'])*100
f8all['ttl_surv._child._f_%'] = (f8all['ttl_surv._child._f'] /f8all['ttl_surv._child._p'])*100
f8all['no._of_surv._child._0_%'] = (f8all['no._of_surv._child._0'] /f8all['total_ever_married_women'])*100
f8all['no._of_surv._child._1_%'] = (f8all['no._of_surv._child._1'] /f8all['total_ever_married_women'])*100
f8all['no._of_surv._child._2_%'] = (f8all['no._of_surv._child._2'] /f8all['total_ever_married_women'])*100
f8all['no._of_surv._child._3_%'] = (f8all['no._of_surv._child._3'] /f8all['total_ever_married_women'])*100
f8all['no._of_surv._child._4_%'] = (f8all['no._of_surv._child._4'] /f8all['total_ever_married_women'])*100
f8all['no._of_surv._child._5+_%'] = (f8all['no._of_surv._child._5+'] /f8all['total_ever_married_women'])*100

In [93]:
# To familiarize i the values
for column in f8all:
    print(f8all[column].unique())
    print('----------------------------------------------------------------------------------------')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
----------------------------------------------------------------------------------------
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640]
----------------------------------------------------------------------------------------
['india' 'jammu_&_kashmir' 'himachal_pradesh' 'punjab' 'chandigarh'
 'uttarakhand' 'haryana' 'nct_of_delhi' 'rajasthan' 'uttar_pradesh'
 'bihar' 'sikkim' 'arunachal_pradesh' 'nagaland' 'manipur' 'mizoram'
 'tripura' 'meghalaya' 'assam' 'west_bengal' 'jharkhand' 'odisha'
 'chhattisgarh' 'madhya_pradesh' 'gujarat' 'daman_&_diu'
 'dadra_&_nagar_haveli' 'maharashtra' 'andhra_pradesh' 'karnataka' 'goa'
 'lakshadweep' 'kerala' 'tamil_nadu' 'puducherry'
 'andaman_&_nicobar_islands' 'kupwara' 'badgam' 'leh(ladakh)' 'kargil'
 'punch' 'rajouri' 'kathua' 'baramula' 'bandipore' 'srinagar' 'ganderbal'
 'pulwama' 'shupiyan' 'anantnag' 'kulgam' 'doda' 'ramban' 'kishtwar'
 'udhampur' 'reasi' 'jammu' 'samba' 'chamba' 'kangra' 'lahul_&_spiti'
 'kullu' 'mandi' 'hamirpur' 'una' 'bilaspur' 'solan' 'sirmaur' 'shimla'
 'kinnaur' 'gurdaspur' 'kapurthala' 'jalandhar' 'hoshiarpur'
 'shahid_bhagat_singh_nagar' 'fatehgarh_sahib' 'ludhiana' 'moga'
 'firozpur' 'muktsar' 'faridkot' 'bathinda' 'mansa' 'patiala' 'amritsar'
 'tarn_taran' 'rupnagar' 'sahibzada_ajit_singh_nagar' 'sangrur' 'barnala'
 'uttarkashi' 'chamoli' 'rudraprayag' 'tehri_garhwal' 'dehradun' 'garhwal'
 'pithoragarh' 'bageshwar' 'almora\n' 'champawat' 'nainital'
 'udham_singh_nagar' 'hardwar' 'panchkula' 'ambala' 'yamunanagar'
 'kurukshetra' 'kaithal' 'karnal' 'panipat' 'sonipat' 'jind' 'fatehabad'
 'sirsa' 'hisar' 'bhiwani' 'rohtak' 'jhajjar' 'mahendragarh' 'rewari'
 'gurgaon' 'mewat' 'faridabad' 'palwal' 'north_west' 'north' 'north_east'
 'east' 'new_delhi' 'central' 'west' 'south_west' 'south' 'ganganagar'
 'hanumangarh' 'bikaner' 'churu' 'jhunjhunun' 'alwar' 'bharatpur'
 'dhaulpur' 'karauli' 'sawai_madhopur' 'dausa' 'jaipur' 'sikar' 'nagaur'
 'jodhpur' 'jaisalmer' 'barmer' 'jalor' 'sirohi' 'pali' 'ajmer' 'tonk'
 'bundi' 'bhilwara' 'rajsamand' 'dungarpur' 'banswara' 'chittaurgarh'
 'kota' 'baran' 'jhalawar' 'udaipur' 'pratapgarh' 'saharanpur'
 'muzaffarnagar' 'bijnor' 'moradabad' 'rampur' 'jyotiba_phule_nagar'
 'meerut' 'baghpat' 'ghaziabad' 'gautam_buddha_nagar' 'bulandshahr'
 'aligarh' 'mahamaya_nagar' 'mathura' 'agra' 'firozabad' 'mainpuri'
 'budaun' 'bareilly' 'pilibhit' 'shahjahanpur' 'kheri' 'sitapur' 'hardoi'
 'unnao' 'lucknow' 'rae_bareli' 'farrukhabad' 'kannauj' 'etawah' 'auraiya'
 'kanpur_dehat' 'kanpur_nagar' 'jalaun' 'jhansi' 'lalitpur' 'mahoba'
 'banda' 'chitrakoot' 'fatehpur' 'kaushambi' 'allahabad' 'bara_banki'
 'faizabad' 'ambedkar_nagar' 'sultanpur' 'bahraich' 'shrawasti'
 'balrampur' 'gonda' 'siddharthnagar' 'basti' 'sant_kabir_nagar'
 'mahrajganj' 'gorakhpur' 'kushinagar' 'deoria' 'azamgarh' 'mau' 'ballia'
 'jaunpur' 'ghazipur' 'chandauli' 'varanasi'
 'sant_ravidas_nagar_(bhadohi)' 'mirzapur' 'sonbhadra' 'etah'
 'kanshiram_nagar' 'pashchim_champaran' 'purba_champaran' 'sheohar'
 'sitamarhi' 'madhubani' 'supaul' 'araria' 'kishanganj' 'purnia' 'katihar'
 'madhepura' 'saharsa' 'darbhanga' 'muzaffarpur' 'gopalganj' 'siwan'
 'saran' 'vaishali' 'samastipur' 'begusarai' 'khagaria' 'bhagalpur'
 'banka' 'munger' 'lakhisarai' 'sheikhpura' 'nalanda' 'patna' 'bhojpur'
 'buxar' 'kaimur_(bhabua)' 'rohtas' 'aurangabad' 'gaya' 'nawada' 'jamui'
 'jehanabad' 'arwal' 'north__district' 'west_district' 'south_district'
 'east_district' 'tawang' 'west_kameng' 'east_kameng' 'papum_pare'
 'upper_subansiri' 'west_siang' 'east_siang' 'upper_siang' 'changlang'
 'tirap' 'lower_subansiri' 'kurung_kumey' 'dibang_valley'
 'lower_dibang_valley' 'lohit' 'anjaw' 'mon' 'mokokchung' 'zunheboto'
 'wokha' 'dimapur' 'phek' 'tuensang' 'longleng' 'kiphire' 'kohima' 'peren'
 'senapati' 'tamenglong' 'churachandpur' 'bishnupur' 'thoubal'
 'imphal_west' 'imphal_east' 'ukhrul' 'chandel' 'mamit' 'kolasib' 'aizawl'
 'champhai' 'serchhip' 'lunglei' 'lawngtlai' 'saiha' 'west_tripura'
 'south_tripura' 'dhalai' 'north_tripura' 'west_garo_hills'
 'east_garo_hills' 'south_garo_hills' 'west_khasi_hills' 'ribhoi'
 'east_khasi_hills' 'jaintia_hills' 'kokrajhar' 'dhubri' 'goalpara'
 'barpeta' 'morigaon' 'nagaon' 'sonitpur' 'lakhimpur' 'dhemaji' 'tinsukia'
 'dibrugarh' 'sivasagar' 'jorhat' 'golaghat' 'karbi_anglong' 'dima_hasao'
 'cachar' 'karimganj' 'hailakandi' 'bongaigaon' 'chirang' 'kamrup'
 'kamrup_metropolitan' 'nalbari' 'baksa' 'darrang' 'udalguri' 'darjiling'
 'jalpaiguri' 'koch_bihar' 'uttar_dinajpur' 'dakshin_dinajpur' 'maldah'
 'murshidabad' 'birbhum' 'barddhaman' 'nadia' 'north_twenty_four_parganas'
 'hugli' 'bankura' 'puruliya' 'haora' 'kolkata'
 'south_twenty_four_parganas' 'paschim_medinipur' 'purba_medinipur'
 'garhwa' 'chatra' 'kodarma' 'giridih' 'deoghar' 'godda' 'sahibganj'
 'pakur' 'dhanbad' 'bokaro' 'lohardaga' 'purbi_singhbhum' 'palamu'
 'latehar' 'hazaribagh' 'ramgarh' 'dumka' 'jamtara' 'ranchi' 'khunti'
 'gumla' 'simdega' 'pashchimi_singhbhum' 'saraikela-kharsawan' 'bargarh'
 'jharsuguda' 'sambalpur' 'debagarh' 'sundargarh' 'kendujhar' 'mayurbhanj'
 'baleshwar' 'bhadrak' 'kendrapara' 'jagatsinghapur' 'cuttack' 'jajapur'
 'dhenkanal' 'anugul' 'nayagarh' 'khordha' 'puri' 'ganjam' 'gajapati'
 'kandhamal' 'baudh' 'subarnapur' 'balangir' 'nuapada' 'kalahandi'
 'rayagada' 'nabarangapur' 'koraput' 'malkangiri' 'koriya' 'surguja'
 'jashpur' 'raigarh' 'korba' 'janjgir_-_champa' 'kabeerdham' 'rajnandgaon'
 'durg' 'raipur' 'mahasamund' 'dhamtari' 'uttar_bastar_kanker' 'bastar'
 'narayanpur' 'dakshin_bastar_dantewada' 'bijapur' 'sheopur' 'morena'
 'bhind' 'gwalior' 'datia' 'shivpuri' 'tikamgarh' 'chhatarpur' 'panna'
 'sagar' 'damoh' 'satna' 'rewa' 'umaria' 'neemuch' 'mandsaur' 'ratlam'
 'ujjain' 'shajapur' 'dewas' 'dhar' 'indore' 'khargone_(west_nimar)'
 'barwani' 'rajgarh' 'vidisha' 'bhopal' 'sehore' 'raisen' 'betul' 'harda'
 'hoshangabad' 'katni' 'jabalpur' 'narsimhapur' 'dindori' 'mandla'
 'chhindwara' 'seoni' 'balaghat' 'guna' 'ashoknagar' 'shahdol' 'anuppur'
 'sidhi' 'singrauli' 'jhabua' 'alirajpur' 'khandwa_(east_nimar)'
 'burhanpur' 'kachchh' 'banas_kantha' 'patan' 'mahesana' 'sabar_kantha'
 'gandhinagar' 'ahmadabad' 'surendranagar' 'rajkot' 'jamnagar' 'porbandar'
 'junagadh' 'amreli' 'bhavnagar' 'anand' 'kheda' 'panch_mahals' 'dohad'
 'vadodara' 'narmada' 'bharuch' 'the_dangs' 'navsari' 'valsad' 'surat'
 'tapi' 'diu' 'daman' 'nandurbar' 'dhule' 'jalgaon' 'buldana' 'akola'
 'washim' 'amravati' 'wardha' 'nagpur' 'bhandara' 'gondiya' 'gadchiroli'
 'chandrapur' 'yavatmal' 'nanded' 'hingoli' 'parbhani' 'jalna' 'nashik'
 'thane' 'mumbai_suburban' 'mumbai' 'pune' 'ahmadnagar' 'bid' 'latur'
 'osmanabad' 'solapur' 'satara' 'ratnagiri' 'sindhudurg' 'kolhapur'
 'sangli' 'adilabad' 'nizamabad' 'karimnagar' 'medak' 'hyderabad'
 'rangareddy' 'mahbubnagar' 'nalgonda' 'warangal' 'khammam' 'srikakulam'
 'vizianagaram' 'visakhapatnam' 'east_godavari' 'west_godavari' 'krishna'
 'guntur' 'prakasam' 'sri_potti_sriramulu_nellore' 'y.s.r.' 'kurnool'
 'anantapur' 'chittoor' 'belgaum' 'bagalkot' 'bidar' 'raichur' 'koppal'
 'gadag' 'dharwad' 'uttara_kannada' 'haveri' 'bellary' 'chitradurga'
 'davanagere' 'shimoga' 'udupi' 'chikmagalur' 'tumkur' 'bangalore'
 'mandya' 'hassan' 'dakshina_kannada' 'kodagu' 'mysore' 'chamarajanagar'
 'gulbarga' 'yadgir' 'kolar' 'chikkaballapura' 'bangalore_rural'
 'ramanagara' 'north_goa' 'south_goa' 'kasaragod' 'kannur' 'wayanad'
 'kozhikode' 'malappuram' 'palakkad' 'thrissur' 'ernakulam' 'idukki'
 'kottayam' 'alappuzha' 'pathanamthitta' 'kollam' 'thiruvananthapuram'
 'thiruvallur' 'chennai' 'kancheepuram' 'vellore' 'tiruvannamalai'
 'viluppuram' 'salem' 'namakkal' 'erode' 'the_nilgiris' 'dindigul' 'karur'
 'tiruchirappalli' 'perambalur' 'ariyalur' 'cuddalore' 'nagapattinam'
 'thiruvarur' 'thanjavur' 'pudukkottai' 'sivaganga' 'madurai' 'theni'
 'virudhunagar' 'ramanathapuram' 'thoothukkudi' 'tirunelveli'
 'kanniyakumari' 'dharmapuri' 'krishnagiri' 'coimbatore' 'tiruppur'
 'yanam' 'mahe' 'karaikal' 'nicobars' 'north__&_middle_andaman'
 'south_andaman']
----------------------------------------------------------------------------------------
['total' 'rural' 'urban']
----------------------------------------------------------------------------------------
['total_main_workers' 'cultivators' 'agricultural_labourers'
 '__(c)_household_industry_workers' '__(d)_other_workers'
 'marginal_workers' 'non-workers']
----------------------------------------------------------------------------------------
['all_ages' 'less_than_15' '15-19' '20-24' '25-29' '30-34' '35-39' '40-44'
 '45-49' '50-54' '55-59' '60-64' '65-69' '70-74' '75-79' '80+']
----------------------------------------------------------------------------------------
[89355595  1689200  4981419 ...    87251    91591    53966]
----------------------------------------------------------------------------------------
[79738242   154674  1869335 ...    22697    12813    51243]
----------------------------------------------------------------------------------------
[12882767    72053  1255706 ...     7610     9848    30077]
----------------------------------------------------------------------------------------
[12595396    21942   403208 ...    11673     4580     7093]
----------------------------------------------------------------------------------------
[21661462    60679   124343 ...     9557     3990    16130]
----------------------------------------------------------------------------------------
[15517897        0    43124 ...    33495    22805     8873]
----------------------------------------------------------------------------------------
[8852228       0   42954 ...    5440   13865    9538]
----------------------------------------------------------------------------------------
[8228492       0   50373 ...   23062   15885    5304]
----------------------------------------------------------------------------------------
[185883867    143300    953082 ...     14808     14489     58628]
----------------------------------------------------------------------------------------
[96787081    76145   497472 ...    27072    29197    53934]
----------------------------------------------------------------------------------------
[89096786    67155   455610 ...    28100    52079    28898]
----------------------------------------------------------------------------------------
[9617353 1534526 3112084 ...   11128   24015   15664]
----------------------------------------------------------------------------------------
[10.76301154 90.8433578  62.4738453  ...  1.02079395  0.68565401
  2.07641196]
----------------------------------------------------------------------------------------
[89.23698846  9.1566422  37.5261547  ... 98.97920605 99.31434599
 97.92358804]
----------------------------------------------------------------------------------------
[52.06857516 53.13677599 52.19613842 ... 52.63990508 47.89522919
 51.39484979]
----------------------------------------------------------------------------------------
[47.93142484 46.86322401 47.80386158 ... 47.36009492 52.10477081
 48.60515021]
----------------------------------------------------------------------------------------
[16.15632183 46.58378267 67.17394154 ...  4.58365164  6.02205259
  6.69014085]
----------------------------------------------------------------------------------------
[15.79592888 14.18596532 21.5695956  ... 19.83022872 16.61759895
 12.95804567]
----------------------------------------------------------------------------------------
[27.16571303 39.23025201  6.65172374 ... 27.98725438 22.12566845
 21.88295165]
----------------------------------------------------------------------------------------
[19.46104731  0.          2.30691663 ... 26.3368984  17.67123288
 14.23611111]
----------------------------------------------------------------------------------------
[11.10160919  0.          2.29782249 ... 13.13980138 16.14445035
 19.5855615 ]
----------------------------------------------------------------------------------------
[10.31937975  0.          0.68932825 ...  8.97503983 15.04010695
 17.98134012]
----------------------------------------------------------------------------------------

In [94]:
f8all.dropna(axis = 0, inplace = True)
f8all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 219546 entries, 0 to 227135
Data columns (total 28 columns):
state_code                      219546 non-null int64
distt._code                     219546 non-null int64
area_name                       219546 non-null object
total/rural/urban               219546 non-null object
economic_activity               219546 non-null object
present_age                     219546 non-null object
total_women                     219546 non-null int64
total_ever_married_women        219546 non-null int64
no._of_surv._child._0           219546 non-null int64
no._of_surv._child._1           219546 non-null int64
no._of_surv._child._2           219546 non-null int64
no._of_surv._child._3           219546 non-null int64
no._of_surv._child._4           219546 non-null int64
no._of_surv._child._5+          219546 non-null int64
ttl_surv._child._p              219546 non-null int64
ttl_surv._child._m              219546 non-null int64
ttl_surv._child._f              219546 non-null int64
total_ever_unmarried_women      219546 non-null int64
total_ever_unmarried_women_%    219546 non-null float64
total_ever_married_women_%      219546 non-null float64
ttl_surv._child._m_%            219546 non-null float64
ttl_surv._child._f_%            219546 non-null float64
no._of_surv._child._0_%         219546 non-null float64
no._of_surv._child._1_%         219546 non-null float64
no._of_surv._child._2_%         219546 non-null float64
no._of_surv._child._3_%         219546 non-null float64
no._of_surv._child._4_%         219546 non-null float64
no._of_surv._child._5+_%        219546 non-null float64
dtypes: float64(10), int64(14), object(4)
memory usage: 48.6+ MB

In [95]:
# Loading the data using Pandas
f9all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_9.xlsx')
f9all.dropna(axis = 0, inplace = True)
f9all.columns = f9all.columns.str.lower()
f9all.columns = f9all.columns.str.strip()
f9all.columns = f9all.columns.str.replace(' |\n', '_')
f9all.columns = f9all.columns.str.replace('__', '_')
f9all = f9all.applymap(lambda s:s.lower() if type(s) == str else s)
f9all['area_name'] = f9all['area_name'].str.replace('\d+', '')
f9all.drop(['table_name'], inplace = True, axis = 1)
f9all['area_name'].astype(object)
f9all['area_name'] = f9all['area_name'].str.strip(' ')
f9all = f9all.set_axis(['state_code','distt._code', 'area_name', 'total/_rural/_urban', 'present_age','total_women', 'total_currently_married_women','number_of_births_last_year_m', 'number_of_births_last_year_f','last_year’s_births_of_order_1', 'last_year’s_births_of_order_2','last_year’s_births_of_order_3', 'last_year’s_births_of_order_4','last_year’s_births_of_order_5', 'last_year’s_births_of_order_6','last_year’s_births_of_order_7+', 'all/sc/st'], axis=1, inplace=False)
f9all['total_currently_unmarried_women'] = f9all['total_women'] - f9all['total_currently_married_women']
f9all['number_of_births_last_year_p'] = f9all['number_of_births_last_year_m'] +f9all['number_of_births_last_year_f']
f9all = f9all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f9all.replace('50+', '50-54', inplace = True)
f9all = f9all.drop_duplicates()
f9all = f9all.reset_index(drop=True)
f9all.head()

,state_code,distt._code,area_name,total/_rural/_urban,present_age,total_women,total_currently_married_women,number_of_births_last_year_m,number_of_births_last_year_f,last_year’s_births_of_order_1,last_year’s_births_of_order_2,last_year’s_births_of_order_3,last_year’s_births_of_order_4,last_year’s_births_of_order_5,last_year’s_births_of_order_6,last_year’s_births_of_order_7+,all/sc/st,total_currently_unmarried_women,number_of_births_last_year_p
0,0,0,india,total,all_ages,587584719,293077472,11004520,9893708,8200796,6090241,3231929,1642040,795069,427988,510165,all,294507247,20898228
1,0,0,india,total,less_than_15,178092741,1709811,31276,27568,29714,29130,0,0,0,0,0,all,176382930,58844
2,0,0,india,total,15-19,56544053,11011012,663852,622830,1005107,206536,42661,32378,0,0,0,all,45533041,1286682
3,0,0,india,total,20-24,53839529,36881677,3668507,3399390,3853252,2281979,669955,164575,40028,15352,42756,all,16957852,7067897
4,0,0,india,total,25-29,50069757,44606658,3190932,2860511,2004321,2059947,1176262,513355,179536,60197,57825,all,5463099,6051443

In [96]:
f9all.columns

Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'present_age', 'total_women', 'total_currently_married_women',
       'number_of_births_last_year_m', 'number_of_births_last_year_f',
       'last_year’s_births_of_order_1', 'last_year’s_births_of_order_2',
       'last_year’s_births_of_order_3', 'last_year’s_births_of_order_4',
       'last_year’s_births_of_order_5', 'last_year’s_births_of_order_6',
       'last_year’s_births_of_order_7+', 'all/sc/st',
       'total_currently_unmarried_women', 'number_of_births_last_year_p'],
      dtype='object')

In [97]:
f9all['last_year’s_births_of_order_1_%'] = (f9all['last_year’s_births_of_order_1'] /f9all['number_of_births_last_year_p'])*100

In [98]:
f9all['last_year’s_births_of_order_2_%'] = (f9all['last_year’s_births_of_order_2'] /f9all['number_of_births_last_year_p'])*100

In [99]:
f9all['last_year’s_births_of_order_3_%'] = (f9all['last_year’s_births_of_order_3'] /f9all['number_of_births_last_year_p'])*100

In [100]:
f9all['last_year’s_births_of_order_4_%'] = (f9all['last_year’s_births_of_order_4'] /f9all['number_of_births_last_year_p'])*100

In [101]:
f9all['last_year’s_births_of_order_5_%'] = (f9all['last_year’s_births_of_order_5'] /f9all['number_of_births_last_year_p'])*100

In [102]:
f9all['last_year’s_births_of_order_6_%'] = (f9all['last_year’s_births_of_order_6'] /f9all['number_of_births_last_year_p'])*100

In [103]:
f9all['last_year’s_births_of_order_7+_%'] = (f9all['last_year’s_births_of_order_7+'] /f9all['number_of_births_last_year_p'])*100

In [104]:
f9all['number_of_births_last_year_m_%'] = (f9all['number_of_births_last_year_m'] /f9all['number_of_births_last_year_p'])*100

In [105]:
f9all['number_of_births_last_year_f_%'] = (f9all['number_of_births_last_year_f'] /f9all['number_of_births_last_year_p'])*100

In [106]:
f9all['total_currently_unmarried_women_%'] = (f9all['total_currently_unmarried_women'] /f9all['total_women'])*100

In [107]:
f9all['total_currently_married_women_%'] = (f9all['total_currently_married_women'] /f9all['total_women'])*100

In [108]:
f9all.dropna(axis = 0, inplace = True)
f9all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53716 entries, 0 to 59787
Data columns (total 30 columns):
state_code                           53716 non-null int64
distt._code                          53716 non-null int64
area_name                            53716 non-null object
total/_rural/_urban                  53716 non-null object
present_age                          53716 non-null object
total_women                          53716 non-null int64
total_currently_married_women        53716 non-null int64
number_of_births_last_year_m         53716 non-null int64
number_of_births_last_year_f         53716 non-null int64
last_year’s_births_of_order_1        53716 non-null int64
last_year’s_births_of_order_2        53716 non-null int64
last_year’s_births_of_order_3        53716 non-null int64
last_year’s_births_of_order_4        53716 non-null int64
last_year’s_births_of_order_5        53716 non-null int64
last_year’s_births_of_order_6        53716 non-null int64
last_year’s_births_of_order_7+       53716 non-null int64
all/sc/st                            53716 non-null object
total_currently_unmarried_women      53716 non-null int64
number_of_births_last_year_p         53716 non-null int64
last_year’s_births_of_order_1_%      53716 non-null float64
last_year’s_births_of_order_2_%      53716 non-null float64
last_year’s_births_of_order_3_%      53716 non-null float64
last_year’s_births_of_order_4_%      53716 non-null float64
last_year’s_births_of_order_5_%      53716 non-null float64
last_year’s_births_of_order_6_%      53716 non-null float64
last_year’s_births_of_order_7+_%     53716 non-null float64
number_of_births_last_year_m_%       53716 non-null float64
number_of_births_last_year_f_%       53716 non-null float64
total_currently_unmarried_women_%    53716 non-null float64
total_currently_married_women_%      53716 non-null float64
dtypes: float64(11), int64(15), object(4)
memory usage: 12.7+ MB

In [109]:
# To familiarize i the values
for column in f9all:
    print(f9all[column].unique())
    print('----------------------------------------------------------------------------------------')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
----------------------------------------------------------------------------------------
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640]
----------------------------------------------------------------------------------------
['india' 'state_-_jammu_&_kashmir' 'state_-_himachal_pradesh'
 'state_-_punjab' 'union_territory_-_chandigarh' 'state_-_uttarakhand'
 'state_-_haryana' 'state_-_nct_of_delhi' 'state_-_rajasthan'
 'state_-_uttar_pradesh' 'state_-_bihar' 'state_-_sikkim'
 'state_-_arunachal_pradesh' 'state_-_nagaland' 'state_-_manipur'
 'state_-_mizoram' 'state_-_tripura' 'state_-_meghalaya' 'state_-_assam'
 'state_-_west_bengal' 'state_-_jharkhand' 'state_-_odisha'
 'state_-_chhattisgarh' 'state_-_madhya_pradesh' 'state_-_gujarat'
 'union_territory_-_daman_&_diu' 'union_territory_-_dadra_&_nagar_haveli'
 'state_-_maharashtra' 'state_-_andhra_pradesh' 'state_-_karnataka'
 'state_-_goa' 'union_territory_-_lakshadweep' 'state_-_kerala'
 'state_-_tamil_nadu' 'union_territory_-_puducherry'
 'union_territory_-_andaman_&_nicobar_islands' 'district_-_kupwara'
 'district_-_badgam' 'district_-_leh(ladakh)' 'district_-_kargil'
 'district_-_punch' 'district_-_rajouri' 'district_-_kathua'
 'district_-_baramula' 'district_-_bandipore' 'district_-_srinagar'
 'district_-_ganderbal' 'district_-_pulwama' 'district_-_shupiyan'
 'district_-_anantnag' 'district_-_kulgam' 'district_-_doda'
 'district_-_ramban' 'district_-_kishtwar' 'district_-_udhampur'
 'district_-_reasi' 'district_-_jammu' 'district_-_samba'
 'district_-_chamba' 'district_-_kangra' 'district_-_lahul_&_spiti'
 'district_-_kullu' 'district_-_mandi' 'district_-_hamirpur'
 'district_-_una' 'district_-_bilaspur' 'district_-_solan'
 'district_-_sirmaur' 'district_-_shimla' 'district_-_kinnaur'
 'district_-_gurdaspur' 'district_-_kapurthala' 'district_-_jalandhar'
 'district_-_hoshiarpur' 'district_-_shahid_bhagat_singh_nagar'
 'district_-_fatehgarh_sahib' 'district_-_ludhiana' 'district_-_moga'
 'district_-_firozpur' 'district_-_muktsar' 'district_-_faridkot'
 'district_-_bathinda' 'district_-_mansa' 'district_-_patiala'
 'district_-_amritsar' 'district_-_tarn_taran' 'district_-_rupnagar'
 'district_-_sahibzada_ajit_singh_nagar' 'district_-_sangrur'
 'district_-_barnala' 'district_-_chandigarh' 'district_-_uttarkashi'
 'district_-_chamoli' 'district_-_rudraprayag' 'district_-_tehri_garhwal'
 'district_-_dehradun' 'district_-_garhwal' 'district_-_pithoragarh'
 'district_-_bageshwar' 'district_-_almora\n' 'district_-_champawat'
 'district_-_nainital' 'district_-_udham_singh_nagar' 'district_-_hardwar'
 'district_-_panchkula' 'district_-_ambala' 'district_-_yamunanagar'
 'district_-_kurukshetra' 'district_-_kaithal' 'district_-_karnal'
 'district_-_panipat' 'district_-_sonipat' 'district_-_jind'
 'district_-_fatehabad' 'district_-_sirsa' 'district_-_hisar'
 'district_-_bhiwani' 'district_-_rohtak' 'district_-_jhajjar'
 'district_-_mahendragarh' 'district_-_rewari' 'district_-_gurgaon'
 'district_-_mewat' 'district_-_faridabad' 'district_-_palwal'
 'district_-_north_west' 'district_-_north' 'district_-_north_east'
 'district_-_east' 'district_-_new_delhi' 'district_-_central'
 'district_-_west' 'district_-_south_west' 'district_-_south'
 'district_-_ganganagar' 'district_-_hanumangarh' 'district_-_bikaner'
 'district_-_churu' 'district_-_jhunjhunun' 'district_-_alwar'
 'district_-_bharatpur' 'district_-_dhaulpur' 'district_-_karauli'
 'district_-_sawai_madhopur' 'district_-_dausa' 'district_-_jaipur'
 'district_-_sikar' 'district_-_nagaur' 'district_-_jodhpur'
 'district_-_jaisalmer' 'district_-_barmer' 'district_-_jalor'
 'district_-_sirohi' 'district_-_pali' 'district_-_ajmer'
 'district_-_tonk' 'district_-_bundi' 'district_-_bhilwara'
 'district_-_rajsamand' 'district_-_dungarpur' 'district_-_banswara'
 'district_-_chittaurgarh' 'district_-_kota' 'district_-_baran'
 'district_-_jhalawar' 'district_-_udaipur' 'district_-_pratapgarh'
 'district_-_saharanpur' 'district_-_muzaffarnagar' 'district_-_bijnor'
 'district_-_moradabad' 'district_-_rampur'
 'district_-_jyotiba_phule_nagar' 'district_-_meerut' 'district_-_baghpat'
 'district_-_ghaziabad' 'district_-_gautam_buddha_nagar'
 'district_-_bulandshahr' 'district_-_aligarh' 'district_-_mahamaya_nagar'
 'district_-_mathura' 'district_-_agra' 'district_-_firozabad'
 'district_-_mainpuri' 'district_-_budaun' 'district_-_bareilly'
 'district_-_pilibhit' 'district_-_shahjahanpur' 'district_-_kheri'
 'district_-_sitapur' 'district_-_hardoi' 'district_-_unnao'
 'district_-_lucknow' 'district_-_rae_bareli' 'district_-_farrukhabad'
 'district_-_kannauj' 'district_-_etawah' 'district_-_auraiya'
 'district_-_kanpur_dehat' 'district_-_kanpur_nagar' 'district_-_jalaun'
 'district_-_jhansi' 'district_-_lalitpur' 'district_-_mahoba'
 'district_-_banda' 'district_-_chitrakoot' 'district_-_fatehpur'
 'district_-_kaushambi' 'district_-_allahabad' 'district_-_bara_banki'
 'district_-_faizabad' 'district_-_ambedkar_nagar' 'district_-_sultanpur'
 'district_-_bahraich' 'district_-_shrawasti' 'district_-_balrampur'
 'district_-_gonda' 'district_-_siddharthnagar' 'district_-_basti'
 'district_-_sant_kabir_nagar' 'district_-_mahrajganj'
 'district_-_gorakhpur' 'district_-_kushinagar' 'district_-_deoria'
 'district_-_azamgarh' 'district_-_mau' 'district_-_ballia'
 'district_-_jaunpur' 'district_-_ghazipur' 'district_-_chandauli'
 'district_-_varanasi' 'district_-_sant_ravidas_nagar_(bhadohi)'
 'district_-_mirzapur' 'district_-_sonbhadra' 'district_-_etah'
 'district_-_kanshiram_nagar' 'district_-_pashchim_champaran'
 'district_-_purba_champaran' 'district_-_sheohar' 'district_-_sitamarhi'
 'district_-_madhubani' 'district_-_supaul' 'district_-_araria'
 'district_-_kishanganj' 'district_-_purnia' 'district_-_katihar'
 'district_-_madhepura' 'district_-_saharsa' 'district_-_darbhanga'
 'district_-_muzaffarpur' 'district_-_gopalganj' 'district_-_siwan'
 'district_-_saran' 'district_-_vaishali' 'district_-_samastipur'
 'district_-_begusarai' 'district_-_khagaria' 'district_-_bhagalpur'
 'district_-_banka' 'district_-_munger' 'district_-_lakhisarai'
 'district_-_sheikhpura' 'district_-_nalanda' 'district_-_patna'
 'district_-_bhojpur' 'district_-_buxar' 'district_-_kaimur_(bhabua)'
 'district_-_rohtas' 'district_-_aurangabad' 'district_-_gaya'
 'district_-_nawada' 'district_-_jamui' 'district_-_jehanabad'
 'district_-_arwal' 'district_-_north__district'
 'district_-_west_district' 'district_-_south_district'
 'district_-_east_district' 'district_-_tawang' 'district_-_west_kameng'
 'district_-_east_kameng' 'district_-_papum_pare'
 'district_-_upper_subansiri' 'district_-_west_siang'
 'district_-_east_siang' 'district_-_upper_siang' 'district_-_changlang'
 'district_-_tirap' 'district_-_lower_subansiri' 'district_-_kurung_kumey'
 'district_-_dibang_valley' 'district_-_lower_dibang_valley'
 'district_-_lohit' 'district_-_anjaw' 'district_-_mon'
 'district_-_mokokchung' 'district_-_zunheboto' 'district_-_wokha'
 'district_-_dimapur' 'district_-_phek' 'district_-_tuensang'
 'district_-_longleng' 'district_-_kiphire' 'district_-_kohima'
 'district_-_peren' 'district_-_senapati' 'district_-_tamenglong'
 'district_-_churachandpur' 'district_-_bishnupur' 'district_-_thoubal'
 'district_-_imphal_west' 'district_-_imphal_east' 'district_-_ukhrul'
 'district_-_chandel' 'district_-_mamit' 'district_-_kolasib'
 'district_-_aizawl' 'district_-_champhai' 'district_-_serchhip'
 'district_-_lunglei' 'district_-_lawngtlai' 'district_-_saiha'
 'district_-_west_tripura' 'district_-_south_tripura' 'district_-_dhalai'
 'district_-_north_tripura' 'district_-_west_garo_hills'
 'district_-_east_garo_hills' 'district_-_south_garo_hills'
 'district_-_west_khasi_hills' 'district_-_ribhoi'
 'district_-_east_khasi_hills' 'district_-_jaintia_hills'
 'district_-_kokrajhar' 'district_-_dhubri' 'district_-_goalpara'
 'district_-_barpeta' 'district_-_morigaon' 'district_-_nagaon'
 'district_-_sonitpur' 'district_-_lakhimpur' 'district_-_dhemaji'
 'district_-_tinsukia' 'district_-_dibrugarh' 'district_-_sivasagar'
 'district_-_jorhat' 'district_-_golaghat' 'district_-_karbi_anglong'
 'district_-_dima_hasao' 'district_-_cachar' 'district_-_karimganj'
 'district_-_hailakandi' 'district_-_bongaigaon' 'district_-_chirang'
 'district_-_kamrup' 'district_-_kamrup_metropolitan' 'district_-_nalbari'
 'district_-_baksa' 'district_-_darrang' 'district_-_udalguri'
 'district_-_darjiling' 'district_-_jalpaiguri' 'district_-_koch_bihar'
 'district_-_uttar_dinajpur' 'district_-_dakshin_dinajpur'
 'district_-_maldah' 'district_-_murshidabad' 'district_-_birbhum'
 'district_-_barddhaman' 'district_-_nadia'
 'district_-_north_twenty_four_parganas' 'district_-_hugli'
 'district_-_bankura' 'district_-_puruliya' 'district_-_haora'
 'district_-_kolkata' 'district_-_south_twenty_four_parganas'
 'district_-_paschim_medinipur' 'district_-_purba_medinipur'
 'district_-_garhwa' 'district_-_chatra' 'district_-_kodarma'
 'district_-_giridih' 'district_-_deoghar' 'district_-_godda'
 'district_-_sahibganj' 'district_-_pakur' 'district_-_dhanbad'
 'district_-_bokaro' 'district_-_lohardaga' 'district_-_purbi_singhbhum'
 'district_-_palamu' 'district_-_latehar' 'district_-_hazaribagh'
 'district_-_ramgarh' 'district_-_dumka' 'district_-_jamtara'
 'district_-_ranchi' 'district_-_khunti' 'district_-_gumla'
 'district_-_simdega' 'district_-_pashchimi_singhbhum'
 'district_-_saraikela-kharsawan' 'district_-_bargarh'
 'district_-_jharsuguda' 'district_-_sambalpur' 'district_-_debagarh'
 'district_-_sundargarh' 'district_-_kendujhar' 'district_-_mayurbhanj'
 'district_-_baleshwar' 'district_-_bhadrak' 'district_-_kendrapara'
 'district_-_jagatsinghapur' 'district_-_cuttack' 'district_-_jajapur'
 'district_-_dhenkanal' 'district_-_anugul' 'district_-_nayagarh'
 'district_-_khordha' 'district_-_puri' 'district_-_ganjam'
 'district_-_gajapati' 'district_-_kandhamal' 'district_-_baudh'
 'district_-_subarnapur' 'district_-_balangir' 'district_-_nuapada'
 'district_-_kalahandi' 'district_-_rayagada' 'district_-_nabarangapur'
 'district_-_koraput' 'district_-_malkangiri' 'district_-_koriya'
 'district_-_surguja' 'district_-_jashpur' 'district_-_raigarh'
 'district_-_korba' 'district_-_janjgir_-_champa' 'district_-_kabeerdham'
 'district_-_rajnandgaon' 'district_-_durg' 'district_-_raipur'
 'district_-_mahasamund' 'district_-_dhamtari'
 'district_-_uttar_bastar_kanker' 'district_-_bastar'
 'district_-_narayanpur' 'district_-_dakshin_bastar_dantewada'
 'district_-_bijapur' 'district_-_sheopur' 'district_-_morena'
 'district_-_bhind' 'district_-_gwalior' 'district_-_datia'
 'district_-_shivpuri' 'district_-_tikamgarh' 'district_-_chhatarpur'
 'district_-_panna' 'district_-_sagar' 'district_-_damoh'
 'district_-_satna' 'district_-_rewa' 'district_-_umaria'
 'district_-_neemuch' 'district_-_mandsaur' 'district_-_ratlam'
 'district_-_ujjain' 'district_-_shajapur' 'district_-_dewas'
 'district_-_dhar' 'district_-_indore' 'district_-_khargone_(west_nimar)'
 'district_-_barwani' 'district_-_rajgarh' 'district_-_vidisha'
 'district_-_bhopal' 'district_-_sehore' 'district_-_raisen'
 'district_-_betul' 'district_-_harda' 'district_-_hoshangabad'
 'district_-_katni' 'district_-_jabalpur' 'district_-_narsimhapur'
 'district_-_dindori' 'district_-_mandla' 'district_-_chhindwara'
 'district_-_seoni' 'district_-_balaghat' 'district_-_guna'
 'district_-_ashoknagar' 'district_-_shahdol' 'district_-_anuppur'
 'district_-_sidhi' 'district_-_singrauli' 'district_-_jhabua'
 'district_-_alirajpur' 'district_-_khandwa_(east_nimar)'
 'district_-_burhanpur' 'district_-_kachchh' 'district_-_banas_kantha'
 'district_-_patan' 'district_-_mahesana' 'district_-_sabar_kantha'
 'district_-_gandhinagar' 'district_-_ahmadabad'
 'district_-_surendranagar' 'district_-_rajkot' 'district_-_jamnagar'
 'district_-_porbandar' 'district_-_junagadh' 'district_-_amreli'
 'district_-_bhavnagar' 'district_-_anand' 'district_-_kheda'
 'district_-_panch_mahals' 'district_-_dohad' 'district_-_vadodara'
 'district_-_narmada' 'district_-_bharuch' 'district_-_the_dangs'
 'district_-_navsari' 'district_-_valsad' 'district_-_surat'
 'district_-_tapi' 'district_-_diu' 'district_-_daman'
 'district_-_dadra_&_nagar_haveli' 'district_-_nandurbar'
 'district_-_dhule' 'district_-_jalgaon' 'district_-_buldana'
 'district_-_akola' 'district_-_washim' 'district_-_amravati'
 'district_-_wardha' 'district_-_nagpur' 'district_-_bhandara'
 'district_-_gondiya' 'district_-_gadchiroli' 'district_-_chandrapur'
 'district_-_yavatmal' 'district_-_nanded' 'district_-_hingoli'
 'district_-_parbhani' 'district_-_jalna' 'district_-_nashik'
 'district_-_thane' 'district_-_mumbai_suburban' 'district_-_mumbai'
 'district_-_pune' 'district_-_ahmadnagar' 'district_-_bid'
 'district_-_latur' 'district_-_osmanabad' 'district_-_solapur'
 'district_-_satara' 'district_-_ratnagiri' 'district_-_sindhudurg'
 'district_-_kolhapur' 'district_-_sangli' 'district_-_adilabad'
 'district_-_nizamabad' 'district_-_karimnagar' 'district_-_medak'
 'district_-_hyderabad' 'district_-_rangareddy' 'district_-_mahbubnagar'
 'district_-_nalgonda' 'district_-_warangal' 'district_-_khammam'
 'district_-_srikakulam' 'district_-_vizianagaram'
 'district_-_visakhapatnam' 'district_-_east_godavari'
 'district_-_west_godavari' 'district_-_krishna' 'district_-_guntur'
 'district_-_prakasam' 'district_-_sri_potti_sriramulu_nellore'
 'district_-_y.s.r.' 'district_-_kurnool' 'district_-_anantapur'
 'district_-_chittoor' 'district_-_belgaum' 'district_-_bagalkot'
 'district_-_bidar' 'district_-_raichur' 'district_-_koppal'
 'district_-_gadag' 'district_-_dharwad' 'district_-_uttara_kannada'
 'district_-_haveri' 'district_-_bellary' 'district_-_chitradurga'
 'district_-_davanagere' 'district_-_shimoga' 'district_-_udupi'
 'district_-_chikmagalur' 'district_-_tumkur' 'district_-_bangalore'
 'district_-_mandya' 'district_-_hassan' 'district_-_dakshina_kannada'
 'district_-_kodagu' 'district_-_mysore' 'district_-_chamarajanagar'
 'district_-_gulbarga' 'district_-_yadgir' 'district_-_kolar'
 'district_-_chikkaballapura' 'district_-_bangalore_rural'
 'district_-_ramanagara' 'district_-_north_goa' 'district_-_south_goa'
 'district_-_lakshadweep' 'district_-_kasaragod' 'district_-_kannur'
 'district_-_wayanad' 'district_-_kozhikode' 'district_-_malappuram'
 'district_-_palakkad' 'district_-_thrissur' 'district_-_ernakulam'
 'district_-_idukki' 'district_-_kottayam' 'district_-_alappuzha'
 'district_-_pathanamthitta' 'district_-_kollam'
 'district_-_thiruvananthapuram' 'district_-_thiruvallur'
 'district_-_chennai' 'district_-_kancheepuram' 'district_-_vellore'
 'district_-_tiruvannamalai' 'district_-_viluppuram' 'district_-_salem'
 'district_-_namakkal' 'district_-_erode' 'district_-_the_nilgiris'
 'district_-_dindigul' 'district_-_karur' 'district_-_tiruchirappalli'
 'district_-_perambalur' 'district_-_ariyalur' 'district_-_cuddalore'
 'district_-_nagapattinam' 'district_-_thiruvarur' 'district_-_thanjavur'
 'district_-_pudukkottai' 'district_-_sivaganga' 'district_-_madurai'
 'district_-_theni' 'district_-_virudhunagar' 'district_-_ramanathapuram'
 'district_-_thoothukkudi' 'district_-_tirunelveli'
 'district_-_kanniyakumari' 'district_-_dharmapuri'
 'district_-_krishnagiri' 'district_-_coimbatore' 'district_-_tiruppur'
 'district_-_yanam' 'district_-_puducherry' 'district_-_mahe'
 'district_-_karaikal' 'district_-_nicobars'
 'district_-_north__&_middle_andaman' 'district_-_south_andaman']
----------------------------------------------------------------------------------------
['total' 'rural' 'urban']
----------------------------------------------------------------------------------------
['all_ages' 'less_than_15' '15-19' '20-24' '25-29' '30-34' '35-39' '40-44'
 '45-49' '50-54']
----------------------------------------------------------------------------------------
[587584719 178092741  56544053 ...     13799      1274     12878]
----------------------------------------------------------------------------------------
[293077472   1709811  11011012 ...      5437      3484      5449]
----------------------------------------------------------------------------------------
[11004520    31276   663852 ...     4851     2135     1193]
----------------------------------------------------------------------------------------
[9893708   27568  622830 ...    2858    2098    1785]
----------------------------------------------------------------------------------------
[8200796   29714 1005107 ...    2012    1446    2943]
----------------------------------------------------------------------------------------
[6090241   29130  206536 ...    2618    1809    3975]
----------------------------------------------------------------------------------------
[3231929       0   42661 ...    4398    2025    2378]
----------------------------------------------------------------------------------------
[1642040       0   32378 ...     984    5969    5125]
----------------------------------------------------------------------------------------
[795069      0  40028 ...   2591   2417   2125]
----------------------------------------------------------------------------------------
[427988      0  15352 ...    689    741   1184]

In [110]:
# Loading the data using Pandas
f10all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_10.xlsx')
f10all.dropna(axis = 0, inplace = True)
f10all.columns = f10all.columns.str.lower()
f10all.columns = f10all.columns.str.strip()
f10all.columns = f10all.columns.str.replace(' |\n', '_')
f10all.columns = f10all.columns.str.replace('__', '_')
f10all = f10all.applymap(lambda s:s.lower() if type(s) == str else s)
f10all['area_name'] = f10all['area_name'].str.replace('\d+', '')
f10all.drop(['table_name'], inplace = True, axis = 1)
f10all['area_name'].astype(object)
f10all['area_name'] = f10all['area_name'].str.strip(' ')
f10all = f10all.set_axis(['state_code', 'distt._code','area_name', 'total/_rural/_urban', 'religious_community','present_age', 'total_women', 'total_currently_married_women','number_of_births_last_year_m', 'number_of_births_last_year_f','last_year’s_births_of_order_1', 'last_year’s_births_of_order_2','last_year’s_births_of_order_3', 'last_year’s_births_of_order_4','last_year’s_births_of_order_5', 'last_year’s_births_of_order_6','last_year’s_births_of_order_7+'], axis=1, inplace=False)
f10all['total_currently_unmarried_women'] = f10all['total_women'] - f10all['total_currently_married_women']
f10all['number_of_births_last_year_p'] = f10all['number_of_births_last_year_m']+f10all['number_of_births_last_year_f']
f10all = f10all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f10all.replace('50+', '50-54', inplace = True)
f10all = f10all.drop_duplicates()
f10all = f10all.reset_index(drop=True)
f10all.head()

,state_code,distt._code,area_name,total/_rural/_urban,religious_community,present_age,total_women,total_currently_married_women,number_of_births_last_year_m,number_of_births_last_year_f,last_year’s_births_of_order_1,last_year’s_births_of_order_2,last_year’s_births_of_order_3,last_year’s_births_of_order_4,last_year’s_births_of_order_5,last_year’s_births_of_order_6,last_year’s_births_of_order_7+,total_currently_unmarried_women,number_of_births_last_year_p
0,0,0,india,total,all_religious_communities,all_ages,587584719,293077472,11004520,9893708,8200796,6090241,3231929,1642040,795069,427988,510165,294507247,20898228
1,0,0,india,total,all_religious_communities,less_than_15,178092741,1709811,31276,27568,29714,29130,0,0,0,0,0,176382930,58844
2,0,0,india,total,all_religious_communities,15-19,56544053,11011012,663852,622830,1005107,206536,42661,32378,0,0,0,45533041,1286682
3,0,0,india,total,all_religious_communities,20-24,53839529,36881677,3668507,3399390,3853252,2281979,669955,164575,40028,15352,42756,16957852,7067897
4,0,0,india,total,all_religious_communities,25-29,50069757,44606658,3190932,2860511,2004321,2059947,1176262,513355,179536,60197,57825,5463099,6051443

In [111]:
f10all.columns

Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'religious_community', 'present_age', 'total_women',
       'total_currently_married_women', 'number_of_births_last_year_m',
       'number_of_births_last_year_f', 'last_year’s_births_of_order_1',
       'last_year’s_births_of_order_2', 'last_year’s_births_of_order_3',
       'last_year’s_births_of_order_4', 'last_year’s_births_of_order_5',
       'last_year’s_births_of_order_6', 'last_year’s_births_of_order_7+',
       'total_currently_unmarried_women', 'number_of_births_last_year_p'],
      dtype='object')

In [112]:
f10all['last_year’s_births_of_order_1_%'] = (f10all['last_year’s_births_of_order_1'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_1_%'] = (f10all['last_year’s_births_of_order_1'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_2_%'] = (f10all['last_year’s_births_of_order_2'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_3_%'] = (f10all['last_year’s_births_of_order_3'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_4_%'] = (f10all['last_year’s_births_of_order_4'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_5_%'] = (f10all['last_year’s_births_of_order_5'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_6_%'] = (f10all['last_year’s_births_of_order_6'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_7+_%'] = (f10all['last_year’s_births_of_order_7+'] /f10all['number_of_births_last_year_p'])*100
f10all['last_year’s_births_of_order_7+_%'] = (f10all['last_year’s_births_of_order_7+'] /f10all['number_of_births_last_year_p'])*100
f10all['number_of_births_last_year_m_%'] = (f10all['number_of_births_last_year_m'] /f10all['number_of_births_last_year_p'])*100
f10all['number_of_births_last_year_m_%'] = (f10all['number_of_births_last_year_m'] /f10all['number_of_births_last_year_p'])*100
f10all['number_of_births_last_year_f_%'] = (f10all['number_of_births_last_year_f'] /f10all['number_of_births_last_year_p'])*100
f10all['number_of_births_last_year_f_%'] = (f10all['number_of_births_last_year_f'] /f10all['number_of_births_last_year_p'])*100
f10all['total_currently_unmarried_women_%'] = (f10all['total_currently_unmarried_women'] /f10all['total_women'])*100
f10all['total_currently_married_women_%'] = (f10all['total_currently_married_women'] /f10all['total_women'])*100

In [113]:
f10all.dropna(axis = 0, inplace = True)
f10all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112831 entries, 0 to 170634
Data columns (total 30 columns):
state_code                           112831 non-null int64
distt._code                          112831 non-null int64
area_name                            112831 non-null object
total/_rural/_urban                  112831 non-null object
religious_community                  112831 non-null object
present_age                          112831 non-null object
total_women                          112831 non-null int64
total_currently_married_women        112831 non-null int64
number_of_births_last_year_m         112831 non-null int64
number_of_births_last_year_f         112831 non-null int64
last_year’s_births_of_order_1        112831 non-null int64
last_year’s_births_of_order_2        112831 non-null int64
last_year’s_births_of_order_3        112831 non-null int64
last_year’s_births_of_order_4        112831 non-null int64
last_year’s_births_of_order_5        112831 non-null int64
last_year’s_births_of_order_6        112831 non-null int64
last_year’s_births_of_order_7+       112831 non-null int64
total_currently_unmarried_women      112831 non-null int64
number_of_births_last_year_p         112831 non-null int64
last_year’s_births_of_order_1_%      112831 non-null float64
last_year’s_births_of_order_2_%      112831 non-null float64
last_year’s_births_of_order_3_%      112831 non-null float64
last_year’s_births_of_order_4_%      112831 non-null float64
last_year’s_births_of_order_5_%      112831 non-null float64
last_year’s_births_of_order_6_%      112831 non-null float64
last_year’s_births_of_order_7+_%     112831 non-null float64
number_of_births_last_year_m_%       112831 non-null float64
number_of_births_last_year_f_%       112831 non-null float64
total_currently_unmarried_women_%    112831 non-null float64
total_currently_married_women_%      112831 non-null float64
dtypes: float64(11), int64(15), object(4)
memory usage: 26.7+ MB

In [114]:
# To familiarize i the values
for column in f10all:
    print(f10all[column].unique())
    print('----------------------------------------------------------------------------------------')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
----------------------------------------------------------------------------------------
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640]
----------------------------------------------------------------------------------------
['india' 'state_-_jammu_&_kashmir' 'state_-_himachal_pradesh'
 'state_-_punjab' 'union_territory_-_chandigarh' 'state_-_uttarakhand'
 'state_-_haryana' 'state_-_nct_of_delhi' 'state_-_rajasthan'
 'state_-_uttar_pradesh' 'state_-_bihar' 'state_-_sikkim'
 'state_-_arunachal_pradesh' 'state_-_nagaland' 'state_-_manipur'
 'state_-_mizoram' 'state_-_tripura' 'state_-_meghalaya' 'state_-_assam'
 'state_-_west_bengal' 'state_-_jharkhand' 'state_-_odisha'
 'state_-_chhattisgarh' 'state_-_madhya_pradesh' 'state_-_gujarat'
 'union_territory_-_daman_&_diu' 'union_territory_-_dadra_&_nagar_haveli'
 'state_-_maharashtra' 'state_-_andhra_pradesh' 'state_-_karnataka'
 'state_-_goa' 'union_territory_-_lakshadweep' 'state_-_kerala'
 'state_-_tamil_nadu' 'union_territory_-_puducherry'
 'union_territory_-_andaman_&_nicobar_islands' 'state_-__jammu_&_kashmir'
 'district_-_kupwara' 'district_-_badgam' 'district_-_leh(ladakh)'
 'district_-_kargil' 'district_-_punch' 'district_-_rajouri'
 'district_-_kathua' 'district_-_baramula' 'district_-_bandipore'
 'district_-_srinagar' 'district_-_ganderbal' 'district_-_pulwama'
 'district_-_shupiyan' 'district_-_anantnag' 'district_-_kulgam'
 'district_-_doda' 'district_-_ramban' 'district_-_kishtwar'
 'district_-_udhampur' 'district_-_reasi' 'district_-_jammu'
 'district_-_samba' 'state_-__himachal_pradesh' 'district_-_chamba'
 'district_-_kangra' 'district_-_lahul_&_spiti' 'district_-_kullu'
 'district_-_mandi' 'district_-_hamirpur' 'district_-_una'
 'district_-_bilaspur' 'district_-_solan' 'district_-_sirmaur'
 'district_-_shimla' 'district_-_kinnaur' 'state_-__punjab'
 'district_-_gurdaspur' 'district_-_kapurthala' 'district_-_jalandhar'
 'district_-_hoshiarpur' 'district_-_shahid_bhagat_singh_nagar'
 'district_-_fatehgarh_sahib' 'district_-_ludhiana' 'district_-_moga'
 'district_-_firozpur' 'district_-_muktsar' 'district_-_faridkot'
 'district_-_bathinda' 'district_-_mansa' 'district_-_patiala'
 'district_-_amritsar' 'district_-_tarn_taran' 'district_-_rupnagar'
 'district_-_sahibzada_ajit_singh_nagar' 'district_-_sangrur'
 'district_-_barnala' 'union_territory_-__chandigarh'
 'district_-_chandigarh' 'state_-__uttarakhand' 'district_-_uttarkashi'
 'district_-_chamoli' 'district_-_rudraprayag' 'district_-_tehri_garhwal'
 'district_-_dehradun' 'district_-_garhwal' 'district_-_pithoragarh'
 'district_-_bageshwar' 'district_-_almora' 'district_-_champawat'
 'district_-_nainital' 'district_-_udham_singh_nagar' 'district_-_hardwar'
 'state_-__haryana' 'district_-_panchkula' 'district_-_ambala'
 'district_-_yamunanagar' 'district_-_kurukshetra' 'district_-_kaithal'
 'district_-_karnal' 'district_-_panipat' 'district_-_sonipat'
 'district_-_jind' 'district_-_fatehabad' 'district_-_sirsa'
 'district_-_hisar' 'district_-_bhiwani' 'district_-_rohtak'
 'district_-_jhajjar' 'district_-_mahendragarh' 'district_-_rewari'
 'district_-_gurgaon' 'district_-_mewat' 'district_-_faridabad'
 'district_-_palwal' 'state_-__nct_of_delhi' 'district_-_north_west'
 'district_-_north' 'district_-_north_east' 'district_-_east'
 'district_-_new_delhi' 'district_-_central' 'district_-_west'
 'district_-_south_west' 'district_-_south' 'state_-__rajasthan'
 'district_-_ganganagar' 'district_-_hanumangarh' 'district_-_bikaner'
 'district_-_churu' 'district_-_jhunjhunun' 'district_-_alwar'
 'district_-_bharatpur' 'district_-_dhaulpur' 'district_-_karauli'
 'district_-_sawai_madhopur' 'district_-_dausa' 'district_-_jaipur'
 'district_-_sikar' 'district_-_nagaur' 'district_-_jodhpur'
 'district_-_jaisalmer' 'district_-_barmer' 'district_-_jalor'
 'district_-_sirohi' 'district_-_pali' 'district_-_ajmer'
 'district_-_tonk' 'district_-_bundi' 'district_-_bhilwara'
 'district_-_rajsamand' 'district_-_dungarpur' 'district_-_banswara'
 'district_-_chittaurgarh' 'district_-_kota' 'district_-_baran'
 'district_-_jhalawar' 'district_-_udaipur' 'district_-_pratapgarh'
 'state_-__uttar_pradesh' 'district_-_saharanpur'
 'district_-_muzaffarnagar' 'district_-_bijnor' 'district_-_moradabad'
 'district_-_rampur' 'district_-_jyotiba_phule_nagar' 'district_-_meerut'
 'district_-_baghpat' 'district_-_ghaziabad'
 'district_-_gautam_buddha_nagar' 'district_-_bulandshahr'
 'district_-_aligarh' 'district_-_mahamaya_nagar' 'district_-_mathura'
 'district_-_agra' 'district_-_firozabad' 'district_-_mainpuri'
 'district_-_budaun' 'district_-_bareilly' 'district_-_pilibhit'
 'district_-_shahjahanpur' 'district_-_kheri' 'district_-_sitapur'
 'district_-_hardoi' 'district_-_unnao' 'district_-_lucknow'
 'district_-_rae_bareli' 'district_-_farrukhabad' 'district_-_kannauj'
 'district_-_etawah' 'district_-_auraiya' 'district_-_kanpur_dehat'
 'district_-_kanpur_nagar' 'district_-_jalaun' 'district_-_jhansi'
 'district_-_lalitpur' 'district_-_mahoba' 'district_-_banda'
 'district_-_chitrakoot' 'district_-_fatehpur' 'district_-_kaushambi'
 'district_-_allahabad' 'district_-_bara_banki' 'district_-_faizabad'
 'district_-_ambedkar_nagar' 'district_-_sultanpur' 'district_-_bahraich'
 'district_-_shrawasti' 'district_-_balrampur' 'district_-_gonda'
 'district_-_siddharthnagar' 'district_-_basti'
 'district_-_sant_kabir_nagar' 'district_-_mahrajganj'
 'district_-_gorakhpur' 'district_-_kushinagar' 'district_-_deoria'
 'district_-_azamgarh' 'district_-_mau' 'district_-_ballia'
 'district_-_jaunpur' 'district_-_ghazipur' 'district_-_chandauli'
 'district_-_varanasi' 'district_-_sant_ravidas_nagar_(bhadohi)'
 'district_-_mirzapur' 'district_-_sonbhadra' 'district_-_etah'
 'district_-_kanshiram_nagar' 'state_-__bihar'
 'district_-_pashchim_champaran' 'district_-_purba_champaran'
 'district_-_sheohar' 'district_-_sitamarhi' 'district_-_madhubani'
 'district_-_supaul' 'district_-_araria' 'district_-_kishanganj'
 'district_-_purnia' 'district_-_katihar' 'district_-_madhepura'
 'district_-_saharsa' 'district_-_darbhanga' 'district_-_muzaffarpur'
 'district_-_gopalganj' 'district_-_siwan' 'district_-_saran'
 'district_-_vaishali' 'district_-_samastipur' 'district_-_begusarai'
 'district_-_khagaria' 'district_-_bhagalpur' 'district_-_banka'
 'district_-_munger' 'district_-_lakhisarai' 'district_-_sheikhpura'
 'district_-_nalanda' 'district_-_patna' 'district_-_bhojpur'
 'district_-_buxar' 'district_-_kaimur_(bhabua)' 'district_-_rohtas'
 'district_-_aurangabad' 'district_-_gaya' 'district_-_nawada'
 'district_-_jamui' 'district_-_jehanabad' 'district_-_arwal'
 'state_-__sikkim' 'district_-_north__district' 'district_-_west_district'
 'district_-_south_district' 'district_-_east_district'
 'state_-__arunachal_pradesh' 'district_-_tawang' 'district_-_west_kameng'
 'district_-_east_kameng' 'district_-_papum_pare'
 'district_-_upper_subansiri' 'district_-_west_siang'
 'district_-_east_siang' 'district_-_upper_siang' 'district_-_changlang'
 'district_-_tirap' 'district_-_lower_subansiri' 'district_-_kurung_kumey'
 'district_-_dibang_valley' 'district_-_lower_dibang_valley'
 'district_-_lohit' 'district_-_anjaw' 'state_-__nagaland'
 'district_-_mon' 'district_-_mokokchung' 'district_-_zunheboto'
 'district_-_wokha' 'district_-_dimapur' 'district_-_phek'
 'district_-_tuensang' 'district_-_longleng' 'district_-_kiphire'
 'district_-_kohima' 'district_-_peren' 'state_-__manipur'
 'district_-_senapati' 'district_-_tamenglong' 'district_-_churachandpur'
 'district_-_bishnupur' 'district_-_thoubal' 'district_-_imphal_west'
 'district_-_imphal_east' 'district_-_ukhrul' 'district_-_chandel'
 'state_-__mizoram' 'district_-_mamit' 'district_-_kolasib'
 'district_-_aizawl' 'district_-_champhai' 'district_-_serchhip'
 'district_-_lunglei' 'district_-_lawngtlai' 'district_-_saiha'
 'state_-__tripura' 'district_-_west_tripura' 'district_-_south_tripura'
 'district_-_dhalai' 'district_-_north_tripura' 'state_-__meghalaya'
 'district_-_west_garo_hills' 'district_-_east_garo_hills'
 'district_-_south_garo_hills' 'district_-_west_khasi_hills'
 'district_-_ribhoi' 'district_-_east_khasi_hills'
 'district_-_jaintia_hills' 'state_-__assam' 'district_-_kokrajhar'
 'district_-_dhubri' 'district_-_goalpara' 'district_-_barpeta'
 'district_-_morigaon' 'district_-_nagaon' 'district_-_sonitpur'
 'district_-_lakhimpur' 'district_-_dhemaji' 'district_-_tinsukia'
 'district_-_dibrugarh' 'district_-_sivasagar' 'district_-_jorhat'
 'district_-_golaghat' 'district_-_karbi_anglong' 'district_-_dima_hasao'
 'district_-_cachar' 'district_-_karimganj' 'district_-_hailakandi'
 'district_-_bongaigaon' 'district_-_chirang' 'district_-_kamrup'
 'district_-_kamrup_metropolitan' 'district_-_nalbari' 'district_-_baksa'
 'district_-_darrang' 'district_-_udalguri' 'state_-__west_bengal'
 'district_-_darjiling' 'district_-_jalpaiguri' 'district_-_koch_bihar'
 'district_-_uttar_dinajpur' 'district_-_dakshin_dinajpur'
 'district_-_maldah' 'district_-_murshidabad' 'district_-_birbhum'
 'district_-_barddhaman' 'district_-_nadia'
 'district_-_north_twenty_four_parganas' 'district_-_hugli'
 'district_-_bankura' 'district_-_puruliya' 'district_-_haora'
 'district_-_kolkata' 'district_-_south_twenty_four_parganas'
 'district_-_paschim_medinipur' 'district_-_purba_medinipur'
 'state_-__jharkhand' 'district_-_garhwa' 'district_-_chatra'
 'district_-_kodarma' 'district_-_giridih' 'district_-_deoghar'
 'district_-_godda' 'district_-_sahibganj' 'district_-_pakur'
 'district_-_dhanbad' 'district_-_bokaro' 'district_-_lohardaga'
 'district_-_purbi_singhbhum' 'district_-_palamu' 'district_-_latehar'
 'district_-_hazaribagh' 'district_-_ramgarh' 'district_-_dumka'
 'district_-_jamtara' 'district_-_ranchi' 'district_-_khunti'
 'district_-_gumla' 'district_-_simdega' 'district_-_pashchimi_singhbhum'
 'district_-_saraikela-kharsawan' 'state_-__odisha' 'district_-_bargarh'
 'district_-_jharsuguda' 'district_-_sambalpur' 'district_-_debagarh'
 'district_-_sundargarh' 'district_-_kendujhar' 'district_-_mayurbhanj'
 'district_-_baleshwar' 'district_-_bhadrak' 'district_-_kendrapara'
 'district_-_jagatsinghapur' 'district_-_cuttack' 'district_-_jajapur'
 'district_-_dhenkanal' 'district_-_anugul' 'district_-_nayagarh'
 'district_-_khordha' 'district_-_puri' 'district_-_ganjam'
 'district_-_gajapati' 'district_-_kandhamal' 'district_-_baudh'
 'district_-_subarnapur' 'district_-_balangir' 'district_-_nuapada'
 'district_-_kalahandi' 'district_-_rayagada' 'district_-_nabarangapur'
 'district_-_koraput' 'district_-_malkangiri' 'state_-__chhattisgarh'
 'district_-_koriya' 'district_-_surguja' 'district_-_jashpur'
 'district_-_raigarh' 'district_-_korba' 'district_-_janjgir_-_champa'
 'district_-_kabeerdham' 'district_-_rajnandgaon' 'district_-_durg'
 'district_-_raipur' 'district_-_mahasamund' 'district_-_dhamtari'
 'district_-_uttar_bastar_kanker' 'district_-_bastar'
 'district_-_narayanpur' 'district_-_dakshin_bastar_dantewada'
 'district_-_bijapur' 'state_-__madhya_pradesh' 'district_-_sheopur'
 'district_-_morena' 'district_-_bhind' 'district_-_gwalior'
 'district_-_datia' 'district_-_shivpuri' 'district_-_tikamgarh'
 'district_-_chhatarpur' 'district_-_panna' 'district_-_sagar'
 'district_-_damoh' 'district_-_satna' 'district_-_rewa'
 'district_-_umaria' 'district_-_neemuch' 'district_-_mandsaur'
 'district_-_ratlam' 'district_-_ujjain' 'district_-_shajapur'
 'district_-_dewas' 'district_-_dhar' 'district_-_indore'
 'district_-_khargone_(west_nimar)' 'district_-_barwani'
 'district_-_rajgarh' 'district_-_vidisha' 'district_-_bhopal'
 'district_-_sehore' 'district_-_raisen' 'district_-_betul'
 'district_-_harda' 'district_-_hoshangabad' 'district_-_katni'
 'district_-_jabalpur' 'district_-_narsimhapur' 'district_-_dindori'
 'district_-_mandla' 'district_-_chhindwara' 'district_-_seoni'
 'district_-_balaghat' 'district_-_guna' 'district_-_ashoknagar'
 'district_-_shahdol' 'district_-_anuppur' 'district_-_sidhi'
 'district_-_singrauli' 'district_-_jhabua' 'district_-_alirajpur'
 'district_-_khandwa_(east_nimar)' 'district_-_burhanpur'
 'state_-__gujarat' 'district_-_kachchh' 'district_-_banas_kantha'
 'district_-_patan' 'district_-_mahesana' 'district_-_sabar_kantha'
 'district_-_gandhinagar' 'district_-_ahmadabad_(m_corp._+_og)'
 'district_-_surendranagar' 'district_-_rajkot' 'district_-_jamnagar'
 'district_-_porbandar' 'district_-_junagadh' 'district_-_amreli'
 'district_-_bhavnagar' 'district_-_anand' 'district_-_kheda'
 'district_-_panch_mahals' 'district_-_dohad' 'district_-_vadodara'
 'district_-_narmada' 'district_-_bharuch' 'district_-_the_dangs'
 'district_-_navsari' 'district_-_valsad'
 'district_-_surat_(m_corp._+_og)' 'district_-_tapi'
 'union_territory_-__daman_&_diu' 'district_-_diu' 'district_-_daman'
 'union_territory_-__dadra_&_nagar_haveli'
 'district_-_dadra_&_nagar_haveli' 'state_-__maharashtra'
 'district_-_nandurbar' 'district_-_dhule' 'district_-_jalgaon'
 'district_-_buldana' 'district_-_akola' 'district_-_washim'
 'district_-_amravati' 'district_-_wardha' 'district_-_nagpur'
 'district_-_bhandara' 'district_-_gondiya' 'district_-_gadchiroli'
 'district_-_chandrapur' 'district_-_yavatmal' 'district_-_nanded'
 'district_-_hingoli' 'district_-_parbhani' 'district_-_jalna'
 'district_-_nashik' 'district_-_thane' 'district_-_mumbai_suburban'
 'district_-_mumbai' 'district_-_pune' 'district_-_ahmadnagar'
 'district_-_bid' 'district_-_latur' 'district_-_osmanabad'
 'district_-_solapur' 'district_-_satara' 'district_-_ratnagiri'
 'district_-_sindhudurg' 'district_-_kolhapur' 'district_-_sangli'
 'state_-__andhra_pradesh' 'district_-_adilabad' 'district_-_nizamabad'
 'district_-_karimnagar' 'district_-_medak' 'district_-_hyderabad'
 'district_-_rangareddy' 'district_-_mahbubnagar' 'district_-_nalgonda'
 'district_-_warangal' 'district_-_khammam' 'district_-_srikakulam'
 'district_-_vizianagaram' 'district_-_visakhapatnam'
 'district_-_east_godavari' 'district_-_west_godavari'
 'district_-_krishna' 'district_-_guntur' 'district_-_prakasam'
 'district_-_sri_potti_sriramulu_nellore' 'district_-_y.s.r.'
 'district_-_kurnool' 'district_-_anantapur' 'district_-_chittoor'
 'state_-__karnataka' 'district_-_belgaum' 'district_-_bagalkot'
 'district_-_bidar' 'district_-_raichur' 'district_-_koppal'
 'district_-_gadag' 'district_-_dharwad' 'district_-_uttara_kannada'
 'district_-_haveri' 'district_-_bellary' 'district_-_chitradurga'
 'district_-_davanagere' 'district_-_shimoga' 'district_-_udupi'
 'district_-_chikmagalur' 'district_-_tumkur' 'district_-_bangalore'
 'district_-_mandya' 'district_-_hassan' 'district_-_dakshina_kannada'
 'district_-_kodagu' 'district_-_mysore' 'district_-_chamarajanagar'
 'district_-_gulbarga' 'district_-_yadgir' 'district_-_kolar'
 'district_-_chikkaballapura' 'district_-_bangalore_rural'
 'district_-_ramanagara' 'state_-__goa' 'district_-_north_goa'
 'district_-_south_goa' 'union_territory_-__lakshadweep'
 'district_-_lakshadweep' 'state_-__kerala' 'district_-_kasaragod'
 'district_-_kannur' 'district_-_wayanad' 'district_-_kozhikode'
 'district_-_malappuram' 'district_-_palakkad' 'district_-_thrissur'
 'district_-_ernakulam' 'district_-_idukki' 'district_-_kottayam'
 'district_-_alappuzha' 'district_-_pathanamthitta' 'district_-_kollam'
 'district_-_thiruvananthapuram' 'state_-__tamil_nadu'
 'district_-_thiruvallur' 'district_-_chennai' 'district_-_kancheepuram'
 'district_-_vellore' 'district_-_tiruvannamalai' 'district_-_viluppuram'
 'district_-_salem' 'district_-_namakkal' 'district_-_erode'
 'district_-_the_nilgiris' 'district_-_dindigul' 'district_-_karur'
 'district_-_tiruchirappalli' 'district_-_perambalur'
 'district_-_ariyalur' 'district_-_cuddalore' 'district_-_nagapattinam'
 'district_-_thiruvarur' 'district_-_thanjavur' 'district_-_pudukkottai'
 'district_-_sivaganga' 'district_-_madurai' 'district_-_theni'
 'district_-_virudhunagar' 'district_-_ramanathapuram'
 'district_-_thoothukkudi' 'district_-_tirunelveli'
 'district_-_kanniyakumari' 'district_-_dharmapuri'
 'district_-_krishnagiri' 'district_-_coimbatore' 'district_-_tiruppur'
 'union_territory_-__puducherry' 'district_-_yanam'
 'district_-_puducherry' 'district_-_mahe' 'district_-_karaikal'
 'union_territory_-__andaman_&_nicobar_islands' 'district_-_nicobars'
 'district_-_north__&_middle_andaman' 'district_-_south_andaman']
----------------------------------------------------------------------------------------
['total' 'rural' 'urban']
----------------------------------------------------------------------------------------
['all_religious_communities' 'hindu' 'muslim' 'christian' 'sikh'
 'buddhist' 'jain' 'other_religious_communities']
----------------------------------------------------------------------------------------
['all_ages' 'less_than_15' '15-19' '20-24' '25-29' '30-34' '35-39' '40-44'
 '45-49' '50-54']
----------------------------------------------------------------------------------------
[587584719 178092741  56544053 ...      5631      4616      7951]
----------------------------------------------------------------------------------------
[293077472   1709811  11011012 ...     43320      7189     34904]
----------------------------------------------------------------------------------------

In [115]:
# Loading the data using Pandas
f11all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_11.xlsx')
f11all.dropna(axis = 0, inplace = True)
f11all.columns = f11all.columns.str.lower()
f11all.columns = f11all.columns.str.strip()
f11all.columns = f11all.columns.str.replace(' |\n', '_')
f11all.columns = f11all.columns.str.replace('__', '_')
f11all = f11all.applymap(lambda s:s.lower() if type(s) == str else s)
f11all['area_name'] = f11all['area_name'].str.replace('\d+', '')
f11all.drop(['table_name'], inplace = True, axis = 1)
f11all['area_name'].astype(object)
f11all['area_name'] = f11all['area_name'].str.strip(' ')
f11all = f11all.set_axis(['state_code','distt._code', 'area_name', 'total/_rural/_urban', 'educational_level','present_age', 'total_women', 'total_currently_married_women','number_of_births_last_year_m', 'number_of_births_last_year_f','last_year’s_births_of_order_1', 'last_year’s_births_of_order_2','last_year’s_births_of_order_3', 'last_year’s_births_of_order_4','last_year’s_births_of_order_5', 'last_year’s_births_of_order_6','last_year’s_births_of_order_7+'], axis=1, inplace=False)
f11all['total_currently_unmarried_women'] = f11all['total_women'] - f11all['total_currently_married_women']
f11all['number_of_births_last_year_p'] = f11all['number_of_births_last_year_m'] + f11all['number_of_births_last_year_f']
f11all = f11all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f11all.replace('50+', '50-54', inplace = True)
f11all = f11all.drop_duplicates()
f11all = f11all.reset_index(drop=True)
f11all.head()

,state_code,distt._code,area_name,total/_rural/_urban,educational_level,present_age,total_women,total_currently_married_women,number_of_births_last_year_m,number_of_births_last_year_f,last_year’s_births_of_order_1,last_year’s_births_of_order_2,last_year’s_births_of_order_3,last_year’s_births_of_order_4,last_year’s_births_of_order_5,last_year’s_births_of_order_6,last_year’s_births_of_order_7+,total_currently_unmarried_women,number_of_births_last_year_p
0,0,0,india,total,total,all_ages,587584719,293077472,11004520,9893708,8200796,6090241,3231929,1642040,795069,427988,510165,294507247,20898228
1,0,0,india,total,total,less_than_15,178092741,1709811,31276,27568,29714,29130,0,0,0,0,0,176382930,58844
2,0,0,india,total,total,15-19,56544053,11011012,663852,622830,1005107,206536,42661,32378,0,0,0,45533041,1286682
3,0,0,india,total,total,20-24,53839529,36881677,3668507,3399390,3853252,2281979,669955,164575,40028,15352,42756,16957852,7067897
4,0,0,india,total,total,25-29,50069757,44606658,3190932,2860511,2004321,2059947,1176262,513355,179536,60197,57825,5463099,6051443

In [116]:
f11all.columns

Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'educational_level', 'present_age', 'total_women',
       'total_currently_married_women', 'number_of_births_last_year_m',
       'number_of_births_last_year_f', 'last_year’s_births_of_order_1',
       'last_year’s_births_of_order_2', 'last_year’s_births_of_order_3',
       'last_year’s_births_of_order_4', 'last_year’s_births_of_order_5',
       'last_year’s_births_of_order_6', 'last_year’s_births_of_order_7+',
       'total_currently_unmarried_women', 'number_of_births_last_year_p'],
      dtype='object')

In [117]:
f11all['last_year’s_births_of_order_1_%'] = (f11all['last_year’s_births_of_order_1'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_1_%'] = (f11all['last_year’s_births_of_order_1'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_2_%'] = (f11all['last_year’s_births_of_order_2'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_3_%'] = (f11all['last_year’s_births_of_order_3'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_4_%'] = (f11all['last_year’s_births_of_order_4'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_5_%'] = (f11all['last_year’s_births_of_order_5'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_6_%'] = (f11all['last_year’s_births_of_order_6'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_7+_%'] = (f11all['last_year’s_births_of_order_7+'] /f11all['number_of_births_last_year_p'])*100
f11all['last_year’s_births_of_order_7+_%'] = (f11all['last_year’s_births_of_order_7+'] /f11all['number_of_births_last_year_p'])*100
f11all['number_of_births_last_year_m_%'] = (f11all['number_of_births_last_year_m'] /f11all['number_of_births_last_year_p'])*100
f11all['number_of_births_last_year_m_%'] = (f11all['number_of_births_last_year_m'] /f11all['number_of_births_last_year_p'])*100
f11all['number_of_births_last_year_f_%'] = (f11all['number_of_births_last_year_f'] /f11all['number_of_births_last_year_p'])*100
f11all['number_of_births_last_year_f_%'] = (f11all['number_of_births_last_year_f'] /f11all['number_of_births_last_year_p'])*100
f11all['total_currently_unmarried_women_%'] = (f11all['total_currently_unmarried_women'] /f11all['total_women'])*100
f11all['total_currently_married_women_%'] = (f11all['total_currently_married_women'] /f11all['total_women'])*100

In [118]:
f11all.dropna(axis = 0, inplace = True)
f11all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 157616 entries, 0 to 170638
Data columns (total 30 columns):
state_code                           157616 non-null int64
distt._code                          157616 non-null int64
area_name                            157616 non-null object
total/_rural/_urban                  157616 non-null object
educational_level                    157616 non-null object
present_age                          157616 non-null object
total_women                          157616 non-null int64
total_currently_married_women        157616 non-null int64
number_of_births_last_year_m         157616 non-null int64
number_of_births_last_year_f         157616 non-null int64
last_year’s_births_of_order_1        157616 non-null int64
last_year’s_births_of_order_2        157616 non-null int64
last_year’s_births_of_order_3        157616 non-null int64
last_year’s_births_of_order_4        157616 non-null int64
last_year’s_births_of_order_5        157616 non-null int64
last_year’s_births_of_order_6        157616 non-null int64
last_year’s_births_of_order_7+       157616 non-null int64
total_currently_unmarried_women      157616 non-null int64
number_of_births_last_year_p         157616 non-null int64
last_year’s_births_of_order_1_%      157616 non-null float64
last_year’s_births_of_order_2_%      157616 non-null float64
last_year’s_births_of_order_3_%      157616 non-null float64
last_year’s_births_of_order_4_%      157616 non-null float64
last_year’s_births_of_order_5_%      157616 non-null float64
last_year’s_births_of_order_6_%      157616 non-null float64
last_year’s_births_of_order_7+_%     157616 non-null float64
number_of_births_last_year_m_%       157616 non-null float64
number_of_births_last_year_f_%       157616 non-null float64
total_currently_unmarried_women_%    157616 non-null float64
total_currently_married_women_%      157616 non-null float64
dtypes: float64(11), int64(15), object(4)
memory usage: 37.3+ MB

In [119]:
# To familiarize i the values
for column in f11all:
    print(f11all[column].unique())
    print('----------------------------------------------------------------------------------------')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
----------------------------------------------------------------------------------------
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640]
----------------------------------------------------------------------------------------
['india' 'state_-_jammu_&_kashmir' 'state_-_himachal_pradesh'
 'state_-_punjab' 'union_territory_-_chandigarh' 'state_-_uttarakhand'
 'state_-_haryana' 'state_-_nct_of_delhi' 'state_-_rajasthan'
 'state_-_uttar_pradesh' 'state_-_bihar' 'state_-_sikkim'
 'state_-_arunachal_pradesh' 'state_-_nagaland' 'state_-_manipur'
 'state_-_mizoram' 'state_-_tripura' 'state_-_meghalaya' 'state_-_assam'
 'state_-_west_bengal' 'state_-_jharkhand' 'state_-_odisha'
 'state_-_chhattisgarh' 'state_-_madhya_pradesh' 'state_-_gujarat'
 'union_territory_-_daman_&_diu' 'union_territory_-_dadra_&_nagar_haveli'
 'state_-_maharashtra' 'state_-_andhra_pradesh' 'state_-_karnataka'
 'state_-_goa' 'union_territory_-_lakshadweep' 'state_-_kerala'
 'state_-_tamil_nadu' 'union_territory_-_puducherry'
 'union_territory_-_andaman_&_nicobar_islands' 'state_-___jammu_&_kashmir'
 'district_-_kupwara' 'district_-_badgam' 'district_-_leh(ladakh)'
 'district_-_kargil' 'district_-_punch' 'district_-_rajouri'
 'district_-_kathua' 'district_-_baramula' 'district_-_bandipore'
 'district_-_srinagar' 'district_-_ganderbal' 'district_-_pulwama'
 'district_-_shupiyan' 'district_-_anantnag' 'district_-_kulgam'
 'district_-_doda' 'district_-_ramban' 'district_-_kishtwar'
 'district_-_udhampur' 'district_-_reasi' 'district_-_jammu'
 'district_-_samba' 'state_-___himachal_pradesh' 'district_-_chamba'
 'district_-_kangra' 'district_-_lahul_&_spiti' 'district_-_kullu'
 'district_-_mandi' 'district_-_hamirpur' 'district_-_una'
 'district_-_bilaspur' 'district_-_solan' 'district_-_sirmaur'
 'district_-_shimla' 'district_-_kinnaur' 'state_-___punjab'
 'district_-_gurdaspur' 'district_-_kapurthala' 'district_-_jalandhar'
 'district_-_hoshiarpur' 'district_-_shahid_bhagat_singh_nagar'
 'district_-_fatehgarh_sahib' 'district_-_ludhiana' 'district_-_moga'
 'district_-_firozpur' 'district_-_muktsar' 'district_-_faridkot'
 'district_-_bathinda' 'district_-_mansa' 'district_-_patiala'
 'district_-_amritsar' 'district_-_tarn_taran' 'district_-_rupnagar'
 'district_-_sahibzada_ajit_singh_nagar' 'district_-_sangrur'
 'district_-_barnala' 'union_territory_-___chandigarh'
 'district_-_chandigarh' 'state_-___uttarakhand' 'district_-_uttarkashi'
 'district_-_chamoli' 'district_-_rudraprayag' 'district_-_tehri_garhwal'
 'district_-_dehradun' 'district_-_garhwal' 'district_-_pithoragarh'
 'district_-_bageshwar' 'district_-_almora' 'district_-_champawat'
 'district_-_nainital' 'district_-_udham_singh_nagar' 'district_-_hardwar'
 'state_-___haryana' 'district_-_panchkula' 'district_-_ambala'
 'district_-_yamunanagar' 'district_-_kurukshetra' 'district_-_kaithal'
 'district_-_karnal' 'district_-_panipat' 'district_-_sonipat'
 'district_-_jind' 'district_-_fatehabad' 'district_-_sirsa'
 'district_-_hisar' 'district_-_bhiwani' 'district_-_rohtak'
 'district_-_jhajjar' 'district_-_mahendragarh' 'district_-_rewari'
 'district_-_gurgaon' 'district_-_mewat' 'district_-_faridabad'
 'district_-_palwal' 'state_-___nct_of_delhi' 'district_-_north_west'
 'district_-_north' 'district_-_north_east' 'district_-_east'
 'district_-_new_delhi' 'district_-_central' 'district_-_west'
 'district_-_south_west' 'district_-_south' 'state_-___rajasthan'
 'district_-_ganganagar' 'district_-_hanumangarh' 'district_-_bikaner'
 'district_-_churu' 'district_-_jhunjhunun' 'district_-_alwar'
 'district_-_bharatpur' 'district_-_dhaulpur' 'district_-_karauli'
 'district_-_sawai_madhopur' 'district_-_dausa' 'district_-_jaipur'
 'district_-_sikar' 'district_-_nagaur' 'district_-_jodhpur'
 'district_-_jaisalmer' 'district_-_barmer' 'district_-_jalor'
 'district_-_sirohi' 'district_-_pali' 'district_-_ajmer'
 'district_-_tonk' 'district_-_bundi' 'district_-_bhilwara'
 'district_-_rajsamand' 'district_-_dungarpur' 'district_-_banswara'
 'district_-_chittaurgarh' 'district_-_kota' 'district_-_baran'
 'district_-_jhalawar' 'district_-_udaipur' 'district_-_pratapgarh'
 'state_-___uttar_pradesh' 'district_-_saharanpur'
 'district_-_muzaffarnagar' 'district_-_bijnor' 'district_-_moradabad'
 'district_-_rampur' 'district_-_jyotiba_phule_nagar' 'district_-_meerut'
 'district_-_baghpat' 'district_-_ghaziabad'
 'district_-_gautam_buddha_nagar' 'district_-_bulandshahr'
 'district_-_aligarh' 'district_-_mahamaya_nagar' 'district_-_mathura'
 'district_-_agra' 'district_-_firozabad' 'district_-_mainpuri'
 'district_-_budaun' 'district_-_bareilly' 'district_-_pilibhit'
 'district_-_shahjahanpur' 'district_-_kheri' 'district_-_sitapur'
 'district_-_hardoi' 'district_-_unnao' 'district_-_lucknow'
 'district_-_rae_bareli' 'district_-_farrukhabad' 'district_-_kannauj'
 'district_-_etawah' 'district_-_auraiya' 'district_-_kanpur_dehat'
 'district_-_kanpur_nagar' 'district_-_jalaun' 'district_-_jhansi'
 'district_-_lalitpur' 'district_-_mahoba' 'district_-_banda'
 'district_-_chitrakoot' 'district_-_fatehpur' 'district_-_kaushambi'
 'district_-_allahabad' 'district_-_bara_banki' 'district_-_faizabad'
 'district_-_ambedkar_nagar' 'district_-_sultanpur' 'district_-_bahraich'
 'district_-_shrawasti' 'district_-_balrampur' 'district_-_gonda'
 'district_-_siddharthnagar' 'district_-_basti'
 'district_-_sant_kabir_nagar' 'district_-_mahrajganj'
 'district_-_gorakhpur' 'district_-_kushinagar' 'district_-_deoria'
 'district_-_azamgarh' 'district_-_mau' 'district_-_ballia'
 'district_-_jaunpur' 'district_-_ghazipur' 'district_-_chandauli'
 'district_-_varanasi' 'district_-_sant_ravidas_nagar_(bhadohi)'
 'district_-_mirzapur' 'district_-_sonbhadra' 'district_-_etah'
 'district_-_kanshiram_nagar' 'state_-___bihar'
 'district_-_pashchim_champaran' 'district_-_purba_champaran'
 'district_-_sheohar' 'district_-_sitamarhi' 'district_-_madhubani'
 'district_-_supaul' 'district_-_araria' 'district_-_kishanganj'
 'district_-_purnia' 'district_-_katihar' 'district_-_madhepura'
 'district_-_saharsa' 'district_-_darbhanga' 'district_-_muzaffarpur'
 'district_-_gopalganj' 'district_-_siwan' 'district_-_saran'
 'district_-_vaishali' 'district_-_samastipur' 'district_-_begusarai'
 'district_-_khagaria' 'district_-_bhagalpur' 'district_-_banka'
 'district_-_munger' 'district_-_lakhisarai' 'district_-_sheikhpura'
 'district_-_nalanda' 'district_-_patna' 'district_-_bhojpur'
 'district_-_buxar' 'district_-_kaimur_(bhabua)' 'district_-_rohtas'
 'district_-_aurangabad' 'district_-_gaya' 'district_-_nawada'
 'district_-_jamui' 'district_-_jehanabad' 'district_-_arwal'
 'state_-___sikkim' 'district_-_north__district'
 'district_-_west_district' 'district_-_south_district'
 'district_-_east_district' 'state_-___arunachal_pradesh'
 'district_-_tawang' 'district_-_west_kameng' 'district_-_east_kameng'
 'district_-_papum_pare' 'district_-_upper_subansiri'
 'district_-_west_siang' 'district_-_east_siang' 'district_-_upper_siang'
 'district_-_changlang' 'district_-_tirap' 'district_-_lower_subansiri'
 'district_-_kurung_kumey' 'district_-_dibang_valley'
 'district_-_lower_dibang_valley' 'district_-_lohit' 'district_-_anjaw'
 'state_-___nagaland' 'district_-_mon' 'district_-_mokokchung'
 'district_-_zunheboto' 'district_-_wokha' 'district_-_dimapur'
 'district_-_phek' 'district_-_tuensang' 'district_-_longleng'
 'district_-_kiphire' 'district_-_kohima' 'district_-_peren'
 'state_-___manipur' 'district_-_senapati' 'district_-_tamenglong'
 'district_-_churachandpur' 'district_-_bishnupur' 'district_-_thoubal'
 'district_-_imphal_west' 'district_-_imphal_east' 'district_-_ukhrul'
 'district_-_chandel' 'state_-___mizoram' 'district_-_mamit'
 'district_-_kolasib' 'district_-_aizawl' 'district_-_champhai'
 'district_-_serchhip' 'district_-_lunglei' 'district_-_lawngtlai'
 'district_-_saiha' 'state_-___tripura' 'district_-_west_tripura'
 'district_-_south_tripura' 'district_-_dhalai' 'district_-_north_tripura'
 'state_-___meghalaya' 'district_-_west_garo_hills'
 'district_-_east_garo_hills' 'district_-_south_garo_hills'
 'district_-_west_khasi_hills' 'district_-_ribhoi'
 'district_-_east_khasi_hills' 'district_-_jaintia_hills'
 'state_-___assam' 'district_-_kokrajhar' 'district_-_dhubri'
 'district_-_goalpara' 'district_-_barpeta' 'district_-_morigaon'
 'district_-_nagaon' 'district_-_sonitpur' 'district_-_lakhimpur'
 'district_-_dhemaji' 'district_-_tinsukia' 'district_-_dibrugarh'
 'district_-_sivasagar' 'district_-_jorhat' 'district_-_golaghat'
 'district_-_karbi_anglong' 'district_-_dima_hasao' 'district_-_cachar'
 'district_-_karimganj' 'district_-_hailakandi' 'district_-_bongaigaon'
 'district_-_chirang' 'district_-_kamrup' 'district_-_kamrup_metropolitan'
 'district_-_nalbari' 'district_-_baksa' 'district_-_darrang'
 'district_-_udalguri' 'state_-___west_bengal' 'district_-_darjiling'
 'district_-_jalpaiguri' 'district_-_koch_bihar'
 'district_-_uttar_dinajpur' 'district_-_dakshin_dinajpur'
 'district_-_maldah' 'district_-_murshidabad' 'district_-_birbhum'
 'district_-_barddhaman' 'district_-_nadia'
 'district_-_north_twenty_four_parganas' 'district_-_hugli'
 'district_-_bankura' 'district_-_puruliya' 'district_-_haora'
 'district_-_kolkata' 'district_-_south_twenty_four_parganas'
 'district_-_paschim_medinipur' 'district_-_purba_medinipur'
 'state_-___jharkhand' 'district_-_garhwa' 'district_-_chatra'
 'district_-_kodarma' 'district_-_giridih' 'district_-_deoghar'
 'district_-_godda' 'district_-_sahibganj' 'district_-_pakur'
 'district_-_dhanbad' 'district_-_bokaro' 'district_-_lohardaga'
 'district_-_purbi_singhbhum' 'district_-_palamu' 'district_-_latehar'
 'district_-_hazaribagh' 'district_-_ramgarh' 'district_-_dumka'
 'district_-_jamtara' 'district_-_ranchi' 'district_-_khunti'
 'district_-_gumla' 'district_-_simdega' 'district_-_pashchimi_singhbhum'
 'district_-_saraikela-kharsawan' 'state_-___odisha' 'district_-_bargarh'
 'district_-_jharsuguda' 'district_-_sambalpur' 'district_-_debagarh'
 'district_-_sundargarh' 'district_-_kendujhar' 'district_-_mayurbhanj'
 'district_-_baleshwar' 'district_-_bhadrak' 'district_-_kendrapara'
 'district_-_jagatsinghapur' 'district_-_cuttack' 'district_-_jajapur'
 'district_-_dhenkanal' 'district_-_anugul' 'district_-_nayagarh'
 'district_-_khordha' 'district_-_puri' 'district_-_ganjam'
 'district_-_gajapati' 'district_-_kandhamal' 'district_-_baudh'
 'district_-_subarnapur' 'district_-_balangir' 'district_-_nuapada'
 'district_-_kalahandi' 'district_-_rayagada' 'district_-_nabarangapur'
 'district_-_koraput' 'district_-_malkangiri' 'state_-___chhattisgarh'
 'district_-_koriya' 'district_-_surguja' 'district_-_jashpur'
 'district_-_raigarh' 'district_-_korba' 'district_-_janjgir_-_champa'
 'district_-_kabeerdham' 'district_-_rajnandgaon' 'district_-_durg'
 'district_-_raipur' 'district_-_mahasamund' 'district_-_dhamtari'
 'district_-_uttar_bastar_kanker' 'district_-_bastar'
 'district_-_narayanpur' 'district_-_dakshin_bastar_dantewada'
 'district_-_bijapur' 'state_-___madhya_pradesh' 'district_-_sheopur'
 'district_-_morena' 'district_-_bhind' 'district_-_gwalior'
 'district_-_datia' 'district_-_shivpuri' 'district_-_tikamgarh'
 'district_-_chhatarpur' 'district_-_panna' 'district_-_sagar'
 'district_-_damoh' 'district_-_satna' 'district_-_rewa'
 'district_-_umaria' 'district_-_neemuch' 'district_-_mandsaur'
 'district_-_ratlam' 'district_-_ujjain' 'district_-_shajapur'
 'district_-_dewas' 'district_-_dhar' 'district_-_indore'
 'district_-_khargone_(west_nimar)' 'district_-_barwani'
 'district_-_rajgarh' 'district_-_vidisha' 'district_-_bhopal'
 'district_-_sehore' 'district_-_raisen' 'district_-_betul'
 'district_-_harda' 'district_-_hoshangabad' 'district_-_katni'
 'district_-_jabalpur' 'district_-_narsimhapur' 'district_-_dindori'
 'district_-_mandla' 'district_-_chhindwara' 'district_-_seoni'
 'district_-_balaghat' 'district_-_guna' 'district_-_ashoknagar'
 'district_-_shahdol' 'district_-_anuppur' 'district_-_sidhi'
 'district_-_singrauli' 'district_-_jhabua' 'district_-_alirajpur'
 'district_-_khandwa_(east_nimar)' 'district_-_burhanpur'
 'state_-___gujarat' 'district_-_kachchh' 'district_-_banas_kantha'
 'district_-_patan' 'district_-_mahesana' 'district_-_sabar_kantha'
 'district_-_gandhinagar' 'district_-_ahmadabad'
 'district_-_surendranagar' 'district_-_rajkot' 'district_-_jamnagar'
 'district_-_porbandar' 'district_-_junagadh' 'district_-_amreli'
 'district_-_bhavnagar' 'district_-_anand' 'district_-_kheda'
 'district_-_panch_mahals' 'district_-_dohad' 'district_-_vadodara'
 'district_-_narmada' 'district_-_bharuch' 'district_-_the_dangs'
 'district_-_navsari' 'district_-_valsad' 'district_-_surat'
 'district_-_tapi' 'union_territory_-___daman_&_diu' 'district_-_diu'
 'district_-_daman' 'union_territory_-___dadra_&_nagar_haveli'
 'district_-_dadra_&_nagar_haveli' 'state_-___maharashtra'
 'district_-_nandurbar' 'district_-_dhule' 'district_-_jalgaon'
 'district_-_buldana' 'district_-_akola' 'district_-_washim'
 'district_-_amravati' 'district_-_wardha' 'district_-_nagpur'
 'district_-_bhandara' 'district_-_gondiya' 'district_-_gadchiroli'
 'district_-_chandrapur' 'district_-_yavatmal' 'district_-_nanded'
 'district_-_hingoli' 'district_-_parbhani' 'district_-_jalna'
 'district_-_nashik' 'district_-_thane' 'district_-_mumbai_suburban'
 'district_-_mumbai' 'district_-_pune' 'district_-_ahmadnagar'
 'district_-_bid' 'district_-_latur' 'district_-_osmanabad'
 'district_-_solapur' 'district_-_satara' 'district_-_ratnagiri'
 'district_-_sindhudurg' 'district_-_kolhapur' 'district_-_sangli'
 'state_-___andhra_pradesh' 'district_-_adilabad' 'district_-_nizamabad'
 'district_-_karimnagar' 'district_-_medak' 'district_-_hyderabad'
 'district_-_rangareddy' 'district_-_mahbubnagar' 'district_-_nalgonda'
 'district_-_warangal' 'district_-_khammam' 'district_-_srikakulam'
 'district_-_vizianagaram' 'district_-_visakhapatnam'
 'district_-_east_godavari' 'district_-_west_godavari'
 'district_-_krishna' 'district_-_guntur' 'district_-_prakasam'
 'district_-_sri_potti_sriramulu_nellore' 'district_-_y.s.r.'
 'district_-_kurnool' 'district_-_anantapur' 'district_-_chittoor'
 'state_-___karnataka' 'district_-_belgaum' 'district_-_bagalkot'
 'district_-_bidar' 'district_-_raichur' 'district_-_koppal'
 'district_-_gadag' 'district_-_dharwad' 'district_-_uttara_kannada'
 'district_-_haveri' 'district_-_bellary' 'district_-_chitradurga'
 'district_-_davanagere' 'district_-_shimoga' 'district_-_udupi'
 'district_-_chikmagalur' 'district_-_tumkur' 'district_-_bangalore'
 'district_-_mandya' 'district_-_hassan' 'district_-_dakshina_kannada'
 'district_-_kodagu' 'district_-_mysore' 'district_-_chamarajanagar'
 'district_-_gulbarga' 'district_-_yadgir' 'district_-_kolar'
 'district_-_chikkaballapura' 'district_-_bangalore_rural'
 'district_-_ramanagara' 'state_-___goa' 'district_-_north_goa'
 'district_-_south_goa' 'union_territory_-___lakshadweep'
 'district_-_lakshadweep' 'state_-___kerala' 'district_-_kasaragod'
 'district_-_kannur' 'district_-_wayanad' 'district_-_kozhikode'
 'district_-_malappuram' 'district_-_palakkad' 'district_-_thrissur'
 'district_-_ernakulam' 'district_-_idukki' 'district_-_kottayam'
 'district_-_alappuzha' 'district_-_pathanamthitta' 'district_-_kollam'
 'district_-_thiruvananthapuram' 'state_-___tamil_nadu'
 'district_-_thiruvallur' 'district_-_chennai' 'district_-_kancheepuram'
 'district_-_vellore' 'district_-_tiruvannamalai' 'district_-_viluppuram'
 'district_-_salem' 'district_-_namakkal' 'district_-_erode'
 'district_-_the_nilgiris' 'district_-_dindigul' 'district_-_karur'
 'district_-_tiruchirappalli' 'district_-_perambalur'
 'district_-_ariyalur' 'district_-_cuddalore' 'district_-_nagapattinam'
 'district_-_thiruvarur' 'district_-_thanjavur' 'district_-_pudukkottai'
 'district_-_sivaganga' 'district_-_madurai' 'district_-_theni'
 'district_-_virudhunagar' 'district_-_ramanathapuram'
 'district_-_thoothukkudi' 'district_-_tirunelveli'
 'district_-_kanniyakumari' 'district_-_dharmapuri'
 'district_-_krishnagiri' 'district_-_coimbatore' 'district_-_tiruppur'
 'union_territory_-___puducherry' 'district_-_yanam'
 'district_-_puducherry' 'district_-_mahe' 'district_-_karaikal'
 'union_territory_-___andaman_&_nicobar_islands' 'district_-_nicobars'
 'district_-_north__&_middle_andaman' 'district_-_south_andaman']
----------------------------------------------------------------------------------------
['total' 'rural' 'urban']
----------------------------------------------------------------------------------------
['total' 'illiterate' 'literate' 'literate_but_below_primary'
 'primary_but_below_middle' 'middle_but_below_matric_or_secondary'
 'matric_or_secondary_but_below_graduate' 'graduate_and_above']
----------------------------------------------------------------------------------------
['all_ages' 'less_than_15' '15-19' '20-24' '25-29' '30-34' '35-39' '40-44'
 '45-49' '50-54']
----------------------------------------------------------------------------------------
[587584719 178092741  56544053 ...      7453      6278     17286]
----------------------------------------------------------------------------------------
[293077472   1709811  11011012 ...     23859     34904     29629]

In [120]:
# Loading the data using Pandas
f12all = pd.read_excel('F:\\data science\\LJMU\\research\\data\\statewise 2011\\Fertility Tables - (F - Series)\\f_12.xlsx')
f12all.dropna(axis = 0, inplace = True)
f12all.columns = f12all.columns.str.lower()
f12all.columns = f12all.columns.str.strip()
f12all.columns = f12all.columns.str.replace(' |\n', '_')
f12all.columns = f12all.columns.str.replace('__', '_')
f12all = f12all.applymap(lambda s:s.lower() if type(s) == str else s)
f12all.drop(['table_name'], inplace = True, axis = 1)
f12all['area_name'].astype(object)
f12all['area_name'] = f12all['area_name'].str.strip(' ')
f12all = f12all.set_axis(['state_code','distt._code','area_name','total/rural/urban', 'economic_activity', 'present_age','total_women', 'total_currently_married_women','number_of_births_last_year_f', 'number_of_births_last_year_m','last_year’s_births_of_order_1', 'last_year’s_births_of_order_2','last_year’s_births_of_order_3', 'last_year’s_births_of_order_4','last_year’s_births_of_order_5', 'last_year’s_births_of_order_6','last_year’s_births_of_order_7+'], axis=1, inplace=False)
f12all['total_currently_unmarried_women'] = f12all['total_women'] - f12all['total_currently_married_women']
f12all['number_of_births_last_year_p'] = f12all['number_of_births_last_year_m'] + f12all['number_of_births_last_year_f']
f12all = f12all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)
f12all.replace('50+', '50-54', inplace = True)
f12all = f12all.drop_duplicates()
f12all = f12all.reset_index(drop=True)
f12all.head()

,state_code,distt._code,area_name,total/rural/urban,economic_activity,present_age,total_women,total_currently_married_women,number_of_births_last_year_f,number_of_births_last_year_m,last_year’s_births_of_order_1,last_year’s_births_of_order_2,last_year’s_births_of_order_3,last_year’s_births_of_order_4,last_year’s_births_of_order_5,last_year’s_births_of_order_6,last_year’s_births_of_order_7+,total_currently_unmarried_women,number_of_births_last_year_p
0,0,0,india,total,total_main_workers,all_ages,89355595,68316028,2187788,1971778,1484804,1198355,702240,371209,184071,99633,119254,21039567,4159566
1,0,0,india,total,total_main_workers,less_than_15,1689200,143299,4504,3905,3681,4728,0,0,0,0,0,1545901,8409
2,0,0,india,total,total_main_workers,15-19,4981419,1822859,119922,113038,174666,42658,9273,6363,0,0,0,3158560,232960
3,0,0,india,total,total_main_workers,20-24,9686759,7117024,673059,625378,636564,455749,149240,36906,8813,3201,7964,2569735,1298437
4,0,0,india,total,total_main_workers,25-29,11764723,10044681,606549,546907,357286,374086,244201,112243,40396,13417,11827,1720042,1153456

In [121]:
f12all.columns

Index(['state_code', 'distt._code', 'area_name', 'total/rural/urban',
       'economic_activity', 'present_age', 'total_women',
       'total_currently_married_women', 'number_of_births_last_year_f',
       'number_of_births_last_year_m', 'last_year’s_births_of_order_1',
       'last_year’s_births_of_order_2', 'last_year’s_births_of_order_3',
       'last_year’s_births_of_order_4', 'last_year’s_births_of_order_5',
       'last_year’s_births_of_order_6', 'last_year’s_births_of_order_7+',
       'total_currently_unmarried_women', 'number_of_births_last_year_p'],
      dtype='object')

In [122]:
f12all.dropna(axis = 0, inplace = True)
f12all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 141960 entries, 0 to 141959
Data columns (total 19 columns):
state_code                         141960 non-null int64
distt._code                        141960 non-null int64
area_name                          141960 non-null object
total/rural/urban                  141960 non-null object
economic_activity                  141960 non-null object
present_age                        141960 non-null object
total_women                        141960 non-null int64
total_currently_married_women      141960 non-null int64
number_of_births_last_year_f       141960 non-null int64
number_of_births_last_year_m       141960 non-null int64
last_year’s_births_of_order_1      141960 non-null int64
last_year’s_births_of_order_2      141960 non-null int64
last_year’s_births_of_order_3      141960 non-null int64
last_year’s_births_of_order_4      141960 non-null int64
last_year’s_births_of_order_5      141960 non-null int64
last_year’s_births_of_order_6      141960 non-null int64
last_year’s_births_of_order_7+     141960 non-null int64
total_currently_unmarried_women    141960 non-null int64
number_of_births_last_year_p       141960 non-null int64
dtypes: int64(15), object(4)
memory usage: 21.7+ MB

In [123]:
f12all['economic_activity'] = f12all['economic_activity'].str.strip()
f12all['economic_activity'] = f12all['economic_activity'].replace({'__(a)_cultivators':'cultivators','__(b)_agricultural_labourers':'agricultural labourers','______(i)_manual':'manual','______(ii)_non-manual':'non-manual','__(c)_other_main_workers':'other workers'})
f12all['economic_activity'].unique()

array(['total_main_workers', 'cultivators', 'agricultural labourers',
       '__(c)_household_industry_workers', '__(d)_other_main_workers',
       'marginal_workers', 'non-workers'], dtype=object)

In [124]:
f12all = f12all.applymap(lambda s:s.replace(' ', '_') if type(s) == str else s)

In [125]:
f12all['last_year’s_births_of_order_1_%'] = (f12all['last_year’s_births_of_order_1'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_1_%'] = (f12all['last_year’s_births_of_order_1'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_2_%'] = (f12all['last_year’s_births_of_order_2'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_3_%'] = (f12all['last_year’s_births_of_order_3'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_4_%'] = (f12all['last_year’s_births_of_order_4'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_5_%'] = (f12all['last_year’s_births_of_order_5'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_6_%'] = (f12all['last_year’s_births_of_order_6'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_7+_%'] = (f12all['last_year’s_births_of_order_7+'] /f12all['number_of_births_last_year_p'])*100
f12all['last_year’s_births_of_order_7+_%'] = (f12all['last_year’s_births_of_order_7+'] /f12all['number_of_births_last_year_p'])*100
f12all['number_of_births_last_year_m_%'] = (f12all['number_of_births_last_year_m'] /f12all['number_of_births_last_year_p'])*100
f12all['number_of_births_last_year_m_%'] = (f12all['number_of_births_last_year_m'] /f12all['number_of_births_last_year_p'])*100
f12all['number_of_births_last_year_f_%'] = (f12all['number_of_births_last_year_f'] /f12all['number_of_births_last_year_p'])*100
f12all['number_of_births_last_year_f_%'] = (f12all['number_of_births_last_year_f'] /f12all['number_of_births_last_year_p'])*100
f12all['total_currently_unmarried_women_%'] = (f12all['total_currently_unmarried_women'] /f12all['total_women'])*100
f12all['total_currently_married_women_%'] = (f12all['total_currently_married_women'] /f12all['total_women'])*100

In [126]:
# To familiarize i the values
for column in f12all:
    print(f12all[column].unique())
    print('----------------------------------------------------------------------------------------')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
----------------------------------------------------------------------------------------
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640]
----------------------------------------------------------------------------------------
['india' 'jammu_&_kashmir' 'himachal_pradesh' 'punjab' 'chandigarh'
 'uttarakhand' 'haryana' 'nct_of_delhi' 'rajasthan' 'uttar_pradesh'
 'bihar' 'sikkim' 'arunachal_pradesh' 'nagaland' 'manipur' 'mizoram'
 'tripura' 'meghalaya' 'assam' 'west_bengal' 'jharkhand' 'odisha'
 'chhattisgarh' 'madhya_pradesh' 'gujarat' 'daman_&_diu'
 'dadra_&_nagar_haveli' 'maharashtra' 'andhra_pradesh' 'karnataka' 'goa'
 'lakshadweep' 'kerala' 'tamil_nadu' 'puducherry'
 'andaman_&_nicobar_islands' 'kupwara' 'badgam' 'leh(ladakh)' 'kargil'
 'punch' 'rajouri' 'kathua' 'baramula' 'bandipore' 'srinagar' 'ganderbal'
 'pulwama' 'shupiyan' 'anantnag' 'kulgam' 'doda' 'ramban' 'kishtwar'
 'udhampur' 'reasi' 'jammu' 'samba' 'chamba' 'kangra' 'lahul_&_spiti'
 'kullu' 'mandi' 'hamirpur' 'una' 'bilaspur' 'solan' 'sirmaur' 'shimla'
 'kinnaur' 'gurdaspur' 'kapurthala' 'jalandhar' 'hoshiarpur'
 'shahid_bhagat_singh_nagar' 'fatehgarh_sahib' 'ludhiana' 'moga'
 'firozpur' 'muktsar' 'faridkot' 'bathinda' 'mansa' 'patiala' 'amritsar'
 'tarn_taran' 'rupnagar' 'sahibzada_ajit_singh_nagar' 'sangrur' 'barnala'
 'uttarkashi' 'chamoli' 'rudraprayag' 'tehri_garhwal' 'dehradun' 'garhwal'
 'pithoragarh' 'bageshwar' 'almora\n' 'champawat' 'nainital'
 'udham_singh_nagar' 'hardwar' 'panchkula' 'ambala' 'yamunanagar'
 'kurukshetra' 'kaithal' 'karnal' 'panipat' 'sonipat' 'jind' 'fatehabad'
 'sirsa' 'hisar' 'bhiwani' 'rohtak' 'jhajjar' 'mahendragarh' 'rewari'
 'gurgaon' 'mewat' 'faridabad' 'palwal' 'north_west' 'north' 'north_east'
 'east' 'new_delhi' 'central' 'west' 'south_west' 'south' 'ganganagar'
 'hanumangarh' 'bikaner' 'churu' 'jhunjhunun' 'alwar' 'bharatpur'
 'dhaulpur' 'karauli' 'sawai_madhopur' 'dausa' 'jaipur' 'sikar' 'nagaur'
 'jodhpur' 'jaisalmer' 'barmer' 'jalor' 'sirohi' 'pali' 'ajmer' 'tonk'
 'bundi' 'bhilwara' 'rajsamand' 'dungarpur' 'banswara' 'chittaurgarh'
 'kota' 'baran' 'jhalawar' 'udaipur' 'pratapgarh' 'saharanpur'
 'muzaffarnagar' 'bijnor' 'moradabad' 'rampur' 'jyotiba_phule_nagar'
 'meerut' 'baghpat' 'ghaziabad' 'gautam_buddha_nagar' 'bulandshahr'
 'aligarh' 'mahamaya_nagar' 'mathura' 'agra' 'firozabad' 'mainpuri'
 'budaun' 'bareilly' 'pilibhit' 'shahjahanpur' 'kheri' 'sitapur' 'hardoi'
 'unnao' 'lucknow' 'rae_bareli' 'farrukhabad' 'kannauj' 'etawah' 'auraiya'
 'kanpur_dehat' 'kanpur_nagar' 'jalaun' 'jhansi' 'lalitpur' 'mahoba'
 'banda' 'chitrakoot' 'fatehpur' 'kaushambi' 'allahabad' 'bara_banki'
 'faizabad' 'ambedkar_nagar' 'sultanpur' 'bahraich' 'shrawasti'
 'balrampur' 'gonda' 'siddharthnagar' 'basti' 'sant_kabir_nagar'
 'mahrajganj' 'gorakhpur' 'kushinagar' 'deoria' 'azamgarh' 'mau' 'ballia'
 'jaunpur' 'ghazipur' 'chandauli' 'varanasi'
 'sant_ravidas_nagar_(bhadohi)' 'mirzapur' 'sonbhadra' 'etah'
 'kanshiram_nagar' 'pashchim_champaran' 'purba_champaran' 'sheohar'
 'sitamarhi' 'madhubani' 'supaul' 'araria' 'kishanganj' 'purnia' 'katihar'
 'madhepura' 'saharsa' 'darbhanga' 'muzaffarpur' 'gopalganj' 'siwan'
 'saran' 'vaishali' 'samastipur' 'begusarai' 'khagaria' 'bhagalpur'
 'banka' 'munger' 'lakhisarai' 'sheikhpura' 'nalanda' 'patna' 'bhojpur'
 'buxar' 'kaimur_(bhabua)' 'rohtas' 'aurangabad' 'gaya' 'nawada' 'jamui'
 'jehanabad' 'arwal' 'north__district' 'west_district' 'south_district'
 'east_district' 'tawang' 'west_kameng' 'east_kameng' 'papum_pare'
 'upper_subansiri' 'west_siang' 'east_siang' 'upper_siang' 'changlang'
 'tirap' 'lower_subansiri' 'kurung_kumey' 'dibang_valley'
 'lower_dibang_valley' 'lohit' 'anjaw' 'mon' 'mokokchung' 'zunheboto'
 'wokha' 'dimapur' 'phek' 'tuensang' 'longleng' 'kiphire' 'kohima' 'peren'
 'senapati' 'tamenglong' 'churachandpur' 'bishnupur' 'thoubal'
 'imphal_west' 'imphal_east' 'ukhrul' 'chandel' 'mamit' 'kolasib' 'aizawl'
 'champhai' 'serchhip' 'lunglei' 'lawngtlai' 'saiha' 'west_tripura'
 'south_tripura' 'dhalai' 'north_tripura' 'west_garo_hills'
 'east_garo_hills' 'south_garo_hills' 'west_khasi_hills' 'ribhoi'
 'east_khasi_hills' 'jaintia_hills' 'kokrajhar' 'dhubri' 'goalpara'
 'barpeta' 'morigaon' 'nagaon' 'sonitpur' 'lakhimpur' 'dhemaji' 'tinsukia'
 'dibrugarh' 'sivasagar' 'jorhat' 'golaghat' 'karbi_anglong' 'dima_hasao'
 'cachar' 'karimganj' 'hailakandi' 'bongaigaon' 'chirang' 'kamrup'
 'kamrup_metropolitan' 'nalbari' 'baksa' 'darrang' 'udalguri' 'darjiling'
 'jalpaiguri' 'koch_bihar' 'uttar_dinajpur' 'dakshin_dinajpur' 'maldah'
 'murshidabad' 'birbhum' 'barddhaman' 'nadia' 'north_twenty_four_parganas'
 'hugli' 'bankura' 'puruliya' 'haora' 'kolkata'
 'south_twenty_four_parganas' 'paschim_medinipur' 'purba_medinipur'
 'garhwa' 'chatra' 'kodarma' 'giridih' 'deoghar' 'godda' 'sahibganj'
 'pakur' 'dhanbad' 'bokaro' 'lohardaga' 'purbi_singhbhum' 'palamu'
 'latehar' 'hazaribagh' 'ramgarh' 'dumka' 'jamtara' 'ranchi' 'khunti'
 'gumla' 'simdega' 'pashchimi_singhbhum' 'saraikela-kharsawan' 'bargarh'
 'jharsuguda' 'sambalpur' 'debagarh' 'sundargarh' 'kendujhar' 'mayurbhanj'
 'baleshwar' 'bhadrak' 'kendrapara' 'jagatsinghapur' 'cuttack' 'jajapur'
 'dhenkanal' 'anugul' 'nayagarh' 'khordha' 'puri' 'ganjam' 'gajapati'
 'kandhamal' 'baudh' 'subarnapur' 'balangir' 'nuapada' 'kalahandi'
 'rayagada' 'nabarangapur' 'koraput' 'malkangiri' 'koriya' 'surguja'
 'jashpur' 'raigarh' 'korba' 'janjgir_-_champa' 'kabeerdham' 'rajnandgaon'
 'durg' 'raipur' 'mahasamund' 'dhamtari' 'uttar_bastar_kanker' 'bastar'
 'narayanpur' 'dakshin_bastar_dantewada' 'bijapur' 'sheopur' 'morena'
 'bhind' 'gwalior' 'datia' 'shivpuri' 'tikamgarh' 'chhatarpur' 'panna'
 'sagar' 'damoh' 'satna' 'rewa' 'umaria' 'neemuch' 'mandsaur' 'ratlam'
 'ujjain' 'shajapur' 'dewas' 'dhar' 'indore' 'khargone_(west_nimar)'
 'barwani' 'rajgarh' 'vidisha' 'bhopal' 'sehore' 'raisen' 'betul' 'harda'
 'hoshangabad' 'katni' 'jabalpur' 'narsimhapur' 'dindori' 'mandla'
 'chhindwara' 'seoni' 'balaghat' 'guna' 'ashoknagar' 'shahdol' 'anuppur'
 'sidhi' 'singrauli' 'jhabua' 'alirajpur' 'khandwa_(east_nimar)'
 'burhanpur' 'kachchh' 'banas_kantha' 'patan' 'mahesana' 'sabar_kantha'
 'gandhinagar' 'ahmadabad' 'surendranagar' 'rajkot' 'jamnagar' 'porbandar'
 'junagadh' 'amreli' 'bhavnagar' 'anand' 'kheda' 'panch_mahals' 'dohad'
 'vadodara' 'narmada' 'bharuch' 'the_dangs' 'navsari' 'valsad' 'surat'
 'tapi' 'diu' 'daman' 'nandurbar' 'dhule' 'jalgaon' 'buldana' 'akola'
 'washim' 'amravati' 'wardha' 'nagpur' 'bhandara' 'gondiya' 'gadchiroli'
 'chandrapur' 'yavatmal' 'nanded' 'hingoli' 'parbhani' 'jalna' 'nashik'
 'thane' 'mumbai_suburban' 'mumbai' 'pune' 'ahmadnagar' 'bid' 'latur'
 'osmanabad' 'solapur' 'satara' 'ratnagiri' 'sindhudurg' 'kolhapur'
 'sangli' 'adilabad' 'nizamabad' 'karimnagar' 'medak' 'hyderabad'
 'rangareddy' 'mahbubnagar' 'nalgonda' 'warangal' 'khammam' 'srikakulam'
 'vizianagaram' 'visakhapatnam' 'east_godavari' 'west_godavari' 'krishna'
 'guntur' 'prakasam' 'sri_potti_sriramulu_nellore' 'y.s.r.' 'kurnool'
 'anantapur' 'chittoor' 'belgaum' 'bagalkot' 'bidar' 'raichur' 'koppal'
 'gadag' 'dharwad' 'uttara_kannada' 'haveri' 'bellary' 'chitradurga'
 'davanagere' 'shimoga' 'udupi' 'chikmagalur' 'tumkur' 'bangalore'
 'mandya' 'hassan' 'dakshina_kannada' 'kodagu' 'mysore' 'chamarajanagar'
 'gulbarga' 'yadgir' 'kolar' 'chikkaballapura' 'bangalore_rural'
 'ramanagara' 'north_goa' 'south_goa' 'kasaragod' 'kannur' 'wayanad'
 'kozhikode' 'malappuram' 'palakkad' 'thrissur' 'ernakulam' 'idukki'
 'kottayam' 'alappuzha' 'pathanamthitta' 'kollam' 'thiruvananthapuram'
 'thiruvallur' 'chennai' 'kancheepuram' 'vellore' 'tiruvannamalai'
 'viluppuram' 'salem' 'namakkal' 'erode' 'the_nilgiris' 'dindigul' 'karur'
 'tiruchirappalli' 'perambalur' 'ariyalur' 'cuddalore' 'nagapattinam'
 'thiruvarur' 'thanjavur' 'pudukkottai' 'sivaganga' 'madurai' 'theni'
 'virudhunagar' 'ramanathapuram' 'thoothukkudi' 'tirunelveli'
 'kanniyakumari' 'dharmapuri' 'krishnagiri' 'coimbatore' 'tiruppur'
 'yanam' 'mahe' 'karaikal' 'nicobars' 'north__&_middle_andaman'
 'south_andaman']
----------------------------------------------------------------------------------------
['total' 'rural' 'urban']
----------------------------------------------------------------------------------------
['total_main_workers' 'cultivators' 'agricultural_labourers'
 '__(c)_household_industry_workers' '__(d)_other_main_workers'
 'marginal_workers' 'non-workers']
----------------------------------------------------------------------------------------
['all_ages' 'less_than_15' '15-19' '20-24' '25-29' '30-34' '35-39' '40-44'
 '45-49' '50-54']
----------------------------------------------------------------------------------------
[89355595  1689200  4981419 ...    42769    91591    11483]
----------------------------------------------------------------------------------------
[68316028   143299  1822859 ...    21157    18863    26867]
----------------------------------------------------------------------------------------
[2187788    4504  119922 ...    4949   10051    5921]
----------------------------------------------------------------------------------------
[1971778    3905  113038 ...    9726    4003    5847]
----------------------------------------------------------------------------------------
[1484804    3681  174666 ...   10244    6477    4364]
----------------------------------------------------------------------------------------
[1198355    4728   42658 ...    3515    7679    3944]
----------------------------------------------------------------------------------------
[702240      0   9273 ...   2666   1928   1460]
----------------------------------------------------------------------------------------
[371209      0   6363 ...   1910   2836   2339]
----------------------------------------------------------------------------------------
[184071      0   8813 ...    721    826   1605]
----------------------------------------------------------------------------------------
[99633     0  3201 ...   694   542   356]
----------------------------------------------------------------------------------------
[119254      0   7964 ...    937   1875    442]
----------------------------------------------------------------------------------------
[21039567  1545901  3158560 ...    18762    11133    27099]
----------------------------------------------------------------------------------------
[4159566    8409  232960 ...   11768    7969    2328]
----------------------------------------------------------------------------------------
[35.69612791 43.77452729 74.97682005 ... 51.4893617  55.72269457
 54.24354244]
----------------------------------------------------------------------------------------
[28.8096162  56.22547271 18.31129808 ... 30.34663179 26.32575758
 36.45320197]
----------------------------------------------------------------------------------------
[16.88253053  0.          3.98051168 ...  3.78619154  9.42857143
  9.87573578]
----------------------------------------------------------------------------------------
[ 8.92422431  0.          2.73137019 ... 53.84615385  2.87162162
  2.41988228]
----------------------------------------------------------------------------------------
[4.42524533 0.         0.67873913 ... 0.20470829 0.92905405 0.85022891]
----------------------------------------------------------------------------------------
[2.39527393 0.         0.24652717 ... 0.79422383 0.96385542 0.36859565]
----------------------------------------------------------------------------------------
[2.8669818  0.         0.61335282 ... 0.29487652 0.51177073 0.52321779]
----------------------------------------------------------------------------------------
[47.40345507 46.43833987 48.52249313 ... 50.16891892 52.28571429
 48.85546109]
----------------------------------------------------------------------------------------
[52.59654493 53.56166013 51.47750687 ... 49.83108108 47.71428571
 51.14453891]
----------------------------------------------------------------------------------------
[23.54588652 91.51675349 63.40683247 ...  7.23047127 10.47258979
 38.38840399]
----------------------------------------------------------------------------------------
[76.45411348  8.48324651 36.59316753 ... 92.76952873 89.52741021
 61.61159601]
----------------------------------------------------------------------------------------

# merge

In [168]:
basic = pd.merge(f1all, f5all,  how='left', on=['total/_rural/_urban','present_age','all/sc/st','state_code','distt._code', 'area_name'])

In [169]:
basic = pd.merge(f9all, basic,  how='left', on=['total/_rural/_urban','present_age','all/sc/st','state_code','distt._code', 'area_name'])

In [170]:
basic = basic.drop(['total_women_x','total_women_y','total_ever_married_women_y','total_ever_unmarried_women_y'], axis = 1)

In [171]:
basic['total_survival_rate'] = basic['ttl_surv._child._p']/basic['total_children_ever_born_p']

In [172]:
basic = basic.fillna(0)

In [173]:
basic.columns

Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'present_age', 'total_women', 'total_currently_married_women',
       'number_of_births_last_year_m', 'number_of_births_last_year_f',
       'last_year’s_births_of_order_1', 'last_year’s_births_of_order_2',
       'last_year’s_births_of_order_3', 'last_year’s_births_of_order_4',
       'last_year’s_births_of_order_5', 'last_year’s_births_of_order_6',
       'last_year’s_births_of_order_7+', 'all/sc/st',
       'total_currently_unmarried_women', 'number_of_births_last_year_p',
       'last_year’s_births_of_order_1_%', 'last_year’s_births_of_order_2_%',
       'last_year’s_births_of_order_3_%', 'last_year’s_births_of_order_4_%',
       'last_year’s_births_of_order_5_%', 'last_year’s_births_of_order_6_%',
       'last_year’s_births_of_order_7+_%', 'number_of_births_last_year_m_%',
       'number_of_births_last_year_f_%', 'total_currently_unmarried_women_%',
       'total_currently_married_women_%', 'total_ever_married_women_x',
       'parity_0', 'parity_1', 'parity_2', 'parity_3', 'parity_4', 'parity_5',
       'parity_6', 'parity_7+', 'total_children_ever_born_p',
       'total_children_ever_born_m', 'total_children_ever_born_f',
       'total_ever_unmarried_women_x', 'parity_0_%', 'parity_1_%',
       'parity_2_%', 'parity_3_%', 'parity_4_%', 'parity_5_%', 'parity_6_%',
       'parity_7+_%', 'total_ever_married_women_%_x',
       'total_ever_unmarried_women_%_x', 'total_children_ever_born_m_%',
       'total_children_ever_born_f_%', 'no._of_surv._child._0',
       'no._of_surv._child._1', 'no._of_surv._child._2',
       'no._of_surv._child._3', 'no._of_surv._child._4',
       'no._of_surv._child._5+', 'ttl_surv._child._p', 'ttl_surv._child._m',
       'ttl_surv._child._f', 'total_ever_unmarried_women_%_y',
       'total_ever_married_women_%_y', 'ttl_surv._child._m_%',
       'ttl_surv._child._f_%', 'no._of_surv._child._0_%',
       'no._of_surv._child._1_%', 'no._of_surv._child._2_%',
       'no._of_surv._child._3_%', 'no._of_surv._child._4_%',
       'no._of_surv._child._5+_%', 'total_survival_rate'],
      dtype='object')

In [131]:
religion = pd.merge(f2all, f6all,  how='left', on=['total/_rural/_urban','religious_community','present_age','state_code','area_name','distt._code'])

In [132]:
religion = pd.merge(religion, f10all,  how='left',on=['total/_rural/_urban','religious_community','present_age','state_code','area_name','distt._code'])

In [133]:
religion = religion.drop(['total_women_x','total_women_y','total_ever_married_women_y','total_ever_unmarried_women_y'], axis = 1) 
religion['total_survival_rate'] = religion['ttl_surv._child._p']/religion['total_children_ever_born_p']
religion = religion.fillna(0)

In [134]:
education = pd.merge(f3all, f7all,  how='left', on=['total/_rural/_urban','educational_level','present_age','state_code','area_name','distt._code'])

In [135]:
education = pd.merge(education, f11all,  how='left',on=['total/_rural/_urban','educational_level','present_age','state_code','area_name','distt._code'])

In [136]:
education = education.drop(['total_women_x','total_women_y','total_ever_married_women_y','total_ever_unmarried_women_y'], axis = 1) 
education['total_survival_rate'] = education['ttl_surv._child._p']/education['total_children_ever_born_p']
education = education.fillna(0)

In [137]:
economics = pd.merge(f4all, f8all,  how='outer', left_on=['total/rural/urban','economic_activity','present_age','state_code','area_name','district_code'], right_on = ['total/rural/urban','economic_activity','present_age','state_code','area_name','distt._code'])

In [138]:
economics = pd.merge(economics, f12all,  how='left',on=['total/rural/urban','economic_activity','present_age','state_code','area_name','distt._code'])

In [139]:
economics = economics.drop(['total_women_x','total_women_y','total_ever_married_women_y','total_ever_unmarried_women_y'], axis = 1) 
economics['total_survival_rate'] = economics['ttl_surv._child._p']/economics['total_children_ever_born_p']
economics = economics.fillna(0)

# linear

## basic

In [174]:
print(basic.info())
print(basic.columns)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53716 entries, 0 to 53715
Data columns (total 75 columns):
state_code                           53716 non-null int64
distt._code                          53716 non-null int64
area_name                            53716 non-null object
total/_rural/_urban                  53716 non-null object
present_age                          53716 non-null object
total_women                          53716 non-null int64
total_currently_married_women        53716 non-null int64
number_of_births_last_year_m         53716 non-null int64
number_of_births_last_year_f         53716 non-null int64
last_year’s_births_of_order_1        53716 non-null int64
last_year’s_births_of_order_2        53716 non-null int64
last_year’s_births_of_order_3        53716 non-null int64
last_year’s_births_of_order_4        53716 non-null int64
last_year’s_births_of_order_5        53716 non-null int64
last_year’s_births_of_order_6        53716 non-null int64
last_year’s_births_of_order_7+       53716 non-null int64
all/sc/st                            53716 non-null object
total_currently_unmarried_women      53716 non-null int64
number_of_births_last_year_p         53716 non-null int64
last_year’s_births_of_order_1_%      53716 non-null float64
last_year’s_births_of_order_2_%      53716 non-null float64
last_year’s_births_of_order_3_%      53716 non-null float64
last_year’s_births_of_order_4_%      53716 non-null float64
last_year’s_births_of_order_5_%      53716 non-null float64
last_year’s_births_of_order_6_%      53716 non-null float64
last_year’s_births_of_order_7+_%     53716 non-null float64
number_of_births_last_year_m_%       53716 non-null float64
number_of_births_last_year_f_%       53716 non-null float64
total_currently_unmarried_women_%    53716 non-null float64
total_currently_married_women_%      53716 non-null float64
total_ever_married_women_x           53716 non-null int64
parity_0                             53716 non-null int64
parity_1                             53716 non-null int64
parity_2                             53716 non-null int64
parity_3                             53716 non-null int64
parity_4                             53716 non-null int64
parity_5                             53716 non-null int64
parity_6                             53716 non-null int64
parity_7+                            53716 non-null int64
total_children_ever_born_p           53716 non-null int64
total_children_ever_born_m           53716 non-null int64
total_children_ever_born_f           53716 non-null int64
total_ever_unmarried_women_x         53716 non-null int64
parity_0_%                           53716 non-null float64
parity_1_%                           53716 non-null float64
parity_2_%                           53716 non-null float64
parity_3_%                           53716 non-null float64
parity_4_%                           53716 non-null float64
parity_5_%                           53716 non-null float64
parity_6_%                           53716 non-null float64
parity_7+_%                          53716 non-null float64
total_ever_married_women_%_x         53716 non-null float64
total_ever_unmarried_women_%_x       53716 non-null float64
total_children_ever_born_m_%         53716 non-null float64
total_children_ever_born_f_%         53716 non-null float64
no._of_surv._child._0                53716 non-null float64
no._of_surv._child._1                53716 non-null float64
no._of_surv._child._2                53716 non-null float64
no._of_surv._child._3                53716 non-null float64
no._of_surv._child._4                53716 non-null float64
no._of_surv._child._5+               53716 non-null float64
ttl_surv._child._p                   53716 non-null float64
ttl_surv._child._m                   53716 non-null float64
ttl_surv._child._f                   53716 non-null float64
total_ever_unmarried_women_%_y       53716 non-null float64
total_ever_married_women_%_y         53716 non-null float64
ttl_surv._child._m_%                 53716 non-null float64
ttl_surv._child._f_%                 53716 non-null float64
no._of_surv._child._0_%              53716 non-null float64
no._of_surv._child._1_%              53716 non-null float64
no._of_surv._child._2_%              53716 non-null float64
no._of_surv._child._3_%              53716 non-null float64
no._of_surv._child._4_%              53716 non-null float64
no._of_surv._child._5+_%             53716 non-null float64
total_survival_rate                  53716 non-null float64
dtypes: float64(43), int64(28), object(4)
memory usage: 31.1+ MB
None
Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'present_age', 'total_women', 'total_currently_married_women',
       'number_of_births_last_year_m', 'number_of_births_last_year_f',
       'last_year’s_births_of_order_1', 'last_year’s_births_of_order_2',
       'last_year’s_births_of_order_3', 'last_year’s_births_of_order_4',
       'last_year’s_births_of_order_5', 'last_year’s_births_of_order_6',
       'last_year’s_births_of_order_7+', 'all/sc/st',
       'total_currently_unmarried_women', 'number_of_births_last_year_p',
       'last_year’s_births_of_order_1_%', 'last_year’s_births_of_order_2_%',
       'last_year’s_births_of_order_3_%', 'last_year’s_births_of_order_4_%',
       'last_year’s_births_of_order_5_%', 'last_year’s_births_of_order_6_%',
       'last_year’s_births_of_order_7+_%', 'number_of_births_last_year_m_%',
       'number_of_births_last_year_f_%', 'total_currently_unmarried_women_%',
       'total_currently_married_women_%', 'total_ever_married_women_x',
       'parity_0', 'parity_1', 'parity_2', 'parity_3', 'parity_4', 'parity_5',
       'parity_6', 'parity_7+', 'total_children_ever_born_p',
       'total_children_ever_born_m', 'total_children_ever_born_f',
       'total_ever_unmarried_women_x', 'parity_0_%', 'parity_1_%',
       'parity_2_%', 'parity_3_%', 'parity_4_%', 'parity_5_%', 'parity_6_%',
       'parity_7+_%', 'total_ever_married_women_%_x',
       'total_ever_unmarried_women_%_x', 'total_children_ever_born_m_%',
       'total_children_ever_born_f_%', 'no._of_surv._child._0',
       'no._of_surv._child._1', 'no._of_surv._child._2',
       'no._of_surv._child._3', 'no._of_surv._child._4',
       'no._of_surv._child._5+', 'ttl_surv._child._p', 'ttl_surv._child._m',
       'ttl_surv._child._f', 'total_ever_unmarried_women_%_y',
       'total_ever_married_women_%_y', 'ttl_surv._child._m_%',
       'ttl_surv._child._f_%', 'no._of_surv._child._0_%',
       'no._of_surv._child._1_%', 'no._of_surv._child._2_%',
       'no._of_surv._child._3_%', 'no._of_surv._child._4_%',
       'no._of_surv._child._5+_%', 'total_survival_rate'],
      dtype='object')

In [175]:
# Seperating into categortical and numric
categorical = basic.select_dtypes(include=['object'])
numeric = basic.select_dtypes(exclude=['object'])
print(categorical.columns.values)
print(numeric.columns.values)

['area_name' 'total/_rural/_urban' 'present_age' 'all/sc/st']
['state_code' 'distt._code' 'total_women' 'total_currently_married_women'
 'number_of_births_last_year_m' 'number_of_births_last_year_f'
 'last_year’s_births_of_order_1' 'last_year’s_births_of_order_2'
 'last_year’s_births_of_order_3' 'last_year’s_births_of_order_4'
 'last_year’s_births_of_order_5' 'last_year’s_births_of_order_6'
 'last_year’s_births_of_order_7+' 'total_currently_unmarried_women'
 'number_of_births_last_year_p' 'last_year’s_births_of_order_1_%'
 'last_year’s_births_of_order_2_%' 'last_year’s_births_of_order_3_%'
 'last_year’s_births_of_order_4_%' 'last_year’s_births_of_order_5_%'
 'last_year’s_births_of_order_6_%' 'last_year’s_births_of_order_7+_%'
 'number_of_births_last_year_m_%' 'number_of_births_last_year_f_%'
 'total_currently_unmarried_women_%' 'total_currently_married_women_%'
 'total_ever_married_women_x' 'parity_0' 'parity_1' 'parity_2' 'parity_3'
 'parity_4' 'parity_5' 'parity_6' 'parity_7+' 'total_children_ever_born_p'
 'total_children_ever_born_m' 'total_children_ever_born_f'
 'total_ever_unmarried_women_x' 'parity_0_%' 'parity_1_%' 'parity_2_%'
 'parity_3_%' 'parity_4_%' 'parity_5_%' 'parity_6_%' 'parity_7+_%'
 'total_ever_married_women_%_x' 'total_ever_unmarried_women_%_x'
 'total_children_ever_born_m_%' 'total_children_ever_born_f_%'
 'no._of_surv._child._0' 'no._of_surv._child._1' 'no._of_surv._child._2'
 'no._of_surv._child._3' 'no._of_surv._child._4' 'no._of_surv._child._5+'
 'ttl_surv._child._p' 'ttl_surv._child._m' 'ttl_surv._child._f'
 'total_ever_unmarried_women_%_y' 'total_ever_married_women_%_y'
 'ttl_surv._child._m_%' 'ttl_surv._child._f_%' 'no._of_surv._child._0_%'
 'no._of_surv._child._1_%' 'no._of_surv._child._2_%'
 'no._of_surv._child._3_%' 'no._of_surv._child._4_%'
 'no._of_surv._child._5+_%' 'total_survival_rate']

In [142]:
# Creating dummies
category = ['area_name','total/_rural/_urban', 'present_age' ,'all/sc/st']
dummy = pd.get_dummies(basic[category])
basic_1 = pd.concat([basic, dummy], axis=1)
basic_1 = basic_1.drop(category, axis=1)

In [143]:
# Converting everything into float for model building
basic_1 = basic_1.astype('float')
basic_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 90073 entries, 0 to 90072
Columns: 739 entries, state_code to all/sc/st_st
dtypes: float64(739)
memory usage: 508.5 MB

In [144]:
from sklearn.model_selection import train_test_split

In [145]:
# Putting feature variable to X
X = basic_1.drop(['total_survival_rate'], axis=1)
X.head()

,state_code,distt._code,total_ever_married_women_x,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,...,present_age_60-64,present_age_65-69,present_age_70-74,present_age_75-79,present_age_80+,present_age_all_ages,present_age_less_than_15,all/sc/st_all,all/sc/st_sc,all/sc/st_st
0,0.0,0.0,339621277.0,49549956.0,50938514.0,81485683.0,60424480.0,40104260.0,23742379.0,14490504.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.0,0.0,1812200.0,1355195.0,136777.0,320228.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,0.0,11229274.0,7880413.0,2243929.0,605514.0,215480.0,283938.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,37474855.0,12988953.0,12869090.0,8233549.0,2313647.0,621922.0,173729.0,81731.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,45672215.0,7339229.0,10679349.0,15526465.0,7645252.0,2928732.0,904274.0,300426.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [146]:
# Putting response variable to y
y = basic_1['total_survival_rate']
y.head()

0    0.895752
1    0.927205
2    0.906729
3    0.918278
4    0.925913
Name: total_survival_rate, dtype: float64

In [147]:
from sklearn.model_selection import train_test_split

In [148]:
df_train, df_test = train_test_split(basic_1, train_size = 0.7, test_size = 0.3, random_state = 100)

In [149]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [150]:
# Apply scaler() to all the columns except the 'yes-no' and 'dummy' variables
num_vars = ['total_ever_married_women_x', 'parity_0',\
 'parity_1', 'parity_2', 'parity_3', 'parity_4' ,'parity_5', 'parity_6',\
 'parity_7+', 'total_children_ever_born_p' ,'total_children_ever_born_m',\
 'total_children_ever_born_f' ,'total_ever_unmarried_women_x', 'parity_0_%',\
 'parity_1_%', 'parity_2_%' ,'parity_3_%' ,'parity_4_%', 'parity_5_%',\
 'parity_6_%' ,'parity_7+_%', 'total_ever_married_women_%_x',\
 'total_ever_unmarried_women_%_x' ,'total_children_ever_born_m_%',\
 'total_children_ever_born_f_%', 'no._of_surv._child._0',\
 'no._of_surv._child._1', 'no._of_surv._child._2' ,'no._of_surv._child._3',\
 'no._of_surv._child._4', 'no._of_surv._child._5+', 'ttl_surv._child._p',\
 'ttl_surv._child._m' ,'ttl_surv._child._f',\
 'total_ever_unmarried_women_%_y', 'total_ever_married_women_%_y',\
 'ttl_surv._child._m_%' ,'ttl_surv._child._f_%' ,'no._of_surv._child._0_%',\
 'no._of_surv._child._1_%', 'no._of_surv._child._2_%',\
 'no._of_surv._child._3_%' ,'no._of_surv._child._4_%',\
 'no._of_surv._child._5+_%' ,'total_survival_rate']
df_train[num_vars] = scaler.fit_transform(df_train[num_vars])
df_train

,state_code,distt._code,total_ever_married_women_x,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,...,present_age_60-64,present_age_65-69,present_age_70-74,present_age_75-79,present_age_80+,present_age_all_ages,present_age_less_than_15,all/sc/st_all,all/sc/st_sc,all/sc/st_st
37616,7.0,92.0,4.711130e-08,0.000000e+00,3.926302e-08,1.227209e-08,3.309917e-08,4.987001e-08,8.423756e-08,0.000000e+00,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
57980,29.0,556.0,8.332811e-06,6.720490e-06,4.358195e-06,2.748949e-06,4.931776e-06,9.126213e-06,1.516276e-05,2.229046e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
51058,22.0,410.0,1.057060e-06,8.678111e-07,9.815756e-07,3.804349e-07,8.771279e-07,1.097140e-06,1.600514e-06,2.967461e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
56305,27.0,521.0,3.239991e-04,3.400407e-04,3.037976e-04,3.651439e-04,3.972231e-04,3.260502e-04,2.418881e-04,1.824643e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
53120,23.0,454.0,8.421145e-07,4.056512e-06,9.815756e-07,1.840814e-07,2.316942e-07,1.745450e-07,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
54511,24.0,483.0,7.243362e-07,3.350154e-06,1.766836e-07,8.835908e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
17978,19.0,341.0,5.769839e-04,6.082750e-04,1.423618e-03,7.651651e-04,3.316537e-04,1.651695e-04,8.196314e-05,4.948068e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40042,9.0,143.0,1.062949e-06,8.274478e-07,6.871029e-07,4.540675e-07,6.950825e-07,1.396360e-06,1.768989e-06,3.105482e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
15119,15.0,281.0,3.433236e-06,1.130173e-06,9.226810e-07,9.817676e-07,2.465888e-06,6.009337e-06,8.465874e-06,1.062765e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
70263,10.0,216.0,2.767789e-07,2.623615e-07,2.355781e-07,1.595372e-07,2.978925e-07,4.737651e-07,2.527127e-07,4.140643e-07,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
50804,22.0,405.0,3.095507e-05,2.744705e-05,2.787675e-05,2.297336e-05,3.108012e-05,4.012043e-05,4.072886e-05,4.271763e-05,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
25806,27.0,504.0,7.168279e-05,2.159437e-05,2.756264e-05,5.809610e-05,1.582637e-04,1.250740e-04,6.877997e-05,4.085434e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
82842,24.0,482.0,2.564621e-06,1.997984e-06,2.375413e-06,2.834854e-06,3.409214e-06,2.767786e-06,2.316533e-06,2.001311e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32069,34.0,636.0,1.107116e-06,5.650863e-07,7.459974e-07,4.908838e-07,7.778304e-07,8.477902e-07,1.853226e-06,3.174493e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
54800,24.0,489.0,6.477804e-08,1.816349e-07,1.766836e-07,2.454419e-08,4.964875e-08,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
69491,9.0,198.0,1.030560e-07,0.000000e+00,0.000000e+00,4.908838e-08,1.158471e-07,2.493501e-07,1.684751e-07,4.140643e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
76273,19.0,344.0,2.997456e-06,5.832498e-06,7.420711e-06,3.252105e-06,1.026074e-06,2.493501e-07,2.105939e-07,2.070321e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
64946,5.0,59.0,8.833369e-09,0.000000e+00,3.926302e-08,0.000000e+00,1.654958e-08,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36738,6.0,74.0,8.247422e-06,2.643796e-06,2.237992e-06,1.889903e-06,4.203594e-06,9.899198e-06,1.819531e-05,2.753527e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
30816,33.0,610.0,1.683463e-04,1.015743e-04,1.793927e-04,2.342988e-04,2.152935e-04,1.543477e-04,1.157003e-04,7.798210e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88029,32.0,592.0,2.026080e-05,2.367308e-05,2.251734e-05,1.779454e-05,2.091867e-05,1.974853e-05,1.768989e-05,1.745971e-05,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
47550,19.0,337.0,1.208552e-04,4.056512e-05,8.453329e-05,1.712816e-04,1.962284e-04,1.416059e-04,8.385849e-05,5.023980e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
78021,21.0,381.0,8.126699e-07,8.274478e-07,5.104193e-07,4.663396e-07,7.116321e-07,1.022335e-06,1.516276e-06,1.656257e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
37033,6.0,80.0,3.098157e-05,5.786080e-05,6.961334e-05,3.476684e-05,1.557316e-05,5.485702e-06,2.274414e-06,1.311204e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5461,6.0,79.0,1.039275e-04,3.878914e-05,8.359097e-05,1.752332e-04,1.465466e-04,9.398004e-05,5.757637e-05,3.222800e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28892,29.0,569.0,4.003577e-05,3.535826e-05,7.416785e-05,7.344849e-05,2.434444e-05,9.699718e-06,4.675184e-06,3.519546e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40260,9.0,148.0,1.549962e-05,5.327956e-06,4.358195e-06,4.098880e-06,9.317416e-06,2.111995e-05,3.563249e-05,5.369033e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9245,9.0,158.0,5.011465e-06,4.520690e-06,3.455146e-06,2.307154e-06,3.607809e-06,5.809857e-06,8.718587e-06,9.799521e-06,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
38100,8.0,103.0,2.254276e-05,3.995967e-06,4.927509e-06,1.167076e-05,3.405904e-05,4.523210e-05,5.007923e-05,4.437389e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5984,7.0,90.0,1.623809e-04,1.102927e-04,1.410720e-04,1.665814e-04,1.962284e-04,1.895061e-04,1.800157e-04,1.670059e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35981,5.0,58.0,5.376577e-06,8.213933e-06,1.154333e-05,6.577843e-06,3.624359e-06,1.396360e-06,4.211878e-07,2.760428e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
21377,22.0,412.0,3.775382e-05,1.509588e-05,1.230896e-05,1.428472e-05,3.483687e-05,6.657647e-05,9.632565e-05,1.068286e-04,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27039,27.0,530.0,8.543929e-05,4.809288e-05,7.116423e-05,1.118601e-04,1.366996e-04,9.111252e-05,5.311178e-05,2.677616e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
30596,33.0,605.0,3.223591e-05,3.622607e-05,2.031861e-05,1.536466e-05,2.273913e-05,3.745238e-05,5.993502e-05,7.466959e-05,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
83820,27.0,503.0,3.986205e-05,2.766905e-05,3.751582e-05,5.866061e-05,5.845313e-05,3.465966e-05,1.587878e-05,6.279975e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
71323,10.0,239.0,1.472228e-08,0.000000e+00,1.963151e-08,4.908838e-08,0.000000e+00,0.000000e+00,0.000000e+00,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
84354,27.0,514.0,2.037564e-06,1.190718e-06,8.048920e-07,9.694955e-07,2.283843e-06,3.017136e-06,4.085522e-06,5.244814e-06,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6230,7.0,96.0,2.752124e-04,9.323924e-05,2.717983e-04,4.441394e-04,3.372640e-04,2.613189e-04,1.847751e-04,1.228391e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
80989,23.0,443.0,4.996742e-06,1.553987e-06,1.060102e-06,1.251754e-06,3.475413e-06,7.729852e-06,1.343589e-05,1.946102e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
38537,8.0,112.0,1.733990e-05,8.617566e-06,8.186340e-06,7.375529e-06,1.118752e-05,2.131943e-05,3.243146e-05,4.727234e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
42491,9.0,195.0,5.269222e-04,5.719279e-04,3.840316e-04,2.879279e-04,4.813612e-04,7.323661e-04,8.927496e-04,9.075599e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7738,8.0,127.0,3.383180e-05,1.105955e-05,9.207179e-06,1.083626e-05,2.710822e-05,5.617857e-05,8.322671e-05,1.062075e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17724,19.0,335.0,3.499369e-04,2.344704e-04,5.634244e-04,4.817165e-04,3.426757e-04,2.574041e-04,1.879761e-04,1.382975e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
59243,29.0,582.0,1.481062e-06,1.493442e-06,1.138628e-06,1.043128e-06,1.241219e-06,1.645710e-06,2.358652e-06,2.829439e-06,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
86296,29.0,555.0,3.651126e-06,2.421798e-06,2.689517e-06,3.387098e-06,6.073697e-06,5.635312e-06,3.158908e-06,1.311204e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
78833,21.0,398.0,6.892972e-05,1.574169e-04,1.584852e-04,6.147092e-05,2.937551e-05,1.246750e-05,5.222729e-06,2.691418e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49954,21.0,387.0,2.973901e-07,1.816349e-07,1.766836e-07,1.963535e-07,3.309917e-07,3.740251e-07,5.475441e-07,4.140643e-07,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
71182,10.0,236.0,8.538923e-08,6.054496e-08,7.852604e-08,7.363257e-08,1.654958e-08,7.480502e-08,2.527127e-07,1.380214e-07,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13890,12.0,255.0,9.952262e-07,3.350154e-06,1.963151e-06,6.381489e-07,2.151446e-07,7.480502e-08,1.263563e-07,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
20533,21.0,394.0,8.459423e-06,6.720490e-06,4.574142e-06,3.595724e-06,5.643408e-06,9.176083e-06,1.436250e-05,2.235947e-05,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
75618,19.0,330.0,5.211688e-07,3.632697e-07,1.001207e-06,6.136047e-07,5.792354e-07,3.989601e-07,2.527127e-07,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14260,13.0,263.0,8.538923e-07,4.641780e-07,2.944727e-07,2.086256e-07,3.475413e-07,8.727252e-07,2.021701e-06,3.243503e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
82270,24.0,470.0,9.481149e-07,2.825431e-07,5.693138e-07,5.767884e-07,1.208120e-06,1.545970e-06,1.474157e-06,2.139332e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
63370,1.0,3.0,1.981619e-06,2.986885e-06,1.668678e-06,1.129033e-06,1.026074e-06,1.595840e-06,1.558395e-06,3.519546e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
81840,23.0,461.0,1.626223e-05,1.210899e-05,1.201448e-05,9.707227e-06,1.555661e-05,2.323943e-05,3.028340e-05,2.960560e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
65615,8.0,104.0,1.647129e-05,3.773969e-06,3.141042e-06,6.221952e-06,1.741016e-05,3.263992e-05,4.127640e-05,4.561608e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
77655,21.0,373.0,1.048226e-06,1.049446e-06,4.907878e-07,4.295233e-07,6.950825e-07,1.371425e-06,1.642632e-06,3.726578e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
79683,22.0,416.0,3.899932e-05,3.043393e-05,3.496372e-05,3.634994e-05,5.059208e-05,5.241338e-05,4.704668e-05,2.953658e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
56088,27.0,516.0,4.675797e-05,1.913221e-05,2.308666e-05,4.179875e-05,8.107641e-05,7.986683e-05,5.745001e-05,3.761084e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38408,8.0,109.0,1.295561e-06,5.650863e-07,4.122617e-07,5.154280e-07,7.612809e-07,2.019736e-06,3.158908e-06,3.657568e-06,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [151]:
y_train = df_train.pop('total_survival_rate')
X_train = df_train

In [152]:
y_train = y_train.to_frame()
y_train

       total_survival_rate
37616             0.787879
57980             0.818032
51058             0.812319
56305             0.923777
53120             0.833333
54511             0.947712
17978             0.947293
40042             0.804068
15119             0.845767
70263             0.856655
50804             0.891664
25806             0.902894
82842             0.935053
32069             0.840140
54800             1.000000
69491             0.921212
76273             0.937449
64946             1.000000
36738             0.828959
30816             0.884501
88029             0.916035
47550             0.928255
78021             0.772679
37033             0.915621
5461              0.930785
28892             0.929526
40260             0.840568
9245              0.861732
38100             0.900212
5984              0.921447
...                    ...
35981             0.944923
21377             0.826483
27039             0.933154
30596             0.794394
83820             0.933283
71323             0.933333
84354             0.885587
6230              0.932030
80989             0.803082
38537             0.807407
42491             0.871357
7738              0.858279
17724             0.943109
59243             0.883792
86296             0.920156
78833             0.865512
49954             0.792105
71182             0.893805
13890             0.908772
20533             0.802937
75618             0.920765
14260             0.773547
82270             0.894029
63370             0.767911
81840             0.817897
65615             0.879021
77655             0.782764
79683             0.868351
56088             0.929857
38408             0.852956

[63051 rows x 1 columns]

In [153]:
X_train

,state_code,distt._code,total_ever_married_women_x,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,...,present_age_60-64,present_age_65-69,present_age_70-74,present_age_75-79,present_age_80+,present_age_all_ages,present_age_less_than_15,all/sc/st_all,all/sc/st_sc,all/sc/st_st
37616,7.0,92.0,4.711130e-08,0.000000e+00,3.926302e-08,1.227209e-08,3.309917e-08,4.987001e-08,8.423756e-08,0.000000e+00,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
57980,29.0,556.0,8.332811e-06,6.720490e-06,4.358195e-06,2.748949e-06,4.931776e-06,9.126213e-06,1.516276e-05,2.229046e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
51058,22.0,410.0,1.057060e-06,8.678111e-07,9.815756e-07,3.804349e-07,8.771279e-07,1.097140e-06,1.600514e-06,2.967461e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
56305,27.0,521.0,3.239991e-04,3.400407e-04,3.037976e-04,3.651439e-04,3.972231e-04,3.260502e-04,2.418881e-04,1.824643e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
53120,23.0,454.0,8.421145e-07,4.056512e-06,9.815756e-07,1.840814e-07,2.316942e-07,1.745450e-07,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
54511,24.0,483.0,7.243362e-07,3.350154e-06,1.766836e-07,8.835908e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
17978,19.0,341.0,5.769839e-04,6.082750e-04,1.423618e-03,7.651651e-04,3.316537e-04,1.651695e-04,8.196314e-05,4.948068e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40042,9.0,143.0,1.062949e-06,8.274478e-07,6.871029e-07,4.540675e-07,6.950825e-07,1.396360e-06,1.768989e-06,3.105482e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
15119,15.0,281.0,3.433236e-06,1.130173e-06,9.226810e-07,9.817676e-07,2.465888e-06,6.009337e-06,8.465874e-06,1.062765e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
70263,10.0,216.0,2.767789e-07,2.623615e-07,2.355781e-07,1.595372e-07,2.978925e-07,4.737651e-07,2.527127e-07,4.140643e-07,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
50804,22.0,405.0,3.095507e-05,2.744705e-05,2.787675e-05,2.297336e-05,3.108012e-05,4.012043e-05,4.072886e-05,4.271763e-05,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
25806,27.0,504.0,7.168279e-05,2.159437e-05,2.756264e-05,5.809610e-05,1.582637e-04,1.250740e-04,6.877997e-05,4.085434e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
82842,24.0,482.0,2.564621e-06,1.997984e-06,2.375413e-06,2.834854e-06,3.409214e-06,2.767786e-06,2.316533e-06,2.001311e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32069,34.0,636.0,1.107116e-06,5.650863e-07,7.459974e-07,4.908838e-07,7.778304e-07,8.477902e-07,1.853226e-06,3.174493e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
54800,24.0,489.0,6.477804e-08,1.816349e-07,1.766836e-07,2.454419e-08,4.964875e-08,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
69491,9.0,198.0,1.030560e-07,0.000000e+00,0.000000e+00,4.908838e-08,1.158471e-07,2.493501e-07,1.684751e-07,4.140643e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
76273,19.0,344.0,2.997456e-06,5.832498e-06,7.420711e-06,3.252105e-06,1.026074e-06,2.493501e-07,2.105939e-07,2.070321e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
64946,5.0,59.0,8.833369e-09,0.000000e+00,3.926302e-08,0.000000e+00,1.654958e-08,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
36738,6.0,74.0,8.247422e-06,2.643796e-06,2.237992e-06,1.889903e-06,4.203594e-06,9.899198e-06,1.819531e-05,2.753527e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
30816,33.0,610.0,1.683463e-04,1.015743e-04,1.793927e-04,2.342988e-04,2.152935e-04,1.543477e-04,1.157003e-04,7.798210e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88029,32.0,592.0,2.026080e-05,2.367308e-05,2.251734e-05,1.779454e-05,2.091867e-05,1.974853e-05,1.768989e-05,1.745971e-05,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
47550,19.0,337.0,1.208552e-04,4.056512e-05,8.453329e-05,1.712816e-04,1.962284e-04,1.416059e-04,8.385849e-05,5.023980e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
78021,21.0,381.0,8.126699e-07,8.274478e-07,5.104193e-07,4.663396e-07,7.116321e-07,1.022335e-06,1.516276e-06,1.656257e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
37033,6.0,80.0,3.098157e-05,5.786080e-05,6.961334e-05,3.476684e-05,1.557316e-05,5.485702e-06,2.274414e-06,1.311204e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5461,6.0,79.0,1.039275e-04,3.878914e-05,8.359097e-05,1.752332e-04,1.465466e-04,9.398004e-05,5.757637e-05,3.222800e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28892,29.0,569.0,4.003577e-05,3.535826e-05,7.416785e-05,7.344849e-05,2.434444e-05,9.699718e-06,4.675184e-06,3.519546e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
40260,9.0,148.0,1.549962e-05,5.327956e-06,4.358195e-06,4.098880e-06,9.317416e-06,2.111995e-05,3.563249e-05,5.369033e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9245,9.0,158.0,5.011465e-06,4.520690e-06,3.455146e-06,2.307154e-06,3.607809e-06,5.809857e-06,8.718587e-06,9.799521e-06,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
38100,8.0,103.0,2.254276e-05,3.995967e-06,4.927509e-06,1.167076e-05,3.405904e-05,4.523210e-05,5.007923e-05,4.437389e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5984,7.0,90.0,1.623809e-04,1.102927e-04,1.410720e-04,1.665814e-04,1.962284e-04,1.895061e-04,1.800157e-04,1.670059e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35981,5.0,58.0,5.376577e-06,8.213933e-06,1.154333e-05,6.577843e-06,3.624359e-06,1.396360e-06,4.211878e-07,2.760428e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
21377,22.0,412.0,3.775382e-05,1.509588e-05,1.230896e-05,1.428472e-05,3.483687e-05,6.657647e-05,9.632565e-05,1.068286e-04,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27039,27.0,530.0,8.543929e-05,4.809288e-05,7.116423e-05,1.118601e-04,1.366996e-04,9.111252e-05,5.311178e-05,2.677616e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
30596,33.0,605.0,3.223591e-05,3.622607e-05,2.031861e-05,1.536466e-05,2.273913e-05,3.745238e-05,5.993502e-05,7.466959e-05,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
83820,27.0,503.0,3.986205e-05,2.766905e-05,3.751582e-05,5.866061e-05,5.845313e-05,3.465966e-05,1.587878e-05,6.279975e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
71323,10.0,239.0,1.472228e-08,0.000000e+00,1.963151e-08,4.908838e-08,0.000000e+00,0.000000e+00,0.000000e+00,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
84354,27.0,514.0,2.037564e-06,1.190718e-06,8.048920e-07,9.694955e-07,2.283843e-06,3.017136e-06,4.085522e-06,5.244814e-06,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6230,7.0,96.0,2.752124e-04,9.323924e-05,2.717983e-04,4.441394e-04,3.372640e-04,2.613189e-04,1.847751e-04,1.228391e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
80989,23.0,443.0,4.996742e-06,1.553987e-06,1.060102e-06,1.251754e-06,3.475413e-06,7.729852e-06,1.343589e-05,1.946102e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
38537,8.0,112.0,1.733990e-05,8.617566e-06,8.186340e-06,7.375529e-06,1.118752e-05,2.131943e-05,3.243146e-05,4.727234e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
42491,9.0,195.0,5.269222e-04,5.719279e-04,3.840316e-04,2.879279e-04,4.813612e-04,7.323661e-04,8.927496e-04,9.075599e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7738,8.0,127.0,3.383180e-05,1.105955e-05,9.207179e-06,1.083626e-05,2.710822e-05,5.617857e-05,8.322671e-05,1.062075e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17724,19.0,335.0,3.499369e-04,2.344704e-04,5.634244e-04,4.817165e-04,3.426757e-04,2.574041e-04,1.879761e-04,1.382975e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
59243,29.0,582.0,1.481062e-06,1.493442e-06,1.138628e-06,1.043128e-06,1.241219e-06,1.645710e-06,2.358652e-06,2.829439e-06,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
86296,29.0,555.0,3.651126e-06,2.421798e-06,2.689517e-06,3.387098e-06,6.073697e-06,5.635312e-06,3.158908e-06,1.311204e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
78833,21.0,398.0,6.892972e-05,1.574169e-04,1.584852e-04,6.147092e-05,2.937551e-05,1.246750e-05,5.222729e-06,2.691418e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49954,21.0,387.0,2.973901e-07,1.816349e-07,1.766836e-07,1.963535e-07,3.309917e-07,3.740251e-07,5.475441e-07,4.140643e-07,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
71182,10.0,236.0,8.538923e-08,6.054496e-08,7.852604e-08,7.363257e-08,1.654958e-08,7.480502e-08,2.527127e-07,1.380214e-07,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13890,12.0,255.0,9.952262e-07,3.350154e-06,1.963151e-06,6.381489e-07,2.151446e-07,7.480502e-08,1.263563e-07,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
20533,21.0,394.0,8.459423e-06,6.720490e-06,4.574142e-06,3.595724e-06,5.643408e-06,9.176083e-06,1.436250e-05,2.235947e-05,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
75618,19.0,330.0,5.211688e-07,3.632697e-07,1.001207e-06,6.136047e-07,5.792354e-07,3.989601e-07,2.527127e-07,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14260,13.0,263.0,8.538923e-07,4.641780e-07,2.944727e-07,2.086256e-07,3.475413e-07,8.727252e-07,2.021701e-06,3.243503e-06,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
82270,24.0,470.0,9.481149e-07,2.825431e-07,5.693138e-07,5.767884e-07,1.208120e-06,1.545970e-06,1.474157e-06,2.139332e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
63370,1.0,3.0,1.981619e-06,2.986885e-06,1.668678e-06,1.129033e-06,1.026074e-06,1.595840e-06,1.558395e-06,3.519546e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
81840,23.0,461.0,1.626223e-05,1.210899e-05,1.201448e-05,9.707227e-06,1.555661e-05,2.323943e-05,3.028340e-05,2.960560e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
65615,8.0,104.0,1.647129e-05,3.773969e-06,3.141042e-06,6.221952e-06,1.741016e-05,3.263992e-05,4.127640e-05,4.561608e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
77655,21.0,373.0,1.048226e-06,1.049446e-06,4.907878e-07,4.295233e-07,6.950825e-07,1.371425e-06,1.642632e-06,3.726578e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
79683,22.0,416.0,3.899932e-05,3.043393e-05,3.496372e-05,3.634994e-05,5.059208e-05,5.241338e-05,4.704668e-05,2.953658e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
56088,27.0,516.0,4.675797e-05,1.913221e-05,2.308666e-05,4.179875e-05,8.107641e-05,7.986683e-05,5.745001e-05,3.761084e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
38408,8.0,109.0,1.295561e-06,5.650863e-07,4.122617e-07,5.154280e-07,7.612809e-07,2.019736e-06,3.158908e-06,3.657568e-06,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [154]:
# Importing RFE and LinearRegression
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [155]:
# Running RFE with the output number of the variable equal to 10
lm = LinearRegression()
lm.fit(X_train, y_train)
# running RFE
rfe = RFE(lm, 15)
rfe = rfe.fit(X_train, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [156]:
list(zip(X_train.columns,rfe.support_,rfe.ranking_))

[('state_code', False, 723),
 ('distt._code', False, 724),
 ('total_ever_married_women_x', True, 1),
 ('parity_0', True, 1),
 ('parity_1', True, 1),
 ('parity_2', True, 1),
 ('parity_3', True, 1),
 ('parity_4', True, 1),
 ('parity_5', True, 1),
 ('parity_6', True, 1),
 ('parity_7+', True, 1),
 ('total_children_ever_born_p', True, 1),
 ('total_children_ever_born_m', True, 1),
 ('total_children_ever_born_f', True, 1),
 ('total_ever_unmarried_women_x', False, 722),
 ('parity_0_%', False, 4),
 ('parity_1_%', False, 6),
 ('parity_2_%', False, 16),
 ('parity_3_%', False, 162),
 ('parity_4_%', False, 18),
 ('parity_5_%', False, 13),
 ('parity_6_%', False, 12),
 ('parity_7+_%', False, 11),
 ('total_ever_married_women_%_x', False, 139),
 ('total_ever_unmarried_women_%_x', False, 15),
 ('total_children_ever_born_m_%', False, 185),
 ('total_children_ever_born_f_%', False, 19),
 ('no._of_surv._child._0', False, 718),
 ('no._of_surv._child._1', False, 716),
 ('no._of_surv._child._2', False, 720),
 ('no._of_surv._child._3', False, 719),
 ('no._of_surv._child._4', False, 721),
 ('no._of_surv._child._5+', False, 717),
 ('ttl_surv._child._p', True, 1),
 ('ttl_surv._child._m', True, 1),
 ('ttl_surv._child._f', True, 1),
 ('total_ever_unmarried_women_%_y', False, 14),
 ('total_ever_married_women_%_y', False, 17),
 ('ttl_surv._child._m_%', False, 9),
 ('ttl_surv._child._f_%', False, 8),
 ('no._of_surv._child._0_%', False, 10),
 ('no._of_surv._child._1_%', False, 210),
 ('no._of_surv._child._2_%', False, 2),
 ('no._of_surv._child._3_%', False, 3),
 ('no._of_surv._child._4_%', False, 5),
 ('no._of_surv._child._5+_%', False, 7),
 ('area_name_district_-_adilabad', False, 472),
 ('area_name_district_-_agra', False, 339),
 ('area_name_district_-_ahmadabad', False, 407),
 ('area_name_district_-_ahmadnagar', False, 546),
 ('area_name_district_-_aizawl', False, 616),
 ('area_name_district_-_ajmer', False, 189),
 ('area_name_district_-_akola', False, 280),
 ('area_name_district_-_alappuzha', False, 701),
 ('area_name_district_-_aligarh', False, 233),
 ('area_name_district_-_alirajpur', False, 137),
 ('area_name_district_-_allahabad', False, 100),
 ('area_name_district_-_almora\n', False, 598),
 ('area_name_district_-_alwar', False, 142),
 ('area_name_district_-_ambala', False, 612),
 ('area_name_district_-_ambedkar_nagar', False, 357),
 ('area_name_district_-_amravati', False, 349),
 ('area_name_district_-_amreli', False, 489),
 ('area_name_district_-_amritsar', False, 658),
 ('area_name_district_-_anand', False, 476),
 ('area_name_district_-_anantapur', False, 72),
 ('area_name_district_-_anantnag', False, 596),
 ('area_name_district_-_anjaw', False, 23),
 ('area_name_district_-_anugul', False, 235),
 ('area_name_district_-_anuppur', False, 86),
 ('area_name_district_-_araria', False, 352),
 ('area_name_district_-_ariyalur', False, 249),
 ('area_name_district_-_arwal', False, 28),
 ('area_name_district_-_ashoknagar', False, 34),
 ('area_name_district_-_auraiya', False, 355),
 ('area_name_district_-_aurangabad', False, 297),
 ('area_name_district_-_azamgarh', False, 459),
 ('area_name_district_-_badgam', False, 706),
 ('area_name_district_-_bagalkot', False, 319),
 ('area_name_district_-_bageshwar', False, 672),
 ('area_name_district_-_baghpat', False, 279),
 ('area_name_district_-_bahraich', False, 195),
 ('area_name_district_-_baksa', False, 161),
 ('area_name_district_-_balaghat', False, 268),
 ('area_name_district_-_balangir', False, 177),
 ('area_name_district_-_baleshwar', False, 291),
 ('area_name_district_-_ballia', False, 500),
 ('area_name_district_-_balrampur', False, 216),
 ('area_name_district_-_banas_kantha', False, 618),
 ('area_name_district_-_banda', False, 237),
 ('area_name_district_-_bandipore', False, 609),
 ('area_name_district_-_bangalore', False, 460),
 ('area_name_district_-_bangalore_rural', False, 371),
 ('area_name_district_-_banka', False, 440),
 ('area_name_district_-_bankura', False, 626),
 ('area_name_district_-_banswara', False, 119),
 ('area_name_district_-_bara_banki', False, 342),
 ('area_name_district_-_baramula', False, 649),
 ('area_name_district_-_baran', False, 75),
 ('area_name_district_-_barddhaman', False, 462),
 ('area_name_district_-_bareilly', False, 102),
 ('area_name_district_-_bargarh', False, 478),
 ('area_name_district_-_barmer', False, 515),
 ('area_name_district_-_barnala', False, 392),
 ('area_name_district_-_barpeta', False, 362),
 ('area_name_district_-_barwani', False, 293),
 ('area_name_district_-_bastar', False, 186),
 ('area_name_district_-_basti', False, 387),
 ('area_name_district_-_bathinda', False, 630),
 ('area_name_district_-_baudh', False, 232),
 ('area_name_district_-_begusarai', False, 274),
 ('area_name_district_-_belgaum', False, 529),
 ('area_name_district_-_bellary', False, 145),
 ('area_name_district_-_betul', False, 152),
 ('area_name_district_-_bhadrak', False, 135),
 ('area_name_district_-_bhagalpur', False, 467),
 ('area_name_district_-_bhandara', False, 435),
 ('area_name_district_-_bharatpur', False, 258),
 ('area_name_district_-_bharuch', False, 419),
 ('area_name_district_-_bhavnagar', False, 682),
 ('area_name_district_-_bhilwara', False, 132),
 ('area_name_district_-_bhind', False, 277),
 ('area_name_district_-_bhiwani', False, 301),
 ('area_name_district_-_bhojpur', False, 318),
 ('area_name_district_-_bhopal', False, 74),
 ('area_name_district_-_bid', False, 663),
 ('area_name_district_-_bidar', False, 611),
 ('area_name_district_-_bijapur', False, 282),
 ('area_name_district_-_bijnor', False, 104),
 ('area_name_district_-_bikaner', False, 594),
 ('area_name_district_-_bilaspur', False, 374),
 ('area_name_district_-_birbhum', False, 343),
 ('area_name_district_-_bishnupur', False, 691),
 ('area_name_district_-_bokaro', False, 221),
 ('area_name_district_-_bongaigaon', False, 526),
 ('area_name_district_-_budaun', False, 194),
 ('area_name_district_-_bulandshahr', False, 270),
 ('area_name_district_-_buldana', False, 528),
 ('area_name_district_-_bundi', False, 193),
 ('area_name_district_-_burhanpur', False, 365),
 ('area_name_district_-_buxar', False, 175),
 ('area_name_district_-_cachar', False, 571),
 ('area_name_district_-_central', False, 579),
 ('area_name_district_-_chamarajanagar', False, 524),
 ('area_name_district_-_chamba', False, 307),
 ('area_name_district_-_chamoli', False, 518),
 ('area_name_district_-_champawat', False, 223),
 ('area_name_district_-_champhai', False, 638),
 ('area_name_district_-_chandauli', False, 393),
 ('area_name_district_-_chandel', False, 650),
 ('area_name_district_-_chandigarh', False, 523),
 ('area_name_district_-_chandrapur', False, 267),
 ('area_name_district_-_changlang', False, 395),
 ('area_name_district_-_chatra', False, 184),
 ('area_name_district_-_chennai', False, 463),
 ('area_name_district_-_chhatarpur', False, 32),
 ('area_name_district_-_chhindwara', False, 180),
 ('area_name_district_-_chikkaballapura', False, 313),
 ('area_name_district_-_chikmagalur', False, 396),
 ('area_name_district_-_chirang', False, 490),
 ('area_name_district_-_chitradurga', False, 436),
 ('area_name_district_-_chitrakoot', False, 445),
 ('area_name_district_-_chittaurgarh', False, 252),
 ('area_name_district_-_chittoor', False, 372),
 ('area_name_district_-_churachandpur', False, 614),
 ('area_name_district_-_churu', False, 509),
 ('area_name_district_-_coimbatore', False, 480),
 ('area_name_district_-_cuddalore', False, 464),
 ('area_name_district_-_cuttack', False, 49),
 ('area_name_district_-_dadra_&_nagar_haveli', False, 685),
 ('area_name_district_-_dakshin_bastar_dantewada', False, 94),
 ('area_name_district_-_dakshin_dinajpur', False, 106),
 ('area_name_district_-_dakshina_kannada', False, 677),
 ('area_name_district_-_daman', False, 699),
 ('area_name_district_-_damoh', False, 87),
 ('area_name_district_-_darbhanga', False, 155),
 ('area_name_district_-_darjiling', False, 536),
 ('area_name_district_-_darrang', False, 338),
 ('area_name_district_-_datia', False, 40),
 ('area_name_district_-_dausa', False, 143),
 ('area_name_district_-_davanagere', False, 488),
 ('area_name_district_-_debagarh', False, 129),
 ('area_name_district_-_dehradun', False, 418),
 ('area_name_district_-_deoghar', False, 306),
 ('area_name_district_-_deoria', False, 315),
 ('area_name_district_-_dewas', False, 147),
 ('area_name_district_-_dhalai', False, 116),
 ('area_name_district_-_dhamtari', False, 344),
 ('area_name_district_-_dhanbad', False, 409),
 ('area_name_district_-_dhar', False, 354),
 ('area_name_district_-_dharmapuri', False, 428),
 ('area_name_district_-_dharwad', False, 438),
 ('area_name_district_-_dhaulpur', False, 288),
 ('area_name_district_-_dhemaji', False, 562),
 ('area_name_district_-_dhenkanal', False, 42),
 ('area_name_district_-_dhubri', False, 130),
 ('area_name_district_-_dhule', False, 368),
 ('area_name_district_-_dibang_valley', False, 70),
 ('area_name_district_-_dibrugarh', False, 659),
 ('area_name_district_-_dima_hasao', False, 544),
 ('area_name_district_-_dimapur', False, 402),
 ('area_name_district_-_dindigul', False, 95),
 ('area_name_district_-_dindori', False, 97),
 ('area_name_district_-_diu', False, 688),
 ('area_name_district_-_doda', False, 628),
 ('area_name_district_-_dohad', False, 585),
 ('area_name_district_-_dumka', False, 85),
 ('area_name_district_-_dungarpur', False, 479),
 ('area_name_district_-_durg', False, 257),
 ('area_name_district_-_east', False, 391),
 ('area_name_district_-_east_district', False, 456),
 ('area_name_district_-_east_garo_hills', False, 530),
 ('area_name_district_-_east_godavari', False, 429),
 ('area_name_district_-_east_kameng', False, 20),
 ('area_name_district_-_east_khasi_hills', False, 122),
 ('area_name_district_-_east_siang', False, 642),
 ('area_name_district_-_ernakulam', False, 711),
 ('area_name_district_-_erode', False, 412),
 ('area_name_district_-_etah', False, 340),
 ('area_name_district_-_etawah', False, 211),
 ('area_name_district_-_faizabad', False, 708),
 ('area_name_district_-_faridabad', False, 281),
 ('area_name_district_-_faridkot', False, 525),
 ('area_name_district_-_farrukhabad', False, 360),
 ('area_name_district_-_fatehabad', False, 302),
 ('area_name_district_-_fatehgarh_sahib', False, 501),
 ('area_name_district_-_fatehpur', False, 138),
 ('area_name_district_-_firozabad', False, 437),
 ('area_name_district_-_firozpur', False, 590),
 ('area_name_district_-_gadag', False, 246),
 ('area_name_district_-_gadchiroli', False, 347),
 ('area_name_district_-_gajapati', False, 30),
 ('area_name_district_-_ganderbal', False, 498),
 ('area_name_district_-_gandhinagar', False, 610),
 ('area_name_district_-_ganganagar', False, 541),
 ('area_name_district_-_ganjam', False, 33),
 ('area_name_district_-_garhwa', False, 183),
 ('area_name_district_-_garhwal', False, 263),
 ('area_name_district_-_gautam_buddha_nagar', False, 259),
 ('area_name_district_-_gaya', False, 254),
 ('area_name_district_-_ghaziabad', False, 134),
 ('area_name_district_-_ghazipur', False, 231),
 ('area_name_district_-_giridih', False, 364),
 ('area_name_district_-_goalpara', False, 451),
 ('area_name_district_-_godda', False, 133),
 ('area_name_district_-_golaghat', False, 654),
 ('area_name_district_-_gonda', False, 474),
 ('area_name_district_-_gondiya', False, 397),
 ('area_name_district_-_gopalganj', False, 348),
 ('area_name_district_-_gorakhpur', False, 247),
 ('area_name_district_-_gulbarga', False, 465),
 ('area_name_district_-_gumla', False, 271),
 ('area_name_district_-_guna', False, 53),
 ('area_name_district_-_guntur', False, 619),
 ('area_name_district_-_gurdaspur', False, 668),
 ('area_name_district_-_gurgaon', False, 394),
 ('area_name_district_-_gwalior', False, 141),
 ('area_name_district_-_hailakandi', False, 325),
 ('area_name_district_-_hamirpur', False, 615),
 ('area_name_district_-_hanumangarh', False, 148),
 ('area_name_district_-_haora', False, 532),
 ('area_name_district_-_harda', False, 125),
 ('area_name_district_-_hardoi', False, 115),
 ('area_name_district_-_hardwar', False, 192),
 ('area_name_district_-_hassan', False, 597),
 ('area_name_district_-_haveri', False, 455),
 ('area_name_district_-_hazaribagh', False, 334),
 ('area_name_district_-_hingoli', False, 607),
 ('area_name_district_-_hisar', False, 283),
 ('area_name_district_-_hoshangabad', False, 69),
 ('area_name_district_-_hoshiarpur', False, 678),
 ('area_name_district_-_hugli', False, 582),
 ('area_name_district_-_hyderabad', False, 651),
 ('area_name_district_-_idukki', False, 666),
 ('area_name_district_-_imphal_east', False, 632),
 ('area_name_district_-_imphal_west', False, 689),
 ('area_name_district_-_indore', False, 386),
 ('area_name_district_-_jabalpur', False, 99),
 ('area_name_district_-_jagatsinghapur', False, 381),
 ('area_name_district_-_jaintia_hills', False, 48),
 ('area_name_district_-_jaipur', False, 330),
 ('area_name_district_-_jaisalmer', False, 617),
 ('area_name_district_-_jajapur', False, 327),
 ('area_name_district_-_jalandhar', False, 625),
 ('area_name_district_-_jalaun', False, 477),
 ('area_name_district_-_jalgaon', False, 449),
 ('area_name_district_-_jalna', False, 502),
 ('area_name_district_-_jalor', False, 508),
 ('area_name_district_-_jalpaiguri', False, 390),
 ('area_name_district_-_jammu', False, 683),
 ('area_name_district_-_jamnagar', False, 608),
 ('area_name_district_-_jamtara', False, 105),
 ('area_name_district_-_jamui', False, 222),
 ('area_name_district_-_janjgir_-_champa', False, 369),
 ('area_name_district_-_jashpur', False, 495),
 ('area_name_district_-_jaunpur', False, 255),
 ('area_name_district_-_jehanabad', False, 68),
 ('area_name_district_-_jhabua', False, 309),
 ('area_name_district_-_jhajjar', False, 425),
 ('area_name_district_-_jhalawar', False, 160),
 ('area_name_district_-_jhansi', False, 403),
 ('area_name_district_-_jharsuguda', False, 248),
 ('area_name_district_-_jhunjhunun', False, 589),
 ('area_name_district_-_jind', False, 238),
 ('area_name_district_-_jodhpur', False, 439),
 ('area_name_district_-_jorhat', False, 687),
 ('area_name_district_-_junagadh', False, 545),
 ('area_name_district_-_jyotiba_phule_nagar', False, 312),
 ('area_name_district_-_kabeerdham', False, 123),
 ('area_name_district_-_kachchh', False, 278),
 ('area_name_district_-_kaimur_(bhabua)', False, 110),
 ('area_name_district_-_kaithal', False, 191),
 ('area_name_district_-_kalahandi', False, 79),
 ('area_name_district_-_kamrup', False, 504),
 ('area_name_district_-_kamrup_metropolitan', False, 581),
 ('area_name_district_-_kancheepuram', False, 292),
 ('area_name_district_-_kandhamal', False, 36),
 ('area_name_district_-_kangra', False, 584),
 ('area_name_district_-_kannauj', False, 264),
 ('area_name_district_-_kanniyakumari', False, 652),
 ('area_name_district_-_kannur', False, 692),
 ('area_name_district_-_kanpur_dehat', False, 107),
 ('area_name_district_-_kanpur_nagar', False, 173),
 ('area_name_district_-_kanshiram_nagar', False, 131),
 ('area_name_district_-_kapurthala', False, 559),
 ('area_name_district_-_karaikal', False, 639),
 ('area_name_district_-_karauli', False, 182),
 ('area_name_district_-_karbi_anglong', False, 296),
 ('area_name_district_-_kargil', False, 26),
 ('area_name_district_-_karimganj', False, 294),
 ('area_name_district_-_karimnagar', False, 645),
 ('area_name_district_-_karnal', False, 323),
 ('area_name_district_-_karur', False, 572),
 ('area_name_district_-_kasaragod', False, 671),
 ('area_name_district_-_kathua', False, 676),
 ('area_name_district_-_katihar', False, 215),
 ('area_name_district_-_katni', False, 80),
 ('area_name_district_-_kaushambi', False, 35),
 ('area_name_district_-_kendrapara', False, 285),
 ('area_name_district_-_kendujhar', False, 289),
 ('area_name_district_-_khagaria', False, 146),
 ('area_name_district_-_khammam', False, 337),
 ('area_name_district_-_khandwa_(east_nimar)', False, 174),
 ('area_name_district_-_khargone_(west_nimar)', False, 329),
 ('area_name_district_-_kheda', False, 447),
 ('area_name_district_-_kheri', False, 77),
 ('area_name_district_-_khordha', False, 71),
 ('area_name_district_-_khunti', False, 103),
 ('area_name_district_-_kinnaur', False, 76),
 ('area_name_district_-_kiphire', False, 214),
 ('area_name_district_-_kishanganj', False, 346),
 ('area_name_district_-_kishtwar', False, 506),
 ('area_name_district_-_koch_bihar', False, 414),
 ('area_name_district_-_kodagu', False, 613),
 ('area_name_district_-_kodarma', False, 588),
 ('area_name_district_-_kohima', False, 710),
 ('area_name_district_-_kokrajhar', False, 433),
 ('area_name_district_-_kolar', False, 599),
 ('area_name_district_-_kolasib', False, 686),
 ('area_name_district_-_kolhapur', False, 563),
 ('area_name_district_-_kolkata', False, 379),
 ('area_name_district_-_kollam', False, 704),
 ('area_name_district_-_koppal', False, 164),
 ('area_name_district_-_koraput', False, 52),
 ('area_name_district_-_korba', False, 384),
 ('area_name_district_-_koriya', False, 224),
 ('area_name_district_-_kota', False, 351),
 ('area_name_district_-_kottayam', False, 698),
 ('area_name_district_-_kozhikode', False, 531),
 ('area_name_district_-_krishna', False, 388),
 ('area_name_district_-_krishnagiri', False, 401),
 ('area_name_district_-_kulgam', False, 304),
 ('area_name_district_-_kullu', False, 540),
 ('area_name_district_-_kupwara', False, 602),
 ('area_name_district_-_kurnool', False, 242),
 ('area_name_district_-_kurukshetra', False, 629),
 ('area_name_district_-_kurung_kumey', False, 21),
 ('area_name_district_-_kushinagar', False, 57),
 ('area_name_district_-_lahul_&_spiti', False, 276),
 ('area_name_district_-_lakhimpur', False, 513),
 ('area_name_district_-_lakhisarai', False, 153),
 ('area_name_district_-_lakshadweep', False, 316),
 ('area_name_district_-_lalitpur', False, 56),
 ('area_name_district_-_latehar', False, 240),
 ('area_name_district_-_latur', False, 534),
 ('area_name_district_-_lawngtlai', False, 516),
 ('area_name_district_-_leh(ladakh)', False, 239),
 ('area_name_district_-_lohardaga', False, 341),
 ('area_name_district_-_lohit', False, 586),
 ('area_name_district_-_longleng', False, 457),
 ('area_name_district_-_lower_dibang_valley', False, 118),
 ('area_name_district_-_lower_subansiri', False, 519),
 ('area_name_district_-_lucknow', False, 209),
 ('area_name_district_-_ludhiana', False, 627),
 ('area_name_district_-_lunglei', False, 512),
 ('area_name_district_-_madhepura', False, 448),
 ('area_name_district_-_madhubani', False, 537),
 ('area_name_district_-_madurai', False, 234),
 ('area_name_district_-_mahamaya_nagar', False, 273),
 ('area_name_district_-_mahasamund', False, 225),
 ('area_name_district_-_mahbubnagar', False, 322),
 ('area_name_district_-_mahe', False, 695),
 ('area_name_district_-_mahendragarh', False, 300),
 ('area_name_district_-_mahesana', False, 580),
 ('area_name_district_-_mahoba', False, 149),
 ('area_name_district_-_mahrajganj', False, 39),
 ('area_name_district_-_mainpuri', False, 178),
 ('area_name_district_-_malappuram', False, 664),
 ('area_name_district_-_maldah', False, 150),
 ('area_name_district_-_malkangiri', False, 158),
 ('area_name_district_-_mamit', False, 423),
 ('area_name_district_-_mandi', False, 578),
 ('area_name_district_-_mandla', False, 117),
 ('area_name_district_-_mandsaur', False, 290),
 ('area_name_district_-_mandya', False, 557),
 ('area_name_district_-_mansa', False, 400),
 ('area_name_district_-_mathura', False, 212),
 ('area_name_district_-_mau', False, 442),
 ('area_name_district_-_mayurbhanj', False, 444),
 ('area_name_district_-_medak', False, 366),
 ('area_name_district_-_meerut', False, 461),
 ('area_name_district_-_mewat', False, 140),
 ('area_name_district_-_mirzapur', False, 190),
 ('area_name_district_-_moga', False, 622),
 ('area_name_district_-_mokokchung', False, 575),
 ('area_name_district_-_mon', False, 603),
 ('area_name_district_-_moradabad', False, 443),
 ('area_name_district_-_morena', False, 219),

In [157]:
col = X_train.columns[rfe.support_]
col

Index(['total_ever_married_women_x', 'parity_0', 'parity_1', 'parity_2',
       'parity_3', 'parity_4', 'parity_5', 'parity_6', 'parity_7+',
       'total_children_ever_born_p', 'total_children_ever_born_m',
       'total_children_ever_born_f', 'ttl_surv._child._p',
       'ttl_surv._child._m', 'ttl_surv._child._f'],
      dtype='object')

In [158]:
X_train.columns[~rfe.support_]

Index(['state_code', 'distt._code', 'total_ever_unmarried_women_x',
       'parity_0_%', 'parity_1_%', 'parity_2_%', 'parity_3_%', 'parity_4_%',
       'parity_5_%', 'parity_6_%',
       ...
       'present_age_60-64', 'present_age_65-69', 'present_age_70-74',
       'present_age_75-79', 'present_age_80+', 'present_age_all_ages',
       'present_age_less_than_15', 'all/sc/st_all', 'all/sc/st_sc',
       'all/sc/st_st'],
      dtype='object', length=723)

In [159]:
# Creating X_test dataframe with RFE selected variables
X_train_rfe = X_train[col]

In [160]:
# Adding a constant variable 
import statsmodels.api as sm  
X_train_rfe = sm.add_constant(X_train_rfe)

In [161]:
# Running the linear model
lm = sm.OLS(y_train,X_train_rfe).fit()

In [162]:
lm.params

const                           0.883804
total_ever_married_women_x     40.225082
parity_0                       -3.144806
parity_1                       12.883198
parity_2                       45.084793
parity_3                       92.059960
parity_4                        5.709820
parity_5                      101.748284
parity_6                       -1.251668
parity_7+                      68.720986
total_children_ever_born_p   -171.697603
total_children_ever_born_m   -288.680822
total_children_ever_born_f    -40.323934
ttl_surv._child._p             49.723221
ttl_surv._child._m            128.340060
ttl_surv._child._f            -39.247750
dtype: float64

In [176]:
#Let's see the summary of our linear model
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     total_survival_rate   R-squared:                       0.003
Model:                             OLS   Adj. R-squared:                  0.003
Method:                  Least Squares   F-statistic:                     17.38
Date:                 Mon, 10 Aug 2020   Prob (F-statistic):           6.33e-38
Time:                         15:19:29   Log-Likelihood:                 84649.
No. Observations:                63051   AIC:                        -1.693e+05
Df Residuals:                    63038   BIC:                        -1.692e+05
Df Model:                           12
Covariance Type:             nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                          0.8838      0.000   3508.816      0.000       0.883       0.884
total_ever_married_women_x    40.2251     18.869      2.132      0.033       3.242      77.208
parity_0                      -3.1448      2.833     -1.110      0.267      -8.697       2.407
parity_1                      12.8832      6.353      2.028      0.043       0.431      25.335
parity_2                      45.0848     25.976      1.736      0.083      -5.828      95.998
parity_3                      92.0600     28.873      3.188      0.001      35.469     148.651
parity_4                       5.7098     30.854      0.185      0.853     -54.765      66.185
parity_5                     101.7483     24.956      4.077      0.000      52.834     150.662
parity_6                      -1.2517     13.345     -0.094      0.925     -27.408      24.904
parity_7+                     68.7210     30.605      2.245      0.025       8.735     128.707
total_children_ever_born_p  -171.6976     58.089     -2.956      0.003    -285.552     -57.843
total_children_ever_born_m  -288.6808     74.510     -3.874      0.000    -434.720    -142.641
total_children_ever_born_f   -40.3239     52.192     -0.773      0.440    -142.620      61.972
ttl_surv._child._p            49.7232      5.443      9.135      0.000      39.055      60.392
ttl_surv._child._m           128.3401     24.856      5.163      0.000      79.622     177.058
ttl_surv._child._f           -39.2477     22.709     -1.728      0.084     -83.757       5.262
==============================================================================
Omnibus:                    34438.828   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           858007.372
Skew:                          -2.131   Prob(JB):                         0.00
Kurtosis:                      20.562   Cond. No.                     3.33e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.7e-33. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [177]:
# Calculate the VIFs for the new model
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
X = X_train_rfe
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

                      Features       VIF
1   total_ever_married_women_x       inf
2                     parity_0       inf
3                     parity_1       inf
4                     parity_2       inf
5                     parity_3       inf
6                     parity_4       inf
7                     parity_5       inf
8                     parity_6       inf
9                    parity_7+       inf
10  total_children_ever_born_p       inf
11  total_children_ever_born_m       inf
12  total_children_ever_born_f       inf
13          ttl_surv._child._p       inf
14          ttl_surv._child._m       inf
15          ttl_surv._child._f       inf
0                        const  0.000000

In [165]:
X_train_new = X_train_rfe.drop(["total_ever_married_women_%_x"], axis = 1)

KeyError: "['total_ever_married_women_%_x'] not found in axis"

In [ ]:
# Adding a constant variable 
X_train_new_1 = sm.add_constant(X_train_new)

In [ ]:
# Running the linear model
lm_1 = sm.OLS(y_train,X_train_new_1).fit()

In [ ]:
lm_1.params

In [ ]:
#Let's see the summary of our linear model
lm_1.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_1
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_1 = X_train_new_1.drop(["total_children_ever_born_m_%"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_1 = sm.add_constant(X_train_new_1)

In [ ]:
# Running the linear model
lm_2 = sm.OLS(y_train,X_train_new_1).fit()

In [ ]:
lm_2.params

In [ ]:
#Let's see the summary of our linear model
lm_2.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_1
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_2 = X_train_new_1.drop(["last_year’s_births_of_order_1_%"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_2 = sm.add_constant(X_train_new_2)

In [ ]:
# Running the linear model
lm_3 = sm.OLS(y_train,X_train_new_2).fit()

In [ ]:
lm_3.params

In [ ]:
#Let's see the summary of our linear model
lm_3.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_2
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_3 = X_train_new_2.drop(["ttl_surv._child._p"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_3 = sm.add_constant(X_train_new_3)

In [ ]:
# Running the linear model
lm_4 = sm.OLS(y_train,X_train_new_3).fit()

In [ ]:
lm_4.params

In [ ]:
#Let's see the summary of our linear model
lm_4.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_3
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_4 = X_train_new_3.drop(["total_children_ever_born_f"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_4 = sm.add_constant(X_train_new_4)

In [ ]:
# Running the linear model
lm_5 = sm.OLS(y_train,X_train_new_4).fit()

In [ ]:
#Let's see the summary of our linear model
lm_5.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_4
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_5 = X_train_new_4.drop(["last_year’s_births_of_order_5"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_5 = sm.add_constant(X_train_new_5)

In [ ]:
# Running the linear model
lm_6 = sm.OLS(y_train,X_train_new_5).fit()

In [ ]:
#Let's see the summary of our linear model
lm_6.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_5
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_6 = X_train_new_5.drop(["last_year’s_births_of_order_4"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_6 = sm.add_constant(X_train_new_6)

In [ ]:
# Running the linear model
lm_7 = sm.OLS(y_train,X_train_new_6).fit()

In [ ]:
#Let's see the summary of our linear model
lm_7.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_6
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_7 = X_train_new_6.drop(["no._of_surv._child._5+_%"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_7 = sm.add_constant(X_train_new_7)

In [ ]:
# Running the linear model
lm_8 = sm.OLS(y_train,X_train_new_7).fit()

In [ ]:
lm_8.params

In [ ]:
#Let's see the summary of our linear model
lm_8.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_7
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
vif['Features'].unique()

In [ ]:
y_train_price = lm_8.predict(X_train_new_7)

In [ ]:
y_train

In [ ]:
y_train_price = y_train_price.to_frame()

In [ ]:
z = y_train['total_survival_rate'] - y_train_price[0]
z

In [ ]:
# Plot the histogram of the error terms
fig = plt.figure()
sns.distplot(z, bins = 20)
plt.xlabel('Errors', fontsize = 18) 
plt.show()

In [ ]:
# Applying the scaling on the test sets
df_test[num_vars] = scaler.transform(df_test[num_vars])

In [ ]:
df_test.describe()

In [ ]:
# Dividing into X_test and y_test
y_test = df_test.pop('total_survival_rate')
X_test = df_test

In [ ]:
# Creating X_test_new dataframe by dropping variables from X_test
X_test_new = X_test[['ttl_surv._child._m', 'last_year’s_births_of_order_7+','parity_6_%', 'parity_7+_%', 'parity_5_%', 'ttl_surv._child._m_%','ttl_surv._child._f_%']]

# Adding a constant variable 
X_test_new = sm.add_constant(X_test_new)

In [ ]:
X_test_new

In [ ]:
# Making predictions
y_pred = lm_8.predict(X_test_new)

In [ ]:
# Plotting y_test and y_pred to understand the spread
plt.scatter(y_test, y_pred)
plt.title('y_test vs y_pred') 
plt.xlabel('y_test') 
plt.ylabel('y_pred')
plt.show()

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

price=−0.1108+0.391×carwidth+0.751×enginesize−0.082×boreratio−0.075×stroke+0.200×bmw+0.110×porsche+0.331×rear+0.168×three+0.203×two

## religion

In [178]:
print(religion.info())
print(religion.columns)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 230789 entries, 0 to 230788
Data columns (total 75 columns):
state_code                           230789 non-null int64
distt._code                          230789 non-null int64
area_name                            230789 non-null object
total/_rural/_urban                  230789 non-null object
religious_community                  230789 non-null object
present_age                          230789 non-null object
total_ever_married_women_x           230789 non-null int64
parity_0                             230789 non-null int64
parity_1                             230789 non-null int64
parity_2                             230789 non-null int64
parity_3                             230789 non-null int64
parity_4                             230789 non-null int64
parity_5                             230789 non-null int64
parity_6                             230789 non-null int64
parity_7+                            230789 non-null int64
total_children_ever_born_p           230789 non-null int64
total_children_ever_born_m           230789 non-null int64
total_children_ever_born_f           230789 non-null int64
total_ever_unmarried_women_x         230789 non-null int64
parity_0_%                           230789 non-null float64
parity_1_%                           230789 non-null float64
parity_2_%                           230789 non-null float64
parity_3_%                           230789 non-null float64
parity_4_%                           230789 non-null float64
parity_5_%                           230789 non-null float64
parity_6_%                           230789 non-null float64
parity_7+_%                          230789 non-null float64
total_ever_married_women_%_x         230789 non-null float64
total_ever_unmarried_women_%_x       230789 non-null float64
total_children_ever_born_m_%         230789 non-null float64
total_children_ever_born_f_%         230789 non-null float64
no._of_surv._child._0                230789 non-null float64
no._of_surv._child._1                230789 non-null float64
no._of_surv._child._2                230789 non-null float64
no._of_surv._child._3                230789 non-null float64
no._of_surv._child._4                230789 non-null float64
no._of_surv._child._5+               230789 non-null float64
ttl_surv._child._p                   230789 non-null float64
ttl_surv._child._m                   230789 non-null float64
ttl_surv._child._f                   230789 non-null float64
total_ever_unmarried_women_%_y       230789 non-null float64
total_ever_married_women_%_y         230789 non-null float64
ttl_surv._child._m_%                 230789 non-null float64
ttl_surv._child._f_%                 230789 non-null float64
no._of_surv._child._0_%              230789 non-null float64
no._of_surv._child._1_%              230789 non-null float64
no._of_surv._child._2_%              230789 non-null float64
no._of_surv._child._3_%              230789 non-null float64
no._of_surv._child._4_%              230789 non-null float64
no._of_surv._child._5+_%             230789 non-null float64
total_women                          230789 non-null float64
total_currently_married_women        230789 non-null float64
number_of_births_last_year_m         230789 non-null float64
number_of_births_last_year_f         230789 non-null float64
last_year’s_births_of_order_1        230789 non-null float64
last_year’s_births_of_order_2        230789 non-null float64
last_year’s_births_of_order_3        230789 non-null float64
last_year’s_births_of_order_4        230789 non-null float64
last_year’s_births_of_order_5        230789 non-null float64
last_year’s_births_of_order_6        230789 non-null float64
last_year’s_births_of_order_7+       230789 non-null float64
total_currently_unmarried_women      230789 non-null float64
number_of_births_last_year_p         230789 non-null float64
last_year’s_births_of_order_1_%      230789 non-null float64
last_year’s_births_of_order_2_%      230789 non-null float64
last_year’s_births_of_order_3_%      230789 non-null float64
last_year’s_births_of_order_4_%      230789 non-null float64
last_year’s_births_of_order_5_%      230789 non-null float64
last_year’s_births_of_order_6_%      230789 non-null float64
last_year’s_births_of_order_7+_%     230789 non-null float64
number_of_births_last_year_m_%       230789 non-null float64
number_of_births_last_year_f_%       230789 non-null float64
total_currently_unmarried_women_%    230789 non-null float64
total_currently_married_women_%      230789 non-null float64
total_survival_rate                  230789 non-null float64
dtypes: float64(56), int64(15), object(4)
memory usage: 133.8+ MB
None
Index(['state_code', 'distt._code', 'area_name', 'total/_rural/_urban',
       'religious_community', 'present_age', 'total_ever_married_women_x',
       'parity_0', 'parity_1', 'parity_2', 'parity_3', 'parity_4', 'parity_5',
       'parity_6', 'parity_7+', 'total_children_ever_born_p',
       'total_children_ever_born_m', 'total_children_ever_born_f',
       'total_ever_unmarried_women_x', 'parity_0_%', 'parity_1_%',
       'parity_2_%', 'parity_3_%', 'parity_4_%', 'parity_5_%', 'parity_6_%',
       'parity_7+_%', 'total_ever_married_women_%_x',
       'total_ever_unmarried_women_%_x', 'total_children_ever_born_m_%',
       'total_children_ever_born_f_%', 'no._of_surv._child._0',
       'no._of_surv._child._1', 'no._of_surv._child._2',
       'no._of_surv._child._3', 'no._of_surv._child._4',
       'no._of_surv._child._5+', 'ttl_surv._child._p', 'ttl_surv._child._m',
       'ttl_surv._child._f', 'total_ever_unmarried_women_%_y',
       'total_ever_married_women_%_y', 'ttl_surv._child._m_%',
       'ttl_surv._child._f_%', 'no._of_surv._child._0_%',
       'no._of_surv._child._1_%', 'no._of_surv._child._2_%',
       'no._of_surv._child._3_%', 'no._of_surv._child._4_%',
       'no._of_surv._child._5+_%', 'total_women',
       'total_currently_married_women', 'number_of_births_last_year_m',
       'number_of_births_last_year_f', 'last_year’s_births_of_order_1',
       'last_year’s_births_of_order_2', 'last_year’s_births_of_order_3',
       'last_year’s_births_of_order_4', 'last_year’s_births_of_order_5',
       'last_year’s_births_of_order_6', 'last_year’s_births_of_order_7+',
       'total_currently_unmarried_women', 'number_of_births_last_year_p',
       'last_year’s_births_of_order_1_%', 'last_year’s_births_of_order_2_%',
       'last_year’s_births_of_order_3_%', 'last_year’s_births_of_order_4_%',
       'last_year’s_births_of_order_5_%', 'last_year’s_births_of_order_6_%',
       'last_year’s_births_of_order_7+_%', 'number_of_births_last_year_m_%',
       'number_of_births_last_year_f_%', 'total_currently_unmarried_women_%',
       'total_currently_married_women_%', 'total_survival_rate'],
      dtype='object')

In [179]:
# Seperating into categortical and numric
categorical = religion.select_dtypes(include=['object'])
numeric = religion.select_dtypes(exclude=['object'])
print(categorical.columns.values)
print(numeric.columns.values)

['area_name' 'total/_rural/_urban' 'religious_community' 'present_age']
['state_code' 'distt._code' 'total_ever_married_women_x' 'parity_0'
 'parity_1' 'parity_2' 'parity_3' 'parity_4' 'parity_5' 'parity_6'
 'parity_7+' 'total_children_ever_born_p' 'total_children_ever_born_m'
 'total_children_ever_born_f' 'total_ever_unmarried_women_x' 'parity_0_%'
 'parity_1_%' 'parity_2_%' 'parity_3_%' 'parity_4_%' 'parity_5_%'
 'parity_6_%' 'parity_7+_%' 'total_ever_married_women_%_x'
 'total_ever_unmarried_women_%_x' 'total_children_ever_born_m_%'
 'total_children_ever_born_f_%' 'no._of_surv._child._0'
 'no._of_surv._child._1' 'no._of_surv._child._2' 'no._of_surv._child._3'
 'no._of_surv._child._4' 'no._of_surv._child._5+' 'ttl_surv._child._p'
 'ttl_surv._child._m' 'ttl_surv._child._f'
 'total_ever_unmarried_women_%_y' 'total_ever_married_women_%_y'
 'ttl_surv._child._m_%' 'ttl_surv._child._f_%' 'no._of_surv._child._0_%'
 'no._of_surv._child._1_%' 'no._of_surv._child._2_%'
 'no._of_surv._child._3_%' 'no._of_surv._child._4_%'
 'no._of_surv._child._5+_%' 'total_women' 'total_currently_married_women'
 'number_of_births_last_year_m' 'number_of_births_last_year_f'
 'last_year’s_births_of_order_1' 'last_year’s_births_of_order_2'
 'last_year’s_births_of_order_3' 'last_year’s_births_of_order_4'
 'last_year’s_births_of_order_5' 'last_year’s_births_of_order_6'
 'last_year’s_births_of_order_7+' 'total_currently_unmarried_women'
 'number_of_births_last_year_p' 'last_year’s_births_of_order_1_%'
 'last_year’s_births_of_order_2_%' 'last_year’s_births_of_order_3_%'
 'last_year’s_births_of_order_4_%' 'last_year’s_births_of_order_5_%'
 'last_year’s_births_of_order_6_%' 'last_year’s_births_of_order_7+_%'
 'number_of_births_last_year_m_%' 'number_of_births_last_year_f_%'
 'total_currently_unmarried_women_%' 'total_currently_married_women_%'
 'total_survival_rate']

In [180]:
# Creating dummies
category = ['area_name','religious_community','total/_rural/_urban', 'present_age' ]
dummy = pd.get_dummies(religion[category])
religion_1 = pd.concat([religion, dummy], axis=1)
religion_1 = religion_1.drop(category, axis=1)

In [181]:
dummy.columns

Index(['area_name_district_-_adilabad', 'area_name_district_-_agra',
       'area_name_district_-_ahmadabad', 'area_name_district_-_ahmadnagar',
       'area_name_district_-_aizawl', 'area_name_district_-_ajmer',
       'area_name_district_-_akola', 'area_name_district_-_alappuzha',
       'area_name_district_-_aligarh', 'area_name_district_-_alirajpur',
       ...
       'present_age_45-49', 'present_age_50-54', 'present_age_55-59',
       'present_age_60-64', 'present_age_65-69', 'present_age_70-74',
       'present_age_75-79', 'present_age_80+', 'present_age_all_ages',
       'present_age_less_than_15'],
      dtype='object', length=1364)

In [182]:
# Converting everything into float for model building
religion_1 = religion_1.astype('float')
religion_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 230789 entries, 0 to 230788
Columns: 1435 entries, state_code to present_age_less_than_15
dtypes: float64(1435)
memory usage: 2.5 GB

In [183]:
from sklearn.model_selection import train_test_split

In [184]:
# Putting feature variable to X
X = religion_1.drop(['total_survival_rate'], axis=1)
X.head()

,state_code,distt._code,total_ever_married_women_x,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,...,present_age_45-49,present_age_50-54,present_age_55-59,present_age_60-64,present_age_65-69,present_age_70-74,present_age_75-79,present_age_80+,present_age_all_ages,present_age_less_than_15
0,0.0,0.0,339621277.0,49549956.0,50938514.0,81485683.0,60424480.0,40104260.0,23742379.0,14490504.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1812200.0,1355195.0,136777.0,320228.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,11229274.0,7880413.0,2243929.0,605514.0,215480.0,283938.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,37474855.0,12988953.0,12869090.0,8233549.0,2313647.0,621922.0,173729.0,81731.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,45672215.0,7339229.0,10679349.0,15526465.0,7645252.0,2928732.0,904274.0,300426.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [185]:
# Putting response variable to y
y = religion_1['total_survival_rate']
y.head()

0    0.895752
1    0.927205
2    0.906729
3    0.918278
4    0.925913
Name: total_survival_rate, dtype: float64

In [186]:
from sklearn.model_selection import train_test_split

In [187]:
df_train, df_test = train_test_split(religion_1, train_size = 0.7, test_size = 0.3, random_state = 100)

In [188]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [189]:
# Apply scaler() to all the columns except the 'yes-no' and 'dummy' variables
num_vars = ['total_ever_married_women_x', 'parity_0', 'parity_1', 'parity_2',  'parity_3', 'parity_4', 'parity_5', 'parity_6', 'parity_7+','total_children_ever_born_p', 'total_children_ever_born_m', 'total_children_ever_born_f',  'total_ever_unmarried_women_x', 'parity_0_%', 'parity_1_%',  'parity_2_%', 'parity_3_%', 'parity_4_%', 'parity_5_%', 'parity_6_%', 'parity_7+_%', 'total_ever_married_women_%_x', 'total_ever_unmarried_women_%_x', 'total_children_ever_born_m_%','total_children_ever_born_f_%', 'no._of_surv._child._0','no._of_surv._child._1', 'no._of_surv._child._2', 'no._of_surv._child._3', 'no._of_surv._child._4','no._of_surv._child._5+', 'ttl_surv._child._p', 'ttl_surv._child._m','ttl_surv._child._f', 'total_ever_unmarried_women_%_y','total_ever_married_women_%_y', 'ttl_surv._child._m_%','ttl_surv._child._f_%', 'no._of_surv._child._0_%','no._of_surv._child._1_%', 'no._of_surv._child._2_%','no._of_surv._child._3_%', 'no._of_surv._child._4_%','no._of_surv._child._5+_%', 'total_women','total_currently_married_women', 'number_of_births_last_year_m','number_of_births_last_year_f', 'last_year’s_births_of_order_1','last_year’s_births_of_order_2', 'last_year’s_births_of_order_3','last_year’s_births_of_order_4', 'last_year’s_births_of_order_5','last_year’s_births_of_order_6', 'last_year’s_births_of_order_7+','total_currently_unmarried_women', 'number_of_births_last_year_p','last_year’s_births_of_order_1_%', 'last_year’s_births_of_order_2_%', 'last_year’s_births_of_order_3_%', 'last_year’s_births_of_order_4_%','last_year’s_births_of_order_5_%', 'last_year’s_births_of_order_6_%','last_year’s_births_of_order_7+_%', 'number_of_births_last_year_m_%','number_of_births_last_year_f_%', 'total_currently_unmarried_women_%','total_currently_married_women_%', 'total_survival_rate']
df_train[num_vars] = scaler.fit_transform(df_train[num_vars])
df_train

,state_code,distt._code,total_ever_married_women_x,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,...,present_age_45-49,present_age_50-54,present_age_55-59,present_age_60-64,present_age_65-69,present_age_70-74,present_age_75-79,present_age_80+,present_age_all_ages,present_age_less_than_15
55590,8.0,129.0,2.944456e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.654958e-08,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23098,3.0,35.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
181110,27.0,499.0,3.182957e-06,1.541878e-05,4.004828e-06,8.713187e-07,3.309917e-07,5.735052e-07,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121256,19.0,329.0,5.352727e-05,3.483353e-05,2.821048e-05,2.180751e-05,3.551541e-05,6.495569e-05,1.020117e-04,1.469928e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
159089,23.0,438.0,0.000000e+00,0.000000e+00,1.963151e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
194939,28.0,536.0,2.061119e-08,4.036331e-08,3.926302e-08,2.454419e-08,3.309917e-08,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151103,22.0,416.0,5.594467e-08,4.036331e-08,9.815756e-08,9.817676e-08,4.964875e-08,4.987001e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70045,9.0,171.0,4.416684e-08,6.054496e-08,1.963151e-08,2.454419e-08,4.964875e-08,7.480502e-08,8.423756e-08,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149721,22.0,412.0,1.766674e-08,1.009083e-07,1.963151e-08,1.227209e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138080,21.0,376.0,2.067008e-05,1.562060e-05,1.391874e-05,1.488605e-05,2.118347e-05,2.575786e-05,3.588520e-05,3.657568e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70207,9.0,172.0,3.818960e-06,3.531789e-06,2.277255e-06,1.092216e-06,2.366590e-06,3.590641e-06,6.149342e-06,8.281285e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
35270,6.0,69.0,1.804952e-06,3.329973e-06,4.338564e-06,2.000351e-06,7.612809e-07,2.493501e-07,4.211878e-08,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225458,33.0,623.0,5.888913e-08,8.072661e-08,3.926302e-08,9.817676e-08,6.619834e-08,2.493501e-08,8.423756e-08,0.000000e+00,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54421,8.0,126.0,2.054347e-05,1.341878e-04,2.061309e-06,2.748949e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
58227,9.0,136.0,2.935623e-06,6.458129e-07,1.236785e-06,1.730365e-06,4.584235e-06,5.585442e-06,6.107223e-06,3.864600e-06,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10372,28.0,0.0,7.652642e-05,5.697281e-05,6.034726e-05,8.838362e-05,1.072910e-04,8.914265e-05,6.507351e-05,4.734135e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151607,22.0,417.0,2.355565e-08,4.036331e-08,1.963151e-08,1.227209e-08,0.000000e+00,7.480502e-08,0.000000e+00,6.901071e-08,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67874,9.0,164.0,4.151094e-05,1.302322e-04,8.127446e-05,2.731768e-05,1.246184e-05,6.383362e-06,4.717303e-06,3.036471e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61584,9.0,146.0,1.546664e-04,6.201822e-05,5.384923e-05,6.259995e-05,1.410687e-04,2.652337e-04,3.785215e-04,4.471894e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87863,10.0,226.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
131015,20.0,356.0,9.275037e-07,4.298692e-06,6.674714e-07,8.467745e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
54504,8.0,126.0,6.360026e-07,1.412716e-07,2.159466e-07,1.840814e-07,4.964875e-07,1.271685e-06,1.726870e-06,2.001311e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
108631,16.0,292.0,1.052996e-04,8.363277e-05,1.770959e-04,1.207697e-04,8.637228e-05,8.044033e-05,7.733008e-05,7.673991e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
163635,23.0,452.0,3.652009e-05,1.872857e-05,1.376169e-05,1.379383e-05,2.750541e-05,5.159053e-05,8.398484e-05,1.057244e-04,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
132902,20.0,362.0,7.840498e-05,8.506567e-05,7.277401e-05,4.943200e-05,6.542051e-05,8.517798e-05,1.069817e-04,1.323625e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39980,6.0,83.0,2.944456e-09,0.000000e+00,1.963151e-08,1.227209e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
136559,21.0,372.0,1.073019e-04,6.187695e-05,1.002385e-04,1.473388e-04,1.342006e-04,1.169452e-04,8.802825e-05,5.803801e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162149,23.0,447.0,2.723622e-06,6.942489e-06,6.419504e-06,2.307154e-06,8.109296e-07,1.994801e-07,8.423756e-08,1.380214e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
194809,28.0,536.0,1.089449e-07,2.825431e-07,1.177891e-07,1.227209e-07,8.274792e-08,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24084,3.0,38.0,1.061182e-04,4.060549e-05,6.829803e-05,1.731470e-04,1.699973e-04,9.697224e-05,5.812391e-05,3.719677e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202395,29.0,557.0,2.650011e-08,0.000000e+00,0.000000e+00,7.363257e-08,3.309917e-08,2.493501e-08,4.211878e-08,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
215426,32.0,593.0,2.711844e-06,1.513624e-06,1.491995e-06,1.006312e-06,1.406715e-06,2.418696e-06,3.790690e-06,6.625028e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
137302,21.0,374.0,9.257076e-05,6.320894e-05,8.050883e-05,1.020793e-04,1.157312e-04,1.136288e-04,9.834735e-05,7.805112e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80989,10.0,203.0,1.322061e-06,1.412716e-06,1.060102e-06,6.381489e-07,8.440288e-07,1.296620e-06,2.105939e-06,2.760428e-06,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
169609,24.0,468.0,2.002230e-07,8.072661e-08,1.177891e-07,2.945303e-07,2.978925e-07,1.246750e-07,2.948314e-07,1.380214e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
173563,24.0,480.0,3.121124e-07,3.027248e-07,2.944727e-07,2.208977e-07,2.813429e-07,4.488301e-07,4.633066e-07,6.210964e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
109456,17.0,294.0,4.416684e-08,8.072661e-08,5.889453e-08,1.227209e-08,0.000000e+00,4.987001e-08,4.211878e-08,1.380214e-07,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
138810,21.0,379.0,9.624839e-05,2.833504e-05,3.423736e-05,5.853789e-05,1.231124e-04,1.825243e-04,1.930304e-04,1.912287e-04,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148796,22.0,409.0,7.826659e-05,2.456107e-05,3.751582e-05,6.301721e-05,1.080026e-04,1.419301e-04,1.347801e-04,1.048963e-04,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
190315,27.0,524.0,1.177783e-08,4.036331e-08,1.963151e-08,1.227209e-08,0.000000e+00,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109796,17.0,295.0,1.017604e-05,9.868828e-06,6.733608e-06,6.332401e-06,9.648407e-06,1.426282e-05,1.899557e-05,1.870190e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91791,10.0,238.0,2.473343e-07,2.623615e-07,3.533672e-07,2.577140e-07,2.482438e-07,1.745450e-07,2.105939e-07,2.070321e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
86296,10.0,221.0,3.801470e-04,1.501313e-04,1.911913e-04,2.979787e-04,5.884536e-04,7.135152e-04,6.041939e-04,4.102687e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109296,17.0,293.0,1.266116e-07,1.210899e-07,1.963151e-08,4.908838e-08,4.964875e-08,2.742851e-07,2.948314e-07,2.070321e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
209905,29.0,579.0,3.445014e-07,3.027248e-07,2.159466e-07,2.454419e-07,4.468388e-07,5.485702e-07,4.633066e-07,5.520857e-07,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
181026,27.0,499.0,1.001115e-07,8.072661e-08,5.889453e-08,4.908838e-08,6.619834e-08,1.246750e-07,2.948314e-07,2.760428e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
202254,29.0,556.0,5.594467e-08,1.210899e-07,1.963151e-08,3.681628e-08,6.619834e-08,9.974003e-08,4.211878e-08,0.000000e+00,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
106210,15.0,285.0,2.944456e-09,0.000000e+00,1.963151e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.901071e-08,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144962,22.0,0.0,2.343443e-03,4.918087e-03,5.694925e-03,2.289506e-03,9.368885e-04,2.932107e-04,1.119517e-04,8.902382e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20533,2.0,27.0,5.055631e-06,1.412716e-06,3.317725e-06,8.357296e-06,8.291342e-06,4.662846e-06,3.074671e-06,1.725268e-06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
206690,29.0,569.0,6.890028e-07,3.652879e-06,2.944727e-07,4.786117e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
145332,22.0,400.0,6.608243e-05,3.828460e-05,5.033519e-05,6.664975e-05,9.828798e-05,9.500238e-05,7.252854e-05,4.789343e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82270,10.0,208.0,2.033442e-05,9.465195e-06,6.478399e-06,5.853789e-06,1.107167e-05,2.373813e-05,4.447743e-05,7.287531e-05,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
194442,28.0,535.0,7.361141e-08,2.018165e-08,5.889453e-08,4.908838e-08,9.929750e-08,9.974003e-08,1.263563e-07,6.901071e-08,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
212912,31.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65615,9.0,158.0,1.082176e-04,7.824427e-05,5.822706e-05,4.462134e-05,7.488687e-05,1.293628e-04,2.040234e-04,2.653462e-04,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
77655,9.0,194.0,2.650011e-08,2.018165e-08,3.926302e-08,1.227209e-08,0.000000e+00,2.493501e-08,4.211878e-08,2.070321e-07,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
210755,29.0,581.0,3.900816e-05,1.945511e-05,3.123373e-05,4.579946e-05,5.289247e-05,4.558119e-05,3.837021e-05,3.050273e-05,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56088,8.0,131.0,7.747453e-05,2.960648e-05,4.108875e-05,7.704421e-05,1.126199e-04,1.291633e-04,1.122887e-04,7.929331e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38408,6.0,78.0,2.208342e-07,2.421798e-07,2.552096e-07,3.436186e-07,2.482438e-07,1.246750e-07,4.211878e-08,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [190]:
y_train = df_train.pop('total_survival_rate')
X_train = df_train

In [191]:
y_train = y_train.to_frame()
y_train

        total_survival_rate
55590              0.714286
23098              0.000000
181110             0.937751
121256             0.000000
159089             1.000000
194939             1.000000
151103             0.000000
70045              0.921569
149721             0.000000
138080             0.882298
70207              0.000000
35270              0.902532
225458             1.000000
54421              0.871609
58227              0.903146
10372              0.898325
151607             0.758621
67874              0.915198
61584              0.883767
87863              0.000000
131015             0.000000
54504              0.891529
108631             0.897442
163635             0.000000
132902             0.000000
39980              1.000000
136559             0.000000
162149             0.910714
194809             0.000000
24084              0.000000
...                     ...
202395             0.000000
215426             0.822109
137302             0.899644
80989              0.856069
169609             0.940000
173563             0.000000
109456             0.000000
138810             0.000000
148796             0.906130
190315             0.857143
109796             0.875650
91791              0.835000
86296              0.000000
109296             0.794872
209905             0.000000
181026             0.000000
202254             0.937500
106210             0.000000
144962             0.904857
20533              0.951081
206690             0.935484
145332             0.000000
82270              0.000000
194442             0.000000
212912             1.000000
65615              0.000000
77655              0.894737
210755             0.926543
56088              0.891072
38408              0.903846

[161552 rows x 1 columns]

In [192]:
X_train

,state_code,distt._code,total_ever_married_women_x,parity_0,parity_1,parity_2,parity_3,parity_4,parity_5,parity_6,...,present_age_45-49,present_age_50-54,present_age_55-59,present_age_60-64,present_age_65-69,present_age_70-74,present_age_75-79,present_age_80+,present_age_all_ages,present_age_less_than_15
55590,8.0,129.0,2.944456e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.654958e-08,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23098,3.0,35.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
181110,27.0,499.0,3.182957e-06,1.541878e-05,4.004828e-06,8.713187e-07,3.309917e-07,5.735052e-07,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121256,19.0,329.0,5.352727e-05,3.483353e-05,2.821048e-05,2.180751e-05,3.551541e-05,6.495569e-05,1.020117e-04,1.469928e-04,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
159089,23.0,438.0,0.000000e+00,0.000000e+00,1.963151e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
194939,28.0,536.0,2.061119e-08,4.036331e-08,3.926302e-08,2.454419e-08,3.309917e-08,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151103,22.0,416.0,5.594467e-08,4.036331e-08,9.815756e-08,9.817676e-08,4.964875e-08,4.987001e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70045,9.0,171.0,4.416684e-08,6.054496e-08,1.963151e-08,2.454419e-08,4.964875e-08,7.480502e-08,8.423756e-08,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149721,22.0,412.0,1.766674e-08,1.009083e-07,1.963151e-08,1.227209e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138080,21.0,376.0,2.067008e-05,1.562060e-05,1.391874e-05,1.488605e-05,2.118347e-05,2.575786e-05,3.588520e-05,3.657568e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70207,9.0,172.0,3.818960e-06,3.531789e-06,2.277255e-06,1.092216e-06,2.366590e-06,3.590641e-06,6.149342e-06,8.281285e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
35270,6.0,69.0,1.804952e-06,3.329973e-06,4.338564e-06,2.000351e-06,7.612809e-07,2.493501e-07,4.211878e-08,6.901071e-08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225458,33.0,623.0,5.888913e-08,8.072661e-08,3.926302e-08,9.817676e-08,6.619834e-08,2.493501e-08,8.423756e-08,0.000000e+00,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54421,8.0,126.0,2.054347e-05,1.341878e-04,2.061309e-06,2.748949e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
58227,9.0,136.0,2.935623e-06,6.458129e-07,1.236785e-06,1.730365e-06,4.584235e-06,5.585442e-06,6.107223e-06,3.864600e-06,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10372,28.0,0.0,7.652642e-05,5.697281e-05,6.034726e-05,8.838362e-05,1.072910e-04,8.914265e-05,6.507351e-05,4.734135e-05,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
151607,22.0,417.0,2.355565e-08,4.036331e-08,1.963151e-08,1.227209e-08,0.000000e+00,7.480502e-08,0.000000e+00,6.901071e-08,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67874,9.0,164.0,4.151094e-05,1.302322e-04,8.127446e-05,2.731768e-05,1.246184e-05,6.383362e-06,4.717303e-06,3.036471e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61584,9.0,146.0,1.546664e-04,6.201822e-05,5.384923e-05,6.259995e-05,1.410687e-04,2.652337e-04,3.785215e-04,4.471894e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87863,10.0,226.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
131015,20.0,356.0,9.275037e-07,4.298692e-06,6.674714e-07,8.467745e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
54504,8.0,126.0,6.360026e-07,1.412716e-07,2.159466e-07,1.840814e-07,4.964875e-07,1.271685e-06,1.726870e-06,2.001311e-06,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
108631,16.0,292.0,1.052996e-04,8.363277e-05,1.770959e-04,1.207697e-04,8.637228e-05,8.044033e-05,7.733008e-05,7.673991e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
163635,23.0,452.0,3.652009e-05,1.872857e-05,1.376169e-05,1.379383e-05,2.750541e-05,5.159053e-05,8.398484e-05,1.057244e-04,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
132902,20.0,362.0,7.840498e-05,8.506567e-05,7.277401e-05,4.943200e-05,6.542051e-05,8.517798e-05,1.069817e-04,1.323625e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39980,6.0,83.0,2.944456e-09,0.000000e+00,1.963151e-08,1.227209e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
136559,21.0,372.0,1.073019e-04,6.187695e-05,1.002385e-04,1.473388e-04,1.342006e-04,1.169452e-04,8.802825e-05,5.803801e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162149,23.0,447.0,2.723622e-06,6.942489e-06,6.419504e-06,2.307154e-06,8.109296e-07,1.994801e-07,8.423756e-08,1.380214e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
194809,28.0,536.0,1.089449e-07,2.825431e-07,1.177891e-07,1.227209e-07,8.274792e-08,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24084,3.0,38.0,1.061182e-04,4.060549e-05,6.829803e-05,1.731470e-04,1.699973e-04,9.697224e-05,5.812391e-05,3.719677e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202395,29.0,557.0,2.650011e-08,0.000000e+00,0.000000e+00,7.363257e-08,3.309917e-08,2.493501e-08,4.211878e-08,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
215426,32.0,593.0,2.711844e-06,1.513624e-06,1.491995e-06,1.006312e-06,1.406715e-06,2.418696e-06,3.790690e-06,6.625028e-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
137302,21.0,374.0,9.257076e-05,6.320894e-05,8.050883e-05,1.020793e-04,1.157312e-04,1.136288e-04,9.834735e-05,7.805112e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80989,10.0,203.0,1.322061e-06,1.412716e-06,1.060102e-06,6.381489e-07,8.440288e-07,1.296620e-06,2.105939e-06,2.760428e-06,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
169609,24.0,468.0,2.002230e-07,8.072661e-08,1.177891e-07,2.945303e-07,2.978925e-07,1.246750e-07,2.948314e-07,1.380214e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
173563,24.0,480.0,3.121124e-07,3.027248e-07,2.944727e-07,2.208977e-07,2.813429e-07,4.488301e-07,4.633066e-07,6.210964e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
109456,17.0,294.0,4.416684e-08,8.072661e-08,5.889453e-08,1.227209e-08,0.000000e+00,4.987001e-08,4.211878e-08,1.380214e-07,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
138810,21.0,379.0,9.624839e-05,2.833504e-05,3.423736e-05,5.853789e-05,1.231124e-04,1.825243e-04,1.930304e-04,1.912287e-04,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148796,22.0,409.0,7.826659e-05,2.456107e-05,3.751582e-05,6.301721e-05,1.080026e-04,1.419301e-04,1.347801e-04,1.048963e-04,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
190315,27.0,524.0,1.177783e-08,4.036331e-08,1.963151e-08,1.227209e-08,0.000000e+00,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109796,17.0,295.0,1.017604e-05,9.868828e-06,6.733608e-06,6.332401e-06,9.648407e-06,1.426282e-05,1.899557e-05,1.870190e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91791,10.0,238.0,2.473343e-07,2.623615e-07,3.533672e-07,2.577140e-07,2.482438e-07,1.745450e-07,2.105939e-07,2.070321e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
86296,10.0,221.0,3.801470e-04,1.501313e-04,1.911913e-04,2.979787e-04,5.884536e-04,7.135152e-04,6.041939e-04,4.102687e-04,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109296,17.0,293.0,1.266116e-07,1.210899e-07,1.963151e-08,4.908838e-08,4.964875e-08,2.742851e-07,2.948314e-07,2.070321e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
209905,29.0,579.0,3.445014e-07,3.027248e-07,2.159466e-07,2.454419e-07,4.468388e-07,5.485702e-07,4.633066e-07,5.520857e-07,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
181026,27.0,499.0,1.001115e-07,8.072661e-08,5.889453e-08,4.908838e-08,6.619834e-08,1.246750e-07,2.948314e-07,2.760428e-07,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
202254,29.0,556.0,5.594467e-08,1.210899e-07,1.963151e-08,3.681628e-08,6.619834e-08,9.974003e-08,4.211878e-08,0.000000e+00,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
106210,15.0,285.0,2.944456e-09,0.000000e+00,1.963151e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.901071e-08,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144962,22.0,0.0,2.343443e-03,4.918087e-03,5.694925e-03,2.289506e-03,9.368885e-04,2.932107e-04,1.119517e-04,8.902382e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20533,2.0,27.0,5.055631e-06,1.412716e-06,3.317725e-06,8.357296e-06,8.291342e-06,4.662846e-06,3.074671e-06,1.725268e-06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
206690,29.0,569.0,6.890028e-07,3.652879e-06,2.944727e-07,4.786117e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
145332,22.0,400.0,6.608243e-05,3.828460e-05,5.033519e-05,6.664975e-05,9.828798e-05,9.500238e-05,7.252854e-05,4.789343e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82270,10.0,208.0,2.033442e-05,9.465195e-06,6.478399e-06,5.853789e-06,1.107167e-05,2.373813e-05,4.447743e-05,7.287531e-05,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
194442,28.0,535.0,7.361141e-08,2.018165e-08,5.889453e-08,4.908838e-08,9.929750e-08,9.974003e-08,1.263563e-07,6.901071e-08,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
212912,31.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.493501e-08,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65615,9.0,158.0,1.082176e-04,7.824427e-05,5.822706e-05,4.462134e-05,7.488687e-05,1.293628e-04,2.040234e-04,2.653462e-04,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
77655,9.0,194.0,2.650011e-08,2.018165e-08,3.926302e-08,1.227209e-08,0.000000e+00,2.493501e-08,4.211878e-08,2.070321e-07,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
210755,29.0,581.0,3.900816e-05,1.945511e-05,3.123373e-05,4.579946e-05,5.289247e-05,4.558119e-05,3.837021e-05,3.050273e-05,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56088,8.0,131.0,7.747453e-05,2.960648e-05,4.108875e-05,7.704421e-05,1.126199e-04,1.291633e-04,1.122887e-04,7.929331e-05,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38408,6.0,78.0,2.208342e-07,2.421798e-07,2.552096e-07,3.436186e-07,2.482438e-07,1.246750e-07,4.211878e-08,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [193]:
# Importing RFE and LinearRegression
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [ ]:
# Running RFE with the output number of the variable equal to 10
lm = LinearRegression()
lm.fit(X_train, y_train)
# running RFE
rfe = RFE(lm, 15)
rfe = rfe.fit(X_train, y_train)

C:\anaconda\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
list(zip(X_train.columns,rfe.support_,rfe.ranking_))

In [ ]:
col = X_train.columns[rfe.support_]
col

In [ ]:
X_train.columns[~rfe.support_]

In [ ]:
# Creating X_test dataframe with RFE selected variables
X_train_rfe = X_train[col]

In [ ]:
# Adding a constant variable 
import statsmodels.api as sm  
X_train_rfe = sm.add_constant(X_train_rfe)

In [ ]:
# Running the linear model
lm = sm.OLS(y_train,X_train_rfe).fit()

In [ ]:
lm.params

In [ ]:
#Let's see the summary of our linear model
lm.summary()

In [ ]:
# Calculate the VIFs for the new model
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
X = X_train_rfe
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new = X_train_rfe.drop(["total_children_ever_born_p"], axis = 1)

In [ ]:
# Adding a constant variable 
X_train_new_1 = sm.add_constant(X_train_new)

In [ ]:
# Running the linear model
lm_1 = sm.OLS(y_train,X_train_new_1).fit()

In [ ]:
lm_1.params

In [ ]:
#Let's see the summary of our linear model
lm_1.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_1
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_1 = X_train_new_1.drop(["ttl_surv._child._p"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_1 = sm.add_constant(X_train_new_1)

In [ ]:
# Running the linear model
lm_2 = sm.OLS(y_train,X_train_new_1).fit()

In [ ]:
lm_2.params

In [ ]:
#Let's see the summary of our linear model
lm_2.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_1
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_2 = X_train_new_1.drop(["total_ever_unmarried_women_%_y"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_2 = sm.add_constant(X_train_new_2)

In [ ]:
# Running the linear model
lm_3 = sm.OLS(y_train,X_train_new_2).fit()

In [ ]:
lm_3.params

In [ ]:
#Let's see the summary of our linear model
lm_3.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_2
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_3 = X_train_new_2.drop(["total_children_ever_born_f"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_3 = sm.add_constant(X_train_new_3)

In [ ]:
# Running the linear model
lm_4 = sm.OLS(y_train,X_train_new_3).fit()

In [ ]:
lm_4.params

In [ ]:
#Let's see the summary of our linear model
lm_4.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_3
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_4 = X_train_new_3.drop(["last_year’s_births_of_order_5"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_4 = sm.add_constant(X_train_new_4)

In [ ]:
# Running the linear model
lm_5 = sm.OLS(y_train,X_train_new_4).fit()

In [ ]:
#Let's see the summary of our linear model
lm_5.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_4
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_5 = X_train_new_4.drop(["ttl_surv._child._m"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_5 = sm.add_constant(X_train_new_5)

In [ ]:
# Running the linear model
lm_6 = sm.OLS(y_train,X_train_new_5).fit()

In [ ]:
#Let's see the summary of our linear model
lm_6.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_5
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_6 = X_train_new_5.drop(["total_children_ever_born_m"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_6 = sm.add_constant(X_train_new_6)

In [ ]:
# Running the linear model
lm_7 = sm.OLS(y_train,X_train_new_6).fit()

In [ ]:
#Let's see the summary of our linear model
lm_7.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_6
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_7 = X_train_new_6.drop(["total_currently_married_women"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_7 = sm.add_constant(X_train_new_7)

In [ ]:
# Running the linear model
lm_8 = sm.OLS(y_train,X_train_new_7).fit()

In [ ]:
lm_8.params

In [ ]:
#Let's see the summary of our linear model
lm_8.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_7
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_8 = X_train_new_7.drop(["last_year’s_births_of_order_4"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_8 = sm.add_constant(X_train_new_8)

In [ ]:
# Running the linear model
lm_9 = sm.OLS(y_train,X_train_new_8).fit()

In [ ]:
#Let's see the summary of our linear model
lm_9.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_8
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_9 = X_train_new_8.drop(["number_of_births_last_year_f"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_9 = sm.add_constant(X_train_new_9)

In [ ]:
# Running the linear model
lm_10 = sm.OLS(y_train,X_train_new_9).fit()

In [ ]:
lm_10.params

In [ ]:
#Let's see the summary of our linear model
lm_10.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_9
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
vif['Features'].unique()

In [ ]:
y_train_price = lm_10.predict(X_train_new_9)

In [ ]:
y_train

In [ ]:
y_train_price = y_train_price.to_frame()

In [ ]:
z = y_train['total_survival_rate'] - y_train_price[0]
z

In [ ]:
# Plot the histogram of the error terms
fig = plt.figure()
sns.distplot(z, bins = 20)
plt.xlabel('Errors', fontsize = 18) 
plt.show()

In [ ]:
# Applying the scaling on the test sets
df_test[num_vars] = scaler.transform(df_test[num_vars])

In [ ]:
df_test.describe()

In [ ]:
# Dividing into X_test and y_test
y_test = df_test.pop('total_survival_rate')
X_test = df_test

In [ ]:
# Creating X_test_new dataframe by dropping variables from X_test
X_test_new = X_test[['ttl_surv._child._f', 'last_year’s_births_of_order_6', 'total_ever_married_women_%_y', 'ttl_surv._child._m_%','ttl_surv._child._f_%']]

# Adding a constant variable 
X_test_new = sm.add_constant(X_test_new)

In [ ]:
X_test_new

In [ ]:
# Making predictions
y_pred = lm_10.predict(X_test_new)

In [ ]:
# Plotting y_test and y_pred to understand the spread
plt.scatter(y_test, y_pred)
plt.title('y_test vs y_pred', fontsize = 20) 
plt.xlabel('y_test', fontsize = 18) 
plt.ylabel('y_pred', fontsize = 16)
plt.show()

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

price=−0.1108+0.391×carwidth+0.751×enginesize−0.082×boreratio−0.075×stroke+0.200×bmw+0.110×porsche+0.331×rear+0.168×three+0.203×two

# education

very high correlation

# economics

In [ ]:
print(economics.info())
print(economics.columns)

In [ ]:
# Seperating into categortical and numric
categorical = economics.select_dtypes(include=['object'])
numeric = economics.select_dtypes(exclude=['object'])
print(categorical.columns.values)
print(numeric.columns.values)

In [ ]:
# Creating dummies
category = ['area_name','total/rural/urban', 'present_age' ,'economic_activity']
dummy = pd.get_dummies(economics[category])
economics_1 = pd.concat([economics, dummy], axis=1)
economics_1 = economics_1.drop(category, axis=1)

In [ ]:
# Converting everything into float for model building
economics_1 = economics_1.astype('float')
economics_1.info()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Putting feature variable to X
X = economics_1.drop(['total_survival_rate'], axis=1)
X.head()

In [ ]:
# Putting response variable to y
y = economics_1['total_survival_rate']
y.head()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df_train, df_test = train_test_split(economics_1, train_size = 0.7, test_size = 0.3, random_state = 100)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [ ]:
# Apply scaler() to all the columns except the 'yes-no' and 'dummy' variables
num_vars = ['total_ever_married_women_x', 'parity_0', 'parity_1', 'parity_2',  'parity_3', 'parity_4', 'parity_5', 'parity_6', 'parity_7+','total_children_ever_born_p', 'total_children_ever_born_m', 'total_children_ever_born_f',  'total_ever_unmarried_women_x', 'parity_0_%', 'parity_1_%',  'parity_2_%', 'parity_3_%', 'parity_4_%', 'parity_5_%', 'parity_6_%', 'parity_7+_%', 'total_ever_married_women_%_x', 'total_ever_unmarried_women_%_x', 'total_children_ever_born_m_%','total_children_ever_born_f_%', 'no._of_surv._child._0','no._of_surv._child._1', 'no._of_surv._child._2', 'no._of_surv._child._3', 'no._of_surv._child._4','no._of_surv._child._5+', 'ttl_surv._child._p', 'ttl_surv._child._m','ttl_surv._child._f', 'total_ever_unmarried_women_%_y','total_ever_married_women_%_y', 'ttl_surv._child._m_%','ttl_surv._child._f_%', 'no._of_surv._child._0_%','no._of_surv._child._1_%', 'no._of_surv._child._2_%','no._of_surv._child._3_%', 'no._of_surv._child._4_%','no._of_surv._child._5+_%', 'total_women','total_currently_married_women', 'number_of_births_last_year_m','number_of_births_last_year_f', 'last_year’s_births_of_order_1','last_year’s_births_of_order_2', 'last_year’s_births_of_order_3','last_year’s_births_of_order_4', 'last_year’s_births_of_order_5','last_year’s_births_of_order_6', 'last_year’s_births_of_order_7+','total_currently_unmarried_women', 'number_of_births_last_year_p','last_year’s_births_of_order_1_%', 'last_year’s_births_of_order_2_%', 'last_year’s_births_of_order_3_%', 'last_year’s_births_of_order_4_%','last_year’s_births_of_order_5_%', 'last_year’s_births_of_order_6_%','last_year’s_births_of_order_7+_%', 'number_of_births_last_year_m_%','number_of_births_last_year_f_%', 'total_currently_unmarried_women_%','total_currently_married_women_%', 'total_survival_rate']
df_train[num_vars] = scaler.fit_transform(df_train[num_vars])
df_train

In [ ]:
y_train = df_train.pop('total_survival_rate')
X_train = df_train

In [ ]:
y_train = y_train.to_frame()
y_train

In [ ]:
X_train

In [ ]:
# Importing RFE and LinearRegression
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [ ]:
# Running RFE with the output number of the variable equal to 10
lm = LinearRegression()
lm.fit(X_train, y_train)
# running RFE
rfe = RFE(lm, 15)
rfe = rfe.fit(X_train, y_train)

In [ ]:
list(zip(X_train.columns,rfe.support_,rfe.ranking_))

In [ ]:
col = X_train.columns[rfe.support_]
col

In [ ]:
X_train.columns[~rfe.support_]

In [ ]:
# Creating X_test dataframe with RFE selected variables
X_train_rfe = X_train[col]

In [ ]:
# Adding a constant variable 
import statsmodels.api as sm  
X_train_rfe = sm.add_constant(X_train_rfe)

In [ ]:
# Running the linear model
lm = sm.OLS(y_train,X_train_rfe).fit()

In [ ]:
lm.params

In [ ]:
#Let's see the summary of our linear model
lm.summary()

In [ ]:
# Calculate the VIFs for the new model
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()
X = X_train_rfe
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new = X_train_rfe.drop(["total_children_ever_born_p"], axis = 1)

In [ ]:
# Adding a constant variable 
X_train_new_1 = sm.add_constant(X_train_new)

In [ ]:
# Running the linear model
lm_1 = sm.OLS(y_train,X_train_new_1).fit()

In [ ]:
lm_1.params

In [ ]:
#Let's see the summary of our linear model
lm_1.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_1
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_1 = X_train_new_1.drop(["ttl_surv._child._p"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_1 = sm.add_constant(X_train_new_1)

In [ ]:
# Running the linear model
lm_2 = sm.OLS(y_train,X_train_new_1).fit()

In [ ]:
lm_2.params

In [ ]:
#Let's see the summary of our linear model
lm_2.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_1
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_2 = X_train_new_1.drop(["total_ever_unmarried_women_%_y"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_2 = sm.add_constant(X_train_new_2)

In [ ]:
# Running the linear model
lm_3 = sm.OLS(y_train,X_train_new_2).fit()

In [ ]:
lm_3.params

In [ ]:
#Let's see the summary of our linear model
lm_3.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_2
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_3 = X_train_new_2.drop(["total_women"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_3 = sm.add_constant(X_train_new_3)

In [ ]:
# Running the linear model
lm_4 = sm.OLS(y_train,X_train_new_3).fit()

In [ ]:
lm_4.params

In [ ]:
#Let's see the summary of our linear model
lm_4.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_3
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_4 = X_train_new_3.drop(["total_children_ever_born_m"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_4 = sm.add_constant(X_train_new_4)

In [ ]:
# Running the linear model
lm_5 = sm.OLS(y_train,X_train_new_4).fit()

In [ ]:
#Let's see the summary of our linear model
lm_5.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_4
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_5 = X_train_new_4.drop(["number_of_births_last_year_p"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_5 = sm.add_constant(X_train_new_5)

In [ ]:
# Running the linear model
lm_6 = sm.OLS(y_train,X_train_new_5).fit()

In [ ]:
#Let's see the summary of our linear model
lm_6.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_5
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_6 = X_train_new_5.drop(["ttl_surv._child._f"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_6 = sm.add_constant(X_train_new_6)

In [ ]:
# Running the linear model
lm_7 = sm.OLS(y_train,X_train_new_6).fit()

In [ ]:
#Let's see the summary of our linear model
lm_7.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_6
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_7 = X_train_new_6.drop(["ttl_surv._child._m"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_7 = sm.add_constant(X_train_new_7)

In [ ]:
# Running the linear model
lm_8 = sm.OLS(y_train,X_train_new_7).fit()

In [ ]:
lm_8.params

In [ ]:
#Let's see the summary of our linear model
lm_8.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_7
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_8 = X_train_new_7.drop(["total_currently_married_women"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_8 = sm.add_constant(X_train_new_8)

In [ ]:
# Running the linear model
lm_9 = sm.OLS(y_train,X_train_new_8).fit()

In [ ]:
#Let's see the summary of our linear model
lm_9.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_8
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
X_train_new_9 = X_train_new_8.drop(["total_children_ever_born_f"], axis = 1)

In [ ]:
# Adding a constant variable  
X_train_new_9 = sm.add_constant(X_train_new_9)

In [ ]:
# Running the linear model
lm_10 = sm.OLS(y_train,X_train_new_9).fit()

In [ ]:
lm_10.params

In [ ]:
#Let's see the summary of our linear model
lm_10.summary()

In [ ]:
# Calculate the VIFs for the new model
vif = pd.DataFrame()
X = X_train_new_9
vif['Features'] = X.columns
vif['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

In [ ]:
y_train_price = lm_10.predict(X_train_new_9)

In [ ]:
y_train

In [ ]:
y_train_price = y_train_price.to_frame()

In [ ]:
z = y_train['total_survival_rate'] - y_train_price[0]
z

In [ ]:
# Plot the histogram of the error terms
fig = plt.figure()
sns.distplot(z, bins = 20)
plt.xlabel('Errors', fontsize = 18) 
plt.show()

In [ ]:
# Applying the scaling on the test sets
df_test[num_vars] = scaler.transform(df_test[num_vars])

In [ ]:
df_test.describe()

In [ ]:
# Dividing into X_test and y_test
y_test = df_test.pop('total_survival_rate')
X_test = df_test

In [ ]:
vif['Features'].unique()

In [ ]:
# Creating X_test_new dataframe by dropping variables from X_test
X_test_new = X_test[['total_ever_married_women_%_y', 'ttl_surv._child._m_%','ttl_surv._child._f_%', 'total_currently_unmarried_women', 'number_of_births_last_year_m']]

# Adding a constant variable 
X_test_new = sm.add_constant(X_test_new)

In [ ]:
X_test_new

In [ ]:
# Making predictions
y_pred = lm_10.predict(X_test_new)

In [ ]:
# Plotting y_test and y_pred to understand the spread
plt.scatter(y_test, y_pred)
plt.title('y_test vs y_pred', fontsize = 20) 
plt.xlabel('y_test', fontsize = 18) 
plt.ylabel('y_pred', fontsize = 16)
plt.show()

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

price=−0.1108+0.391×carwidth+0.751×enginesize−0.082×boreratio−0.075×stroke+0.200×bmw+0.110×porsche+0.331×rear+0.168×three+0.203×two